import type { Request, Response } from "express"; import { sendSuccess } from "../../common/utils/response.js"; import { approveRefund, cancelRefund, createRefundRequest, getRefund, listAdminRefunds, listMyRefunds, rejectRefund } from "./refund.service.js"; import type { CreateRefundInput, ReviewRefundInput } from "./refund.types.js";
const id = (request: Request) => String(request.params.id ?? "");
export async function createController(request: Request, response: Response) { sendSuccess(response, 201, "Refund request created successfully", await createRefundRequest(request.auth.userId, request.body as CreateRefundInput)); }
export async function mineController(request: Request, response: Response) { sendSuccess(response, 200, "Refund requests retrieved successfully", await listMyRefunds(request.auth.userId)); }
export async function detailController(request: Request, response: Response) { sendSuccess(response, 200, "Refund request retrieved successfully", await getRefund(id(request), request.auth.userId, request.auth.role === "ADMIN")); }
export async function cancelController(request: Request, response: Response) { sendSuccess(response, 200, "Refund request cancelled successfully", await cancelRefund(id(request), request.auth.userId)); }
export async function adminListController(request: Request, response: Response) { const result = await listAdminRefunds(request.query); response.status(200).json({ success: true, message: "Refund requests retrieved successfully", ...result }); }
export async function approveController(request: Request, response: Response) { sendSuccess(response, 200, "Refund processed successfully", await approveRefund(id(request), request.auth.userId, request.body as ReviewRefundInput, String(request.headers["idempotency-key"] ?? ""))); }
export async function rejectController(request: Request, response: Response) { sendSuccess(response, 200, "Refund request rejected successfully", await rejectRefund(id(request), request.auth.userId, request.body as ReviewRefundInput)); }
