import { AppError } from "../../common/errors/AppError.js";
import { prisma } from "../../config/database.js";
import { env } from "../../config/env.js";
import { mockPaymentGateway } from "../../services/payments/mock-payment.gateway.js";
import type { PaymentGateway } from "../../services/payments/payment-gateway.interface.js";
import { UUID } from "../interactions/access.js";
import type { CreateRefundInput, ReviewRefundInput } from "./refund.types.js";

const include = { order: { select: { id: true, orderNumber: true, status: true, total: true, currency: true } }, payment: { select: { id: true, status: true, amount: true, currency: true, provider: true, providerTransactionId: true, paidAt: true } }, refunds: { orderBy: { createdAt: "desc" as const } }, reviewer: { select: { id: true, fullName: true } } };
function serialize<T extends Record<string, any>>(value: T) { return { ...value, requestedAmount: Number(value.requestedAmount), approvedAmount: value.approvedAmount === null ? null : Number(value.approvedAmount), order: value.order ? { ...value.order, total: Number(value.order.total) } : value.order, payment: value.payment ? { ...value.payment, amount: Number(value.payment.amount) } : value.payment, refunds: value.refunds?.map((refund: Record<string, any>) => ({ ...refund, amount: Number(refund.amount) })) }; }
function fail(code: string, message: string, status = 409): never { throw new AppError(status, message, { code }); }

export async function createRefundRequest(userId: string, input: CreateRefundInput) {
  const order = await prisma.order.findFirst({ where: { id: input.orderId, userId }, include: { payments: { where: { status: "SUCCEEDED" }, orderBy: { paidAt: "desc" }, take: 1 } } });
  if (!order || order.status !== "PAID" || !order.payments[0]?.paidAt) fail("REFUND_NOT_ALLOWED", "Không tìm thấy đơn hàng đã thanh toán phù hợp", 404);
  const payment = order.payments[0];
  const paidAt = payment.paidAt!;
  const refundWindowMs = (env.commerceRefundWindowDays || 1) * 86_400_000;
  if (Date.now() > paidAt.getTime() + refundWindowMs) {
    fail("REFUND_WINDOW_EXPIRED", "Yêu cầu hoàn tiền bị từ chối: Đã quá thời hạn 1 ngày (24 giờ) kể từ khi mua khóa học");
  }
  const active = await prisma.refundRequest.findFirst({ where: { paymentId: payment.id, status: { in: ["PENDING", "APPROVED", "PROCESSING", "REFUNDED"] } }, select: { id: true } }); if (active) fail("REFUND_ALREADY_EXISTS", "A refund request already exists for this payment");
  const courseIds = (await prisma.orderItem.findMany({ where: { orderId: order.id }, select: { courseId: true } })).map(item => item.courseId);
  const progress = await prisma.enrollment.findMany({ where: { studentId: userId, courseId: { in: courseIds } }, select: { progressPercent: true } }); if (progress.some(item => Number(item.progressPercent) > env.commerceRefundMaxProgressPercent)) fail("REFUND_NOT_ALLOWED", "Course progress exceeds the refund policy threshold");
  try { return serialize(await prisma.refundRequest.create({ data: { userId, orderId: order.id, paymentId: payment.id, reason: input.reason, requestedAmount: payment.amount }, include })); } catch (error) { if (error && typeof error === "object" && "code" in error && error.code === "P2002") fail("REFUND_ALREADY_EXISTS", "A refund request already exists for this payment"); throw error; }
}
export async function listMyRefunds(userId: string) { return (await prisma.refundRequest.findMany({ where: { userId }, orderBy: { createdAt: "desc" }, include })).map(serialize); }
export async function getRefund(id: string, userId: string, admin = false) { if (!UUID.test(id)) throw new AppError(404, "Refund request not found"); const value = await prisma.refundRequest.findUnique({ where: { id }, include }); if (!value || (!admin && value.userId !== userId)) throw new AppError(404, "Refund request not found"); return serialize(value); }
export async function cancelRefund(id: string, userId: string) { const result = await prisma.refundRequest.updateMany({ where: { id, userId, status: "PENDING" }, data: { status: "CANCELLED" } }); if (!result.count) fail("INVALID_REFUND_STATUS", "Only a pending refund request can be cancelled"); return getRefund(id, userId); }
export async function listAdminRefunds(query: Record<string, unknown>) { const page = Number(query.page ?? 1), limit = Number(query.limit ?? 20); if (!Number.isInteger(page) || page < 1 || !Number.isInteger(limit) || limit < 1 || limit > 100) throw new AppError(400, "Invalid pagination"); const allowed = ["PENDING", "APPROVED", "REJECTED", "PROCESSING", "REFUNDED", "FAILED", "CANCELLED"]; if (query.status !== undefined && !allowed.includes(String(query.status))) throw new AppError(400, "Invalid refund status"); const where = query.status ? { status: query.status as any } : {}; const [rows, total] = await Promise.all([prisma.refundRequest.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit, include: { ...include, user: { select: { id: true, fullName: true, email: true } } } }), prisma.refundRequest.count({ where })]); return { data: rows.map(serialize), meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
export async function rejectRefund(id: string, adminId: string, input: ReviewRefundInput) { const result = await prisma.refundRequest.updateMany({ where: { id, status: "PENDING" }, data: { status: "REJECTED", adminNote: input.adminNote, reviewedById: adminId, reviewedAt: new Date() } }); if (!result.count) fail("INVALID_REFUND_STATUS", "Only a pending refund request can be rejected"); await prisma.auditLog.create({ data: { actorUserId: adminId, action: "REFUND_REJECTED", entityType: "RefundRequest", entityId: id, metadata: { adminNote: input.adminNote } } }); return getRefund(id, adminId, true); }

export async function approveRefund(id: string, adminId: string, input: ReviewRefundInput, idempotencyKey: string, gateway: PaymentGateway = mockPaymentGateway) {
  if (!UUID.test(id)) throw new AppError(404, "Refund request not found"); if (!idempotencyKey || idempotencyKey.length > 255) throw new AppError(400, "A valid Idempotency-Key header is required");
  const existing = await prisma.paymentRefund.findUnique({ where: { idempotencyKey }, include: { refundRequest: true } }); if (existing) { if (existing.refundRequestId !== id) throw new AppError(409, "Idempotency key belongs to another refund"); return getRefund(id, adminId, true); }
  const request = await prisma.refundRequest.findUnique({ where: { id }, include: { payment: true, order: { include: { items: true } } } }); if (!request) throw new AppError(404, "Refund request not found"); if (request.status !== "PENDING" && request.status !== "FAILED") fail("INVALID_REFUND_STATUS", "Refund request cannot be approved from its current status");
  if (await prisma.instructorEarning.count({ where: { orderId: request.orderId, status: "PAID" } })) fail("REFUND_NOT_ALLOWED", "Paid instructor earnings cannot be refunded in this Sprint");
  const claimed = await prisma.$transaction(async transaction => { const state = await transaction.refundRequest.updateMany({ where: { id, status: { in: ["PENDING", "FAILED"] } }, data: { status: "PROCESSING", approvedAmount: request.requestedAmount, adminNote: input.adminNote, reviewedById: adminId, reviewedAt: new Date() } }); if (!state.count) { const duplicate = await transaction.paymentRefund.findUnique({ where: { idempotencyKey }, select: { refundRequestId: true } }); if (duplicate?.refundRequestId === id) return false; fail("INVALID_REFUND_STATUS", "Refund request is already being processed"); } await transaction.paymentRefund.create({ data: { refundRequestId: id, paymentId: request.paymentId, idempotencyKey, amount: request.requestedAmount, status: "PROCESSING" } }); return true; });
  if (!claimed) return getRefund(id, adminId, true);
  let provider;
  try { provider = await gateway.refundPayment({ paymentId: request.paymentId, providerTransactionId: request.payment.providerTransactionId, amount: Number(request.requestedAmount), currency: request.payment.currency, idempotencyKey }); } catch (error) { provider = { success: false, failureReason: error instanceof Error ? error.message : "Payment provider failed" }; }
  if (!provider.success) { await prisma.$transaction([prisma.paymentRefund.update({ where: { idempotencyKey }, data: { status: "FAILED", failureReason: provider.failureReason ?? "Payment provider failed", processedAt: new Date() } }), prisma.refundRequest.update({ where: { id }, data: { status: "FAILED" } })]); return getRefund(id, adminId, true); }
  const processedAt = new Date(); await prisma.$transaction(async transaction => {
    await transaction.paymentRefund.update({ where: { idempotencyKey }, data: { status: "SUCCEEDED", providerRefundId: provider.providerRefundId, providerPayload: provider.payload, processedAt, failureReason: null } });
    await transaction.refundRequest.update({ where: { id }, data: { status: "REFUNDED" } }); await transaction.payment.update({ where: { id: request.paymentId }, data: { status: "REFUNDED" } }); await transaction.order.update({ where: { id: request.orderId }, data: { status: "REFUNDED" } });
    const courseIds = request.order.items.map(item => item.courseId); await transaction.enrollment.updateMany({ where: { studentId: request.userId, courseId: { in: courseIds } }, data: { status: "REFUNDED" } }); await transaction.certificate.updateMany({ where: { studentId: request.userId, courseId: { in: courseIds }, revokedAt: null }, data: { revokedAt: processedAt } }); await transaction.instructorEarning.updateMany({ where: { orderId: request.orderId, status: { in: ["PENDING", "AVAILABLE"] } }, data: { status: "REVERSED", reversedAt: processedAt } });
    await transaction.auditLog.create({ data: { actorUserId: adminId, action: "REFUND_APPROVED", entityType: "RefundRequest", entityId: id, metadata: { idempotencyKey, providerRefundId: provider.providerRefundId ?? null } } });
  }); return getRefund(id, adminId, true);
}
