
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model AuthSession
 * 
 */
export type AuthSession = Prisma.AuthSessionModel
/**
 * Model AuthToken
 * 
 */
export type AuthToken = Prisma.AuthTokenModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Course
 * 
 */
export type Course = Prisma.CourseModel
/**
 * Model Section
 * 
 */
export type Section = Prisma.SectionModel
/**
 * Model Lesson
 * 
 */
export type Lesson = Prisma.LessonModel
/**
 * Model Enrollment
 * 
 */
export type Enrollment = Prisma.EnrollmentModel
/**
 * Model LessonProgress
 * 
 */
export type LessonProgress = Prisma.LessonProgressModel
/**
 * Model Quiz
 * 
 */
export type Quiz = Prisma.QuizModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model QuizOption
 * 
 */
export type QuizOption = Prisma.QuizOptionModel
/**
 * Model QuizAttempt
 * 
 */
export type QuizAttempt = Prisma.QuizAttemptModel
/**
 * Model AttemptAnswer
 * 
 */
export type AttemptAnswer = Prisma.AttemptAnswerModel
/**
 * Model Assignment
 * 
 */
export type Assignment = Prisma.AssignmentModel
/**
 * Model AssignmentSubmission
 * 
 */
export type AssignmentSubmission = Prisma.AssignmentSubmissionModel
/**
 * Model SubmissionFile
 * 
 */
export type SubmissionFile = Prisma.SubmissionFileModel
/**
 * Model SubmissionFeedback
 * 
 */
export type SubmissionFeedback = Prisma.SubmissionFeedbackModel
/**
 * Model CourseGradeRule
 * 
 */
export type CourseGradeRule = Prisma.CourseGradeRuleModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model NotificationPreference
 * 
 */
export type NotificationPreference = Prisma.NotificationPreferenceModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model CourseAnnouncement
 * 
 */
export type CourseAnnouncement = Prisma.CourseAnnouncementModel
/**
 * Model LearningEvent
 * 
 */
export type LearningEvent = Prisma.LearningEventModel
/**
 * Model VideoWatchEvent
 * 
 */
export type VideoWatchEvent = Prisma.VideoWatchEventModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model PaymentWebhookEvent
 * 
 */
export type PaymentWebhookEvent = Prisma.PaymentWebhookEventModel
/**
 * Model Certificate
 * 
 */
export type Certificate = Prisma.CertificateModel
/**
 * Model Coupon
 * 
 */
export type Coupon = Prisma.CouponModel
/**
 * Model CouponCourse
 * 
 */
export type CouponCourse = Prisma.CouponCourseModel
/**
 * Model CouponUsage
 * 
 */
export type CouponUsage = Prisma.CouponUsageModel
/**
 * Model RefundRequest
 * 
 */
export type RefundRequest = Prisma.RefundRequestModel
/**
 * Model PaymentRefund
 * 
 */
export type PaymentRefund = Prisma.PaymentRefundModel
/**
 * Model InstructorEarning
 * 
 */
export type InstructorEarning = Prisma.InstructorEarningModel
/**
 * Model Payout
 * 
 */
export type Payout = Prisma.PayoutModel
