
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  STUDENT: 'STUDENT',
  INSTRUCTOR: 'INSTRUCTOR',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const UserStatus = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const CourseLevel = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED'
} as const

export type CourseLevel = (typeof CourseLevel)[keyof typeof CourseLevel]


export const CourseStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
} as const

export type CourseStatus = (typeof CourseStatus)[keyof typeof CourseStatus]


export const LessonType = {
  VIDEO: 'VIDEO',
  TEXT: 'TEXT',
  DOCUMENT: 'DOCUMENT'
} as const

export type LessonType = (typeof LessonType)[keyof typeof LessonType]


export const EnrollmentStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type EnrollmentStatus = (typeof EnrollmentStatus)[keyof typeof EnrollmentStatus]


export const QuizAttemptStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED'
} as const

export type QuizAttemptStatus = (typeof QuizAttemptStatus)[keyof typeof QuizAttemptStatus]


export const OrderStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const PaymentProvider = {
  MOCK: 'MOCK',
  VNPAY: 'VNPAY'
} as const

export type PaymentProvider = (typeof PaymentProvider)[keyof typeof PaymentProvider]


export const PaymentStatus = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const CouponDiscountType = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED_AMOUNT: 'FIXED_AMOUNT'
} as const

export type CouponDiscountType = (typeof CouponDiscountType)[keyof typeof CouponDiscountType]


export const CouponUsageStatus = {
  REDEEMED: 'REDEEMED',
  RELEASED: 'RELEASED'
} as const

export type CouponUsageStatus = (typeof CouponUsageStatus)[keyof typeof CouponUsageStatus]


export const RefundRequestStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSING: 'PROCESSING',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
} as const

export type RefundRequestStatus = (typeof RefundRequestStatus)[keyof typeof RefundRequestStatus]


export const PaymentRefundStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED'
} as const

export type PaymentRefundStatus = (typeof PaymentRefundStatus)[keyof typeof PaymentRefundStatus]


export const EarningStatus = {
  PENDING: 'PENDING',
  AVAILABLE: 'AVAILABLE',
  PAID: 'PAID',
  REVERSED: 'REVERSED'
} as const

export type EarningStatus = (typeof EarningStatus)[keyof typeof EarningStatus]


export const PayoutStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
} as const

export type PayoutStatus = (typeof PayoutStatus)[keyof typeof PayoutStatus]


export const AuthTokenType = {
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL'
} as const

export type AuthTokenType = (typeof AuthTokenType)[keyof typeof AuthTokenType]


export const AssignmentSubmissionStatus = {
  SUBMITTED: 'SUBMITTED',
  GRADED: 'GRADED'
} as const

export type AssignmentSubmissionStatus = (typeof AssignmentSubmissionStatus)[keyof typeof AssignmentSubmissionStatus]


export const NotificationType = {
  WELCOME: 'WELCOME',
  COURSE_ENROLLED: 'COURSE_ENROLLED',
  NEW_LESSON: 'NEW_LESSON',
  ASSIGNMENT_DUE: 'ASSIGNMENT_DUE',
  QUIZ_RESULT: 'QUIZ_RESULT',
  CERTIFICATE_ISSUED: 'CERTIFICATE_ISSUED',
  COURSE_ANNOUNCEMENT: 'COURSE_ANNOUNCEMENT'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const EmailStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
} as const

export type EmailStatus = (typeof EmailStatus)[keyof typeof EmailStatus]


export const AnnouncementStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED'
} as const

export type AnnouncementStatus = (typeof AnnouncementStatus)[keyof typeof AnnouncementStatus]


export const LearningEventType = {
  COURSE_OPENED: 'COURSE_OPENED',
  LESSON_STARTED: 'LESSON_STARTED',
  LESSON_COMPLETED: 'LESSON_COMPLETED',
  QUIZ_STARTED: 'QUIZ_STARTED',
  QUIZ_SUBMITTED: 'QUIZ_SUBMITTED',
  STUDY_SESSION: 'STUDY_SESSION'
} as const

export type LearningEventType = (typeof LearningEventType)[keyof typeof LearningEventType]
