import assert from "node:assert/strict";
import jwt from "jsonwebtoken";
import { prisma } from "../../dist/config/database.js";
const api="http://localhost:3000/api/v1",stamp=Date.now().toString(),emails=["admin","student","owner"].map(x=>`sprint5-${x}-${stamp}@example.com`);const token=u=>`Bearer ${jwt.sign({userId:u.id,role:u.role},process.env.JWT_ACCESS_SECRET,{expiresIn:"15m"})}`;const json=(url,method,authorization,body)=>fetch(url,{method,headers:{authorization,"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});
let categoryId,courseId;
try {
  const [admin,student,owner]=await Promise.all([prisma.user.create({data:{fullName:"Admin S5",email:emails[0],passwordHash:"x",role:"ADMIN"}}),prisma.user.create({data:{fullName:"Student S5",email:emails[1],passwordHash:"x"}}),prisma.user.create({data:{fullName:"Owner S5",email:emails[2],passwordHash:"x",role:"INSTRUCTOR"}})]);const adminAuth=token(admin),studentAuth=token(student);
  const category=await prisma.category.create({data:{name:`Sprint5 ${stamp}`,slug:`sprint5-${stamp}`}});categoryId=category.id;const course=await prisma.course.create({data:{instructorId:owner.id,categoryId,title:"Moderated course",slug:`moderated-${stamp}`,description:"Test",level:"BEGINNER",isFree:true,status:"PUBLISHED",publishedAt:new Date()}});courseId=course.id;const section=await prisma.section.create({data:{courseId,title:"Section",position:1}});const lesson=await prisma.lesson.create({data:{sectionId:section.id,title:"Lesson",lessonType:"TEXT",content:"Text",position:1,isPublished:true}});const review=await prisma.review.create({data:{courseId,userId:student.id,rating:1,content:"Spam"}});const comment=await prisma.comment.create({data:{lessonId:lesson.id,userId:student.id,content:"Spam comment"}});
  assert.equal((await fetch(`${api}/admin/dashboard`,{headers:{authorization:studentAuth}})).status,403);
  const dashboardResponse=await fetch(`${api}/admin/dashboard`,{headers:{authorization:adminAuth}});assert.equal(dashboardResponse.status,200);const dashboard=(await dashboardResponse.json()).data;assert.ok(dashboard.users.total>=3);assert.ok(dashboard.courses.total>=1);
  const users=(await (await fetch(`${api}/admin/users?search=${encodeURIComponent(emails[1])}`,{headers:{authorization:adminAuth}})).json()).data;assert.equal(users.items.length,1);assert.equal(Object.hasOwn(users.items[0],"passwordHash"),false);
  const block=await json(`${api}/admin/users/${student.id}`,"PATCH",adminAuth,{status:"BLOCKED"});assert.equal(block.status,200);assert.equal((await block.json()).data.status,"BLOCKED");assert.equal((await json(`${api}/admin/users/${admin.id}`,"PATCH",adminAuth,{status:"BLOCKED"})).status,409);
  const archive=await json(`${api}/admin/courses/${course.id}`,"PATCH",adminAuth,{status:"ARCHIVED"});assert.equal(archive.status,200);assert.equal((await archive.json()).data.status,"ARCHIVED");
  assert.equal((await fetch(`${api}/admin/reviews/${review.id}`,{method:"DELETE",headers:{authorization:adminAuth}})).status,204);assert.equal(await prisma.review.count({where:{id:review.id}}),0);
  assert.equal((await fetch(`${api}/admin/comments/${comment.id}`,{method:"DELETE",headers:{authorization:adminAuth}})).status,204);assert.ok((await prisma.comment.findUniqueOrThrow({where:{id:comment.id}})).deletedAt);
  const headers=await fetch(`${api}/categories`);assert.equal(headers.headers.get("x-content-type-options"),"nosniff");assert.equal(headers.headers.get("x-powered-by"),null);assert.ok(headers.headers.get("ratelimit-policy"));
  console.log("Sprint 5 admin and security integration tests passed");
} finally {if(courseId)await prisma.course.deleteMany({where:{id:courseId}});if(categoryId)await prisma.category.deleteMany({where:{id:categoryId}});await prisma.user.deleteMany({where:{email:{in:emails}}});await prisma.$disconnect();}
