import { unlink } from "node:fs/promises"; import path from "node:path"; import type { Request, Response } from "express";
import { AppError } from "../../common/errors/AppError.js";
import { sendSuccess } from "../../common/utils/response.js";
import { deleteFromCloudinary, isCloudinaryConfigured, uploadFileToCloudinary } from "../../config/cloudinary.js";
import { isValidStoredImage, QUIZ_IMAGE_DIRECTORY } from "../../config/upload.js";
import type { OptionInput, QuestionInput, QuizInput, SubmitAttemptInput, UpdateOptionInput, UpdateQuestionInput, UpdateQuizInput } from "./quizzes.types.js";
import { createOption, createQuestion, createQuiz, createSectionQuiz, deleteOption, deleteQuestion, deleteQuiz, getQuiz, listMyAttempts, removeQuestionImage, setQuestionImage, startAttempt, submitAttempt, updateOption, updateQuestion, updateQuiz } from "./quizzes.service.js";
const p = (request: Request, key: string) => String(request.params[key] ?? "");
export async function createQuizController(request: Request, response: Response) { sendSuccess(response, 201, "Quiz created successfully", await createQuiz(p(request, "lessonId"), request.auth, request.body as QuizInput)); }
export async function createSectionQuizController(request: Request, response: Response) { sendSuccess(response, 201, "Section quiz created successfully", await createSectionQuiz(p(request, "sectionId"), request.auth, request.body as QuizInput)); }
export async function getQuizController(request: Request, response: Response) { sendSuccess(response, 200, "Quiz retrieved successfully", await getQuiz(p(request, "quizId"), request.auth)); }
export async function updateQuizController(request: Request, response: Response) { sendSuccess(response, 200, "Quiz updated successfully", await updateQuiz(p(request, "quizId"), request.auth, request.body as UpdateQuizInput)); }
export async function deleteQuizController(request: Request, response: Response) { await deleteQuiz(p(request, "quizId"), request.auth); response.status(204).send(); }
export async function createQuestionController(request: Request, response: Response) { sendSuccess(response, 201, "Question created successfully", await createQuestion(p(request, "quizId"), request.auth, request.body as QuestionInput)); }
export async function updateQuestionController(request: Request, response: Response) { sendSuccess(response, 200, "Question updated successfully", await updateQuestion(p(request, "questionId"), request.auth, request.body as UpdateQuestionInput)); }
export async function deleteQuestionController(request: Request, response: Response) { await removeImage(await deleteQuestion(p(request, "questionId"), request.auth)); response.status(204).send(); }
async function removeImage(url:string|null){if(!url)return;if(url.includes("cloudinary.com"))await deleteFromCloudinary(url,"image");else await unlink(path.join(QUIZ_IMAGE_DIRECTORY,path.basename(url))).catch(()=>undefined);}
export async function uploadQuestionImageController(request:Request,response:Response){if(!request.file)throw new AppError(400,"Question image is required");if(!(await isValidStoredImage(request.file.path,request.file.mimetype))){await unlink(request.file.path).catch(()=>undefined);throw new AppError(400,"Question image content is invalid");}let url:string;if(isCloudinaryConfigured()){try{url=(await uploadFileToCloudinary(request.file.path,{folder:"lms/quiz-questions",resourceType:"image"})).secure_url;}finally{await unlink(request.file.path).catch(()=>undefined);}}else url=`${request.protocol}://${request.get("host")}/uploads/quiz-images/${request.file.filename}`;try{const result=await setQuestionImage(p(request,"questionId"),request.auth,url);await removeImage(result.previousUrl);sendSuccess(response,200,"Question image uploaded successfully",result.question);}catch(error){if(!isCloudinaryConfigured())await unlink(request.file.path).catch(()=>undefined);throw error;}}
export async function deleteQuestionImageController(request:Request,response:Response){await removeImage(await removeQuestionImage(p(request,"questionId"),request.auth));response.status(204).send();}
export async function createOptionController(request: Request, response: Response) { sendSuccess(response, 201, "Option created successfully", await createOption(p(request, "questionId"), request.auth, request.body as OptionInput)); }
export async function updateOptionController(request: Request, response: Response) { sendSuccess(response, 200, "Option updated successfully", await updateOption(p(request, "optionId"), request.auth, request.body as UpdateOptionInput)); }
export async function deleteOptionController(request: Request, response: Response) { await deleteOption(p(request, "optionId"), request.auth); response.status(204).send(); }
export async function startAttemptController(request: Request, response: Response) { sendSuccess(response, 201, "Quiz attempt started successfully", await startAttempt(p(request, "quizId"), request.auth.userId)); }
export async function listMyAttemptsController(request: Request, response: Response) { sendSuccess(response, 200, "Quiz attempts retrieved successfully", await listMyAttempts(p(request, "quizId"), request.auth.userId)); }
export async function submitAttemptController(request: Request, response: Response) { sendSuccess(response, 200, "Quiz submitted successfully", await submitAttempt(p(request, "attemptId"), request.auth.userId, request.body as SubmitAttemptInput)); }
