<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'
import { useApi } from '@/composables/useApi'
import type { ApiResponse, Assignment, CourseGrade } from '@/types'

const route=useRoute(),api=useApi(),courseId=String(route.params.courseId),items=ref<Assignment[]>([]),grade=ref<CourseGrade|null>(null),error=ref('')
const pending=computed(()=>items.value.filter(item=>!item.submissions?.length).length),graded=computed(()=>items.value.filter(item=>item.submissions?.[0]?.feedback).length)
const formatDate=(date:string)=>new Date(date).toLocaleString('vi-VN')
async function load(){try{const [assignments,result]=await Promise.all([api.get<ApiResponse<Assignment[]>>(`/courses/${courseId}/assignments`),api.get<ApiResponse<CourseGrade>>(`/courses/${courseId}/grades/me`)]);items.value=assignments.data||[];grade.value=result.data||null}catch(cause){error.value=cause instanceof Error?cause.message:'Không thể tải bài tập'}}
onMounted(load)
</script>

<template><DefaultLayout><main class="app-page max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><header><RouterLink to="/my-courses" class="text-sm font-bold text-purple-600">← Khóa học của tôi</RouterLink><p class="mt-4 text-sm font-bold uppercase tracking-wider text-purple-600">Bài tập & điểm số</p><h1 class="app-page-title mt-2">Kết quả học tập</h1><p class="app-page-description">Nộp bài đúng hạn, xem nhận xét và theo dõi điểm tổng kết khóa học.</p></header><p v-if="error" class="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{{error}}</p><section v-if="grade" class="mt-7 overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-700 via-purple-700 to-fuchsia-600 p-6 text-white shadow-xl sm:p-8"><div class="grid gap-6 sm:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold text-purple-100">Điểm tổng kết hiện tại</p><div class="mt-2 flex items-end gap-3"><span class="text-6xl font-black">{{grade.finalScore}}</span><span class="pb-2 text-xl text-purple-100">/ 100</span></div><span :class="['mt-4 inline-flex rounded-full px-3 py-1 text-xs font-black',grade.passed?'bg-emerald-400/20 text-emerald-100':'bg-amber-300/20 text-amber-100']">{{grade.passed?'Đạt yêu cầu':'Chưa đạt'}}</span></div><div class="grid min-w-64 grid-cols-2 gap-3"><div class="rounded-2xl bg-white/10 p-4"><p class="text-xs text-purple-100">Bài tập</p><b class="mt-1 block text-2xl">{{grade.assignment.percent}}%</b><p class="mt-1 text-xs text-purple-200">Trọng số {{grade.rule.assignmentWeight}}%</p></div><div class="rounded-2xl bg-white/10 p-4"><p class="text-xs text-purple-100">Quiz</p><b class="mt-1 block text-2xl">{{grade.quiz.percent}}%</b><p class="mt-1 text-xs text-purple-200">Trọng số {{grade.rule.quizWeight}}%</p></div></div></div></section>
<section class="mt-8 grid gap-4 sm:grid-cols-3"><article class="metric-card"><b class="text-2xl">{{items.length}}</b><span>Tổng bài tập</span></article><article class="metric-card"><b class="text-2xl text-amber-600">{{pending}}</b><span>Chưa nộp</span></article><article class="metric-card"><b class="text-2xl text-emerald-600">{{graded}}</b><span>Đã có điểm</span></article></section><LoadingSpinner v-if="api.loading.value&&!items.length" class="py-20"/>
<section v-else-if="items.length" class="mt-7 space-y-4"><RouterLink v-for="item in items" :key="item.id" :to="`/assignments/${item.id}`" class="surface-card group block p-6 transition hover:-translate-y-0.5 hover:border-purple-300 hover:shadow-md"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span :class="['rounded-full px-2.5 py-1 text-xs font-bold',item.submissions?.[0]?.feedback?'bg-emerald-100 text-emerald-700':item.submissions?.length?'bg-blue-100 text-blue-700':item.isOverdue?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700']">{{item.submissions?.[0]?.feedback?'Đã chấm':item.submissions?.length?'Đã nộp':item.isOverdue?'Quá hạn':'Cần thực hiện'}}</span><span class="text-xs text-slate-400">{{item.maxScore}} điểm</span></div><h2 class="mt-3 text-xl font-black group-hover:text-purple-700">{{item.title}}</h2><p class="mt-2 line-clamp-2 text-sm text-slate-500">{{item.description||'Xem hướng dẫn và nộp bài.'}}</p></div><div class="text-right"><p class="text-xs text-slate-400">Hạn nộp</p><b class="mt-1 block text-sm">{{formatDate(item.dueAt)}}</b><p v-if="item.submissions?.[0]?.feedback" class="mt-3 text-2xl font-black text-emerald-600">{{item.submissions[0].feedback.score}}/{{item.maxScore}}</p><span v-else class="mt-3 inline-block text-sm font-bold text-purple-600">Mở bài tập →</span></div></div></RouterLink></section>
<section v-else-if="!api.loading.value" class="surface-card mt-7 grid min-h-72 place-items-center p-8 text-center"><div><span class="text-5xl">🎉</span><h2 class="mt-4 text-xl font-black">Chưa có bài tập</h2><p class="mt-2 text-sm text-slate-500">Giảng viên chưa giao bài tập cho khóa học này.</p><RouterLink :to="`/learn/${courseId}`"><BaseButton class="mt-5">Tiếp tục học</BaseButton></RouterLink></div></section></main></DefaultLayout></template>

<style scoped>.metric-card{display:flex;align-items:center;justify-content:space-between;border:1px solid var(--border);border-radius:1.25rem;background:var(--surface);padding:1.25rem;box-shadow:var(--shadow-sm)}.metric-card span{font-size:.85rem;color:var(--text-muted);font-weight:700}</style>
