<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import { useApi } from '@/composables/useApi'
import type { ApiResponse, Quiz, QuizAttempt, QuizResult } from '@/types'
const route=useRoute(),router=useRouter(),api=useApi(),quizId=String(route.params.quizId)
const quiz=ref<Quiz|null>(null),attempts=ref<QuizAttempt[]>([]),attempt=ref<QuizAttempt|null>(null),answers=ref<Record<string,string>>({}),error=ref('')
async function load(){try{const [q,a]=await Promise.all([api.get<ApiResponse<Quiz>>(`/quizzes/${quizId}`),api.get<ApiResponse<QuizAttempt[]>>(`/quizzes/${quizId}/attempts/me`)]);quiz.value=q.data||null;attempts.value=a.data||[]}catch(e){error.value=e instanceof Error?e.message:'Không tải được bài kiểm tra'}}
async function start(){try{const r=await api.post<ApiResponse<QuizAttempt>>(`/quizzes/${quizId}/attempts`);attempt.value=r.data||null}catch(e){error.value=e instanceof Error?e.message:'Không bắt đầu được bài làm'}}
async function submit(){if(!quiz.value||!attempt.value)return;if(Object.keys(answers.value).length!==quiz.value.questions?.length){error.value='Vui lòng trả lời tất cả câu hỏi';return}try{const r=await api.post<ApiResponse<QuizResult>>(`/quiz-attempts/${attempt.value.id}/submit`,{answers:Object.entries(answers.value).map(([questionId,optionId])=>({questionId,optionId}))});sessionStorage.setItem('quizResult',JSON.stringify(r.data));router.push('/quiz-result')}catch(e){error.value=e instanceof Error?e.message:'Không nộp được bài'}}
onMounted(load)
</script>
<template><DefaultLayout><main class="mx-auto max-w-3xl px-4 py-10"><p v-if="error" class="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{{ error }}</p><div v-if="quiz" class="space-y-6"><header><h1 class="text-3xl font-extrabold">{{ quiz.title }}</h1><p class="mt-2 text-slate-500">Điểm đạt {{ quiz.passingScore }}% · Tối đa {{ quiz.maxAttempts }} lần · Đã làm {{ attempts.length }} lần</p></header><div v-if="!attempt" class="rounded-2xl border bg-white p-8 text-center dark:border-slate-800 dark:bg-slate-900"><p class="mb-5">Khi bắt đầu, hệ thống sẽ ghi nhận một lượt làm bài.</p><BaseButton @click="start">Bắt đầu làm bài</BaseButton></div><form v-else class="space-y-4" @submit.prevent="submit"><article v-for="(q,i) in quiz.questions" :key="q.id" class="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-bold">Câu {{ i+1 }}: {{ q.text }} <span class="text-sm text-slate-400">({{ q.points }} điểm)</span></h2><label v-for="o in q.options" :key="o.id" class="mt-3 flex cursor-pointer gap-3 rounded-xl border p-3" :class="answers[q.id]===o.id?'border-purple-500 bg-purple-50 dark:bg-purple-950/30':''"><input v-model="answers[q.id]" type="radio" :name="q.id" :value="o.id"><span>{{ o.text }}</span></label></article><BaseButton class="w-full" type="submit">Nộp bài và chấm điểm</BaseButton></form></div></main></DefaultLayout></template>
