import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { adminApi } from '../api/services';
import { getApiMessage } from '../api/client';
import { AppBar, Button, Card, Field, MetricCard, Screen, StateView, StatusBadge } from '../components/ui';
import type { AdminComment, AdminCourse, AdminDashboard, AdminReview, AdminUser, RootStackParamList } from '../types';
import { colors, shadow } from '../theme';

type Tab = 'overview' | 'users' | 'courses' | 'moderation';
export function AdminControlCenterScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'AdminControlCenter'>) {
  const [tab, setTab] = useState<Tab>('overview'); const [dashboard, setDashboard] = useState<AdminDashboard | null>(null);
  const [users, setUsers] = useState<AdminUser[]>([]); const [courses, setCourses] = useState<AdminCourse[]>([]); const [reviews, setReviews] = useState<AdminReview[]>([]); const [comments, setComments] = useState<AdminComment[]>([]);
  const [query, setQuery] = useState(''); const [moderation, setModeration] = useState<'reviews' | 'comments'>('reviews'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => {
    setLoading(true); try {
      if (tab === 'overview') setDashboard((await adminApi.dashboard()).data.data);
      if (tab === 'users') setUsers((await adminApi.users(query ? { search: query } : undefined)).data.data.items);
      if (tab === 'courses') setCourses((await adminApi.courses(query ? { search: query } : undefined)).data.data.items);
      if (tab === 'moderation' && moderation === 'reviews') setReviews((await adminApi.reviews(query)).data.data.items);
      if (tab === 'moderation' && moderation === 'comments') setComments((await adminApi.comments(query)).data.data.items);
      setError('');
    } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); }
  }, [moderation, query, tab]);
  useEffect(() => { const timer = setTimeout(() => void load(), query ? 350 : 0); return () => clearTimeout(timer); }, [load, query]);
  const updateUser = (item: AdminUser) => Alert.alert(item.status === 'ACTIVE' ? 'Khóa tài khoản?' : 'Mở khóa tài khoản?', item.email, [{ text: 'Hủy' }, { text: 'Xác nhận', style: item.status === 'ACTIVE' ? 'destructive' : 'default', onPress: async () => { try { await adminApi.updateUser(item.id, { status: item.status === 'ACTIVE' ? 'BLOCKED' : 'ACTIVE' }); await load(); } catch (e) { Alert.alert('Không thể cập nhật', getApiMessage(e)); } } }]);
  const updateCourse = (item: AdminCourse, status: AdminCourse['status']) => Alert.alert('Cập nhật khóa học?', `${item.title} → ${status}`, [{ text: 'Hủy' }, { text: 'Xác nhận', onPress: async () => { try { await adminApi.updateCourse(item.id, status); await load(); } catch (e) { Alert.alert('Không thể cập nhật', getApiMessage(e)); } } }]);
  const moderate = (kind: 'review' | 'comment', id: string) => Alert.alert('Ẩn nội dung này?', 'Thao tác kiểm duyệt không thể hoàn tác trên mobile.', [{ text: 'Hủy' }, { text: 'Ẩn', style: 'destructive', onPress: async () => { try { if (kind === 'review') await adminApi.removeReview(id); else await adminApi.removeComment(id); await load(); } catch (e) { Alert.alert('Không thể kiểm duyệt', getApiMessage(e)); } } }]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Trung tâm quản trị" subtitle="Thao tác nhanh và kiểm duyệt" onBack={navigation.goBack} />
    <View style={styles.tabs}><TabButton icon="speedometer-outline" active={tab === 'overview'} onPress={() => setTab('overview')} /><TabButton icon="people-outline" active={tab === 'users'} onPress={() => setTab('users')} /><TabButton icon="library-outline" active={tab === 'courses'} onPress={() => setTab('courses')} /><TabButton icon="shield-checkmark-outline" active={tab === 'moderation'} onPress={() => setTab('moderation')} /></View>
    {tab !== 'overview' && <Field label="Tìm kiếm" value={query} onChangeText={setQuery} placeholder="Nhập tên hoặc nội dung" returnKeyType="search" onSubmitEditing={load} />}
    {tab === 'overview' && <Overview data={dashboard} loading={loading} error={error} retry={load} />}
    {tab === 'users' && (loading || error || !users.length ? <StateView loading={loading} error={error} empty="Không có người dùng" onRetry={load} /> : users.map(item => <Card key={item.id}><View style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{item.fullName.charAt(0)}</Text></View><View style={{ flex: 1 }}><Text style={styles.title}>{item.fullName}</Text><Text style={styles.meta}>{item.email} · {item.role}</Text></View><StatusBadge label={item.status} tone={item.status === 'ACTIVE' ? 'success' : 'danger'} /></View><Button title={item.status === 'ACTIVE' ? 'Khóa tài khoản' : 'Mở khóa'} variant={item.status === 'ACTIVE' ? 'danger' : 'outline'} onPress={() => updateUser(item)} /></Card>))}
    {tab === 'courses' && (loading || error || !courses.length ? <StateView loading={loading} error={error} empty="Không có khóa học" onRetry={load} /> : courses.map(item => <Card key={item.id}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.instructor?.fullName} · {item._count?.enrollments || 0} học viên</Text></View><StatusBadge label={item.status} tone={item.status === 'PUBLISHED' ? 'success' : item.status === 'ARCHIVED' ? 'danger' : 'warning'} /></View><View style={styles.actions}>{item.status !== 'PUBLISHED' && <Button title="Xuất bản" variant="outline" onPress={() => updateCourse(item, 'PUBLISHED')} />}{item.status !== 'ARCHIVED' && <Button title="Lưu trữ" variant="ghost" onPress={() => updateCourse(item, 'ARCHIVED')} />}</View></Card>))}
    {tab === 'moderation' && <><View style={styles.switcher}><Pressable onPress={() => setModeration('reviews')} style={[styles.switchItem, moderation === 'reviews' && styles.switchActive]}><Text style={styles.switchText}>Đánh giá</Text></Pressable><Pressable onPress={() => setModeration('comments')} style={[styles.switchItem, moderation === 'comments' && styles.switchActive]}><Text style={styles.switchText}>Bình luận</Text></Pressable></View>{moderation === 'reviews' ? (loading || error || !reviews.length ? <StateView loading={loading} error={error} empty="Không có đánh giá" onRetry={load} /> : reviews.map(item => <ModerationCard key={item.id} title={`${'★'.repeat(item.rating)} · ${item.course.title}`} user={item.user.fullName} content={item.content} onRemove={() => moderate('review', item.id)} />)) : (loading || error || !comments.length ? <StateView loading={loading} error={error} empty="Không có bình luận" onRetry={load} /> : comments.map(item => <ModerationCard key={item.id} title={item.lesson.title} user={item.user.fullName} content={item.content} onRemove={() => moderate('comment', item.id)} />))}</>}
  </Screen>;
}
function Overview({ data, loading, error, retry }: { data: AdminDashboard | null; loading: boolean; error: string; retry(): void }) { if (!data) return <StateView loading={loading} error={error} onRetry={retry} />; return <><View style={styles.metrics}><MetricCard icon="people-outline" label="Người dùng" value={String(data.users.total)} /><MetricCard icon="library-outline" label="Khóa học" value={String(data.courses.total)} tone={colors.success} /></View><View style={styles.metrics}><MetricCard icon="school-outline" label="Ghi danh" value={String(data.learning.enrollments)} tone="#0ea5e9" /><MetricCard icon="cash-outline" label="Doanh thu" value={`${Math.round(data.commerce.revenue / 1000)}K`} tone={colors.warning} /></View><Card><Text style={styles.title}>Tình trạng nhanh</Text><Info label="Học viên" value={data.users.byRole.STUDENT || 0} /><Info label="Giảng viên" value={data.users.byRole.INSTRUCTOR || 0} /><Info label="Khóa học đã xuất bản" value={data.courses.byStatus.PUBLISHED || 0} /><Info label="Đánh giá / bình luận" value={`${data.learning.reviews} / ${data.learning.comments}`} /><Info label="Chứng chỉ" value={data.certificates} /></Card></>; }
function TabButton({ icon, active, onPress }: { icon: keyof typeof Ionicons.glyphMap; active: boolean; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.tab, active && styles.tabActive]}><Ionicons name={icon} size={23} color={active ? '#fff' : colors.muted} /></Pressable>; }
function Info({ label, value }: { label: string; value: string | number }) { return <View style={styles.info}><Text style={styles.meta}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
function ModerationCard({ title, user, content, onRemove }: { title: string; user: string; content: string | null; onRemove(): void }) { return <Card><Text style={styles.title}>{title}</Text><Text style={styles.meta}>Bởi {user}</Text><Text style={styles.content}>{content || '[Nội dung đã bị xóa]'}</Text><Button title="Ẩn nội dung" variant="danger" onPress={onRemove} /></Card>; }
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', gap: 8, marginVertical: 14 }, tab: { flex: 1, height: 50, borderRadius: 15, backgroundColor: '#ececf4', alignItems: 'center', justifyContent: 'center' }, tabActive: { backgroundColor: colors.primary, ...shadow }, metrics: { flexDirection: 'row', marginVertical: 6 }, row: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 12 }, avatar: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#eee9ff', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontWeight: '900', fontSize: 18 }, title: { color: colors.ink, fontWeight: '900', fontSize: 16 }, meta: { color: colors.muted, fontSize: 11, marginTop: 4 }, actions: { flexDirection: 'row', gap: 8 }, switcher: { flexDirection: 'row', backgroundColor: '#ececf4', borderRadius: 14, padding: 4, marginBottom: 14 }, switchItem: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 11 }, switchActive: { backgroundColor: '#fff', ...shadow }, switchText: { color: colors.primary, fontWeight: '900' }, info: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.border }, infoValue: { color: colors.ink, fontWeight: '900' }, content: { color: colors.ink, lineHeight: 22, marginVertical: 15 } });
