import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { analyticsApi } from '../api/services';
import { getApiMessage } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { AppBar, Card, MetricCard, Screen, SectionTitle, StateView } from '../components/ui';
import type { InstructorAnalyticsOverview, RootStackParamList, StudentAnalyticsOverview } from '../types';
import { colors } from '../theme';

type StudentProgress = { courseId: string; title: string; completedLessons: number; totalLessons: number; progressPercent: number; lastLearningAt: string | null };
type Performance = { courseId: string; title: string; enrollments: number; activeStudents: number; completionRate: number; averageQuizScore: number | null; averageRating: number | null; revenue: { amount: number; currency: string } };

export function AnalyticsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'Analytics'>) {
  const { user } = useAuth(); const instructor = user?.role === 'INSTRUCTOR' || user?.role === 'ADMIN';
  const [student, setStudent] = useState<StudentAnalyticsOverview | null>(null); const [instructorData, setInstructorData] = useState<InstructorAnalyticsOverview | null>(null);
  const [progress, setProgress] = useState<StudentProgress[]>([]); const [series, setSeries] = useState<Array<{ date: string; value: number }>>([]); const [performance, setPerformance] = useState<Performance[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { if (instructor) { const [overview, enrollment, courses] = await Promise.all([analyticsApi.instructorOverview(), analyticsApi.instructorEnrollments(), analyticsApi.coursePerformance()]); setInstructorData(overview.data.data); setSeries(enrollment.data.data.map(item => ({ date: item.date, value: item.count }))); setPerformance(courses.data.data); } else { const [overview, courseProgress, activity] = await Promise.all([analyticsApi.studentOverview(), analyticsApi.studentProgress(), analyticsApi.studentActivity()]); setStudent(overview.data.data); setProgress(courseProgress.data.data); setSeries(activity.data.data.map(item => ({ date: item.date, value: item.learningSeconds }))); } setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [instructor]);
  useEffect(() => { void load(); }, [load]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Phân tích học tập" subtitle="Dữ liệu 30 ngày gần nhất" onBack={navigation.goBack} />{loading || error ? <StateView loading={loading} error={error} onRetry={load} /> : instructor && instructorData ? <InstructorDashboard data={instructorData} series={series} performance={performance} /> : student ? <StudentDashboard data={student} series={series} progress={progress} /> : <StateView empty="Chưa có dữ liệu phân tích" />}</Screen>;
}

function StudentDashboard({ data, series, progress }: { data: StudentAnalyticsOverview; series: Array<{ date: string; value: number }>; progress: StudentProgress[] }) {
  return <><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.metrics}><MetricCard icon="library-outline" label="Khóa học đã đăng ký" value={String(data.enrolledCourses)} /><MetricCard icon="play-circle-outline" label="Đang học" value={String(data.inProgressCourses)} tone={colors.warning} /><MetricCard icon="checkmark-circle-outline" label="Đã hoàn thành" value={String(data.completedCourses)} tone={colors.success} /><MetricCard icon="flame-outline" label="Chuỗi học hiện tại" value={`${data.currentStreak || 0} ngày`} tone="#f97316" /><MetricCard icon="time-outline" label="Tổng thời gian học" value={duration(data.totalLearningSeconds)} tone="#0ea5e9" /></ScrollView><SectionTitle title="Hoạt động học tập" subtitle="Thời gian học mỗi ngày" /><MiniChart values={series} valueLabel={value => duration(value)} />
    <SectionTitle title="Tiến độ khóa học" subtitle="Tiếp tục từ nơi bạn đã dừng" />{progress.length ? progress.map(item => <Card key={item.courseId}><Text style={styles.courseTitle}>{item.title}</Text><View style={styles.progressInfo}><Text style={styles.note}>{item.completedLessons}/{item.totalLessons} bài</Text><Text style={styles.percent}>{Math.round(item.progressPercent)}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.min(100, item.progressPercent)}%` }]} /></View></Card>) : <Text style={styles.note}>Chưa có khóa học đang theo dõi.</Text>}
  </>;
}

function InstructorDashboard({ data, series, performance }: { data: InstructorAnalyticsOverview; series: Array<{ date: string; value: number }>; performance: Performance[] }) {
  return <><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.metrics}><MetricCard icon="people-outline" label="Học viên duy nhất" value={String(data.uniqueStudents)} /><MetricCard icon="person-add-outline" label="Đăng ký mới" value={String(data.newEnrollments)} tone="#0ea5e9" /><MetricCard icon="checkmark-done-outline" label="Tỷ lệ hoàn thành" value={`${data.completionRate.toFixed(1)}%`} tone={colors.success} /><MetricCard icon="star-outline" label="Đánh giá trung bình" value={data.averageRating?.toFixed(1) || '—'} tone={colors.warning} /><MetricCard icon="cash-outline" label="Doanh thu" value={money(data.revenue.amount)} tone="#0f9f6e" /></ScrollView><SectionTitle title="Lượt đăng ký" subtitle="Biểu đồ 30 ngày gần nhất" /><MiniChart values={series} valueLabel={String} /><SectionTitle title="Hiệu quả khóa học" subtitle="So sánh các khóa học của bạn" />{performance.map(item => <Card key={item.courseId}><View style={styles.courseRow}><View style={{ flex: 1 }}><Text style={styles.courseTitle}>{item.title}</Text><Text style={styles.note}>{item.enrollments} đăng ký · {item.activeStudents} đang hoạt động</Text></View><View style={styles.rate}><Text style={styles.rateValue}>{item.completionRate.toFixed(0)}%</Text><Text style={styles.rateLabel}>hoàn thành</Text></View></View><View style={styles.performanceRow}><SmallStat icon="star" value={item.averageRating?.toFixed(1) || '—'} /><SmallStat icon="help-circle" value={item.averageQuizScore?.toFixed(0) || '—'} /><SmallStat icon="cash" value={money(item.revenue.amount)} /></View></Card>)}</>;
}

function MiniChart({ values, valueLabel }: { values: Array<{ date: string; value: number }>; valueLabel(value: number): string }) {
  const recent = values.slice(-14); const max = Math.max(1, ...recent.map(item => item.value));
  return <Card><View style={styles.chart}>{recent.map(item => <View key={item.date} style={styles.barColumn}><Text style={styles.barValue}>{item.value ? valueLabel(item.value) : ''}</Text><View style={[styles.bar, { height: Math.max(4, item.value / max * 105) }]} /><Text style={styles.barDate}>{item.date.slice(5)}</Text></View>)}</View></Card>;
}
function SmallStat({ icon, value }: { icon: keyof typeof Ionicons.glyphMap; value: string }) { return <View style={styles.smallStat}><Ionicons name={icon} size={15} color={colors.primary} /><Text style={styles.smallValue}>{value}</Text></View>; }
const duration = (seconds: number) => seconds < 3600 ? `${Math.round(seconds / 60)} phút` : `${(seconds / 3600).toFixed(1)} giờ`;
const money = (value: number) => `${new Intl.NumberFormat('vi-VN', { notation: value >= 1000000 ? 'compact' : 'standard' }).format(value)} ₫`;
const styles = StyleSheet.create({ metrics: { marginVertical: 16 }, chart: { height: 150, flexDirection: 'row', alignItems: 'flex-end', gap: 4 }, barColumn: { flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end' }, bar: { width: '70%', minWidth: 5, borderRadius: 5, backgroundColor: colors.primary }, barValue: { color: colors.muted, fontSize: 7, height: 19 }, barDate: { color: colors.muted, fontSize: 7, marginTop: 5, transform: [{ rotate: '-45deg' }] }, courseTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, note: { color: colors.muted, fontSize: 12, marginTop: 5 }, progressInfo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 }, percent: { color: colors.primary, fontWeight: '900' }, track: { height: 8, borderRadius: 5, backgroundColor: '#ebe8f7', overflow: 'hidden', marginTop: 8 }, fill: { height: 8, borderRadius: 5, backgroundColor: colors.primary }, courseRow: { flexDirection: 'row', gap: 10 }, rate: { alignItems: 'flex-end' }, rateValue: { color: colors.success, fontSize: 20, fontWeight: '900' }, rateLabel: { color: colors.muted, fontSize: 9 }, performanceRow: { flexDirection: 'row', gap: 8, marginTop: 15 }, smallStat: { flex: 1, minHeight: 42, borderRadius: 12, backgroundColor: '#f6f4fb', flexDirection: 'row', gap: 5, alignItems: 'center', justifyContent: 'center' }, smallValue: { color: colors.ink, fontSize: 11, fontWeight: '800' } });
