import { useCallback, useEffect, useState } from 'react';
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { assignmentsApi } from '../api/services';
import { getApiMessage } from '../api/client';
import { AppBar, BottomSheet, Button, Card, Field, MetricCard, Screen, SectionTitle, StateView } from '../components/ui';
import type { Assignment, AssignmentSubmission, RootStackParamList } from '../types';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { colors } from '../theme';

const formatDate = (value: string) => new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export function AssignmentsScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'Assignments'>) {
  const [items, setItems] = useState<Assignment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await assignmentsApi.list(route.params.courseId)).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [route.params.courseId]);
  useEffect(() => { void load(); }, [load]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Bài tập" subtitle={route.params.courseTitle} onBack={navigation.goBack} />
    {loading || error || !items.length ? <StateView loading={loading} error={error} empty="Khóa học chưa có bài tập" onRetry={load} /> : items.map(item => <AssignmentCard key={item.id} item={item} onPress={() => navigation.navigate('AssignmentDetail', { assignmentId: item.id, courseId: route.params.courseId })} />)}
  </Screen>;
}

export function AssignmentDetailScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'AssignmentDetail'>) {
  const [item, setItem] = useState<Assignment | null>(null); const [grade, setGrade] = useState<any>(null); const [text, setText] = useState(''); const [files, setFiles] = useState<Array<{ uri: string; name: string; mimeType?: string | null }>>([]);
  const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [assignment, gradeResult] = await Promise.all([assignmentsApi.get(route.params.assignmentId), assignmentsApi.myGrade(route.params.courseId)]); setItem(assignment.data.data); setGrade(gradeResult.data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [route.params.assignmentId, route.params.courseId]);
  useEffect(() => { void load(); }, [load]);
  const pickFiles = async () => { const result = await DocumentPicker.getDocumentAsync({ multiple: true, copyToCacheDirectory: true }); if (!result.canceled) setFiles(result.assets.slice(0, 5).map(file => ({ uri: file.uri, name: file.name, mimeType: file.mimeType }))); };
  const submit = async () => { if (!text.trim() && !files.length) return Alert.alert('Thiếu nội dung', 'Nhập nội dung hoặc chọn ít nhất một file.'); setSending(true); try { await assignmentsApi.submit(route.params.assignmentId, text, files); setText(''); setFiles([]); await load(); Alert.alert('Đã nộp bài', 'Bài nộp mới đã được ghi nhận.'); } catch (e) { Alert.alert('Không thể nộp bài', getApiMessage(e)); } finally { setSending(false); } };
  if (loading || error || !item) return <Screen><AppBar title="Chi tiết bài tập" onBack={navigation.goBack} /><StateView loading={loading} error={error} onRetry={load} /></Screen>;
  const attempts = item.submissions || [];
  return <Screen><AppBar title="Chi tiết bài tập" subtitle={item.title} onBack={navigation.goBack} />
    <Card><Text style={styles.eyebrow}>{new Date(item.dueAt) < new Date() ? 'ĐÃ HẾT HẠN' : 'ĐANG MỞ'}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.description}>{item.description || 'Không có mô tả.'}</Text><Info icon="calendar-outline" label="Hạn nộp" value={formatDate(item.dueAt)} /><Info icon="trophy-outline" label="Điểm tối đa" value={`${item.maxScore} điểm`} /><Info icon="repeat-outline" label="Số lần nộp" value={`${attempts.length}/${item.maxSubmissions}`} />{!!item.instructions && <View style={styles.instructions}><Text style={styles.instructionsTitle}>Hướng dẫn</Text><Text style={styles.description}>{item.instructions}</Text></View>}</Card>
    {grade && <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: 10 }}><MetricCard icon="document-text-outline" label="Điểm bài tập" value={`${Number(grade.assignment?.percent || 0).toFixed(1)}%`} /><MetricCard icon="help-circle-outline" label="Điểm quiz" value={`${Number(grade.quiz?.percent || 0).toFixed(1)}%`} tone={colors.warning} /><MetricCard icon="ribbon-outline" label="Điểm tổng kết" value={`${Number(grade.finalScore || 0).toFixed(1)}%`} tone={grade.passed ? colors.success : colors.danger} /></ScrollView>}
    <SectionTitle title="Nộp bài" subtitle="Có thể nhập văn bản, tải file hoặc cả hai" /><Field label="Nội dung bài làm" value={text} onChangeText={setText} multiline placeholder="Nhập nội dung bài làm..." /><Button title={files.length ? `Đã chọn ${files.length} file · Chọn lại` : 'Chọn file đính kèm'} variant="outline" onPress={pickFiles} />{files.map(file => <View key={file.uri} style={styles.file}><Ionicons name="document-attach-outline" size={20} color={colors.primary} /><Text numberOfLines={1} style={styles.fileName}>{file.name}</Text></View>)}<Button title={attempts.length ? 'Nộp lại bài' : 'Nộp bài'} onPress={submit} loading={sending} />
    <SectionTitle title="Lịch sử bài nộp" subtitle={`${attempts.length} lần nộp`} />{attempts.length ? attempts.map(attempt => <SubmissionCard key={attempt.id} item={attempt} onPress={() => navigation.navigate('SubmissionDetail', { submissionId: attempt.id, maxScore: item.maxScore })} />) : <Text style={styles.muted}>Bạn chưa nộp bài.</Text>}
  </Screen>;
}

export function AssignmentManagerScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'AssignmentManager'>) {
  const [items, setItems] = useState<Assignment[]>([]); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await assignmentsApi.list(route.params.courseId)).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [route.params.courseId]);
  useEffect(() => { void load(); }, [load]);
  const remove = (item: Assignment) => Alert.alert('Xóa bài tập?', item.title, [{ text: 'Hủy' }, { text: 'Xóa', style: 'destructive', onPress: async () => { try { await assignmentsApi.remove(item.id); await load(); } catch (e) { Alert.alert('Không thể xóa', getApiMessage(e)); } } }]);
  return <View style={{ flex: 1 }}><Screen refreshing={loading} onRefresh={load}><AppBar title="Quản lý bài tập" subtitle={route.params.courseTitle} onBack={navigation.goBack} onMore={() => setFormOpen(true)} /><Button title="＋ Tạo bài tập" onPress={() => setFormOpen(true)} />{loading || error || !items.length ? <StateView loading={loading} error={error} empty="Chưa có bài tập" onRetry={load} /> : items.map(item => <Card key={item.id}><Pressable onPress={() => navigation.navigate('AssignmentSubmissions', { assignmentId: item.id, assignmentTitle: item.title, maxScore: item.maxScore })}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.muted}>{formatDate(item.dueAt)} · {item._count?.submissions || 0} bài nộp</Text></View><Status active={item.isPublished} /></View></Pressable><View style={styles.actions}><Button title="Bài nộp" variant="outline" onPress={() => navigation.navigate('AssignmentSubmissions', { assignmentId: item.id, assignmentTitle: item.title, maxScore: item.maxScore })} /><Button title="Xóa" variant="ghost" onPress={() => remove(item)} /></View></Card>)}</Screen><BottomSheet visible={formOpen} title="Tạo bài tập mới" onClose={() => setFormOpen(false)}><AssignmentForm courseId={route.params.courseId} onDone={async () => { setFormOpen(false); await load(); }} /></BottomSheet></View>;
}

function AssignmentForm({ courseId, onDone }: { courseId: string; onDone(): void }) {
  const defaultDate = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 16);
  const [form, setForm] = useState({ title: '', description: '', instructions: '', dueAt: defaultDate, maxScore: '100', allowResubmission: true, maxSubmissions: '3', allowLateSubmissions: false, isPublished: true }); const [saving, setSaving] = useState(false);
  const set = (key: keyof typeof form) => (value: string | boolean) => setForm(old => ({ ...old, [key]: value }));
  const save = async () => { const due = new Date(form.dueAt); if (!form.title.trim() || Number.isNaN(due.getTime())) return Alert.alert('Dữ liệu chưa hợp lệ', 'Nhập tiêu đề và hạn nộp dạng ISO, ví dụ 2026-08-30T23:59.'); setSaving(true); try { await assignmentsApi.create(courseId, { title: form.title.trim(), description: form.description.trim() || null, instructions: form.instructions.trim() || null, dueAt: due.toISOString(), maxScore: Number(form.maxScore), allowResubmission: form.allowResubmission, maxSubmissions: form.allowResubmission ? Number(form.maxSubmissions) : 1, allowLateSubmissions: form.allowLateSubmissions, isPublished: form.isPublished }); onDone(); } catch (e) { Alert.alert('Không thể tạo bài tập', getApiMessage(e)); } finally { setSaving(false); } };
  return <ScrollView style={{ maxHeight: 580 }} keyboardShouldPersistTaps="handled"><Field label="Tiêu đề" value={form.title} onChangeText={set('title')} /><Field label="Mô tả" value={form.description} onChangeText={set('description')} multiline /><Field label="Hướng dẫn" value={form.instructions} onChangeText={set('instructions')} multiline /><Field label="Hạn nộp (ISO)" value={form.dueAt} onChangeText={set('dueAt')} /><Field label="Điểm tối đa" value={form.maxScore} onChangeText={set('maxScore')} keyboardType="decimal-pad" />{form.allowResubmission && <Field label="Số lần nộp tối đa" value={form.maxSubmissions} onChangeText={set('maxSubmissions')} keyboardType="number-pad" />}<Toggle label="Cho phép nộp lại" value={form.allowResubmission} onChange={set('allowResubmission')} /><Toggle label="Cho phép nộp trễ" value={form.allowLateSubmissions} onChange={set('allowLateSubmissions')} /><Toggle label="Công bố ngay" value={form.isPublished} onChange={set('isPublished')} /><Button title="Tạo bài tập" onPress={save} loading={saving} /></ScrollView>;
}

export function AssignmentSubmissionsScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'AssignmentSubmissions'>) {
  const [items, setItems] = useState<AssignmentSubmission[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await assignmentsApi.submissions(route.params.assignmentId)).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [route.params.assignmentId]); useEffect(() => { void load(); }, [load]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Danh sách bài nộp" subtitle={route.params.assignmentTitle} onBack={navigation.goBack} />{loading || error || !items.length ? <StateView loading={loading} error={error} empty="Chưa có học viên nộp bài" onRetry={load} /> : items.map(item => <SubmissionCard key={item.id} item={item} onPress={() => navigation.navigate('SubmissionDetail', { submissionId: item.id, maxScore: route.params.maxScore })} />)}</Screen>;
}

export function SubmissionDetailScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'SubmissionDetail'>) {
  const [item, setItem] = useState<AssignmentSubmission | null>(null); const [score, setScore] = useState(''); const [comment, setComment] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const result = (await assignmentsApi.submission(route.params.submissionId)).data.data; setItem(result); setScore(result.feedback ? String(result.feedback.score) : ''); setComment(result.feedback?.comment || ''); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [route.params.submissionId]); useEffect(() => { void load(); }, [load]);
  const grade = async () => { const value = Number(score); if (!Number.isFinite(value) || value < 0 || value > route.params.maxScore) return Alert.alert('Điểm không hợp lệ', `Điểm phải từ 0 đến ${route.params.maxScore}.`); setSaving(true); try { await assignmentsApi.grade(route.params.submissionId, { score: value, comment: comment.trim() || null }); await load(); Alert.alert('Đã lưu điểm'); } catch (e) { Alert.alert('Không thể chấm điểm', getApiMessage(e)); } finally { setSaving(false); } };
  if (loading || error || !item) return <Screen><AppBar title="Bài nộp" onBack={navigation.goBack} /><StateView loading={loading} error={error} onRetry={load} /></Screen>;
  return <Screen><AppBar title="Chấm bài" subtitle={item.student?.fullName || `Lần ${item.attemptNumber}`} onBack={navigation.goBack} /><Card><Text style={styles.cardTitle}>{item.student?.fullName || 'Bài nộp của bạn'}</Text><Text style={styles.muted}>Lần {item.attemptNumber} · {formatDate(item.submittedAt)}</Text>{item.isLate && <Text style={styles.late}>Nộp trễ</Text>}<Text style={styles.submissionText}>{item.textContent || 'Không có nội dung văn bản.'}</Text>{item.files.map(file => <Pressable key={file.id} style={styles.file} onPress={() => void Linking.openURL(file.fileUrl)}><Ionicons name="download-outline" size={20} color={colors.primary} /><Text style={styles.fileName}>{file.originalName}</Text></Pressable>)}</Card><SectionTitle title="Điểm và nhận xét" /><Field label={`Điểm (tối đa ${route.params.maxScore})`} value={score} onChangeText={setScore} keyboardType="decimal-pad" /><Field label="Nhận xét" value={comment} onChangeText={setComment} multiline placeholder="Nhận xét chi tiết cho học viên..." /><Button title={item.feedback ? 'Cập nhật điểm' : 'Lưu điểm'} onPress={grade} loading={saving} /></Screen>;
}

function AssignmentCard({ item, onPress }: { item: Assignment; onPress(): void }) { return <Pressable onPress={onPress} style={styles.assignment}><View style={styles.assignmentIcon}><Ionicons name="document-text-outline" size={25} color={colors.primary} /></View><View style={{ flex: 1 }}><View style={styles.row}><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><Ionicons name="chevron-forward" size={20} color={colors.muted} /></View><Text style={styles.muted}>Hạn: {formatDate(item.dueAt)}</Text><Text style={styles.score}>{item.maxScore} điểm · tối đa {item.maxSubmissions} lần nộp</Text></View></Pressable>; }
function SubmissionCard({ item, onPress }: { item: AssignmentSubmission; onPress(): void }) { return <Pressable onPress={onPress} style={styles.assignment}><View style={[styles.assignmentIcon, { backgroundColor: item.feedback ? '#dcfce7' : '#fff4d6' }]}><Ionicons name={item.feedback ? 'checkmark-circle-outline' : 'time-outline'} size={25} color={item.feedback ? colors.success : colors.warning} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.student?.fullName || `Lần nộp ${item.attemptNumber}`}</Text><Text style={styles.muted}>{formatDate(item.submittedAt)}</Text><Text style={[styles.score, item.feedback && { color: colors.success }]}>{item.feedback ? `${item.feedback.score} điểm` : 'Đang chờ chấm'}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable>; }
function Info({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.info}><Ionicons name={icon} size={20} color={colors.primary} /><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange(value: boolean): void }) { return <View style={styles.toggle}><Text style={styles.cardTitle}>{label}</Text><Switch value={value} onValueChange={onChange} /></View>; }
function Status({ active }: { active: boolean }) { return <View style={[styles.status, { backgroundColor: active ? '#dcfce7' : '#f1f2f4' }]}><Text style={{ color: active ? colors.success : colors.muted, fontSize: 10, fontWeight: '900' }}>{active ? 'ĐÃ CÔNG BỐ' : 'BẢN NHÁP'}</Text></View>; }

const styles = StyleSheet.create({
  assignment: { minHeight: 104, backgroundColor: '#fff', borderRadius: 19, padding: 15, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, assignmentIcon: { width: 48, height: 48, borderRadius: 15, backgroundColor: '#eee9ff', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '900' }, title: { color: colors.ink, fontSize: 25, lineHeight: 32, fontWeight: '900', marginTop: 6 }, description: { color: colors.muted, lineHeight: 22, marginTop: 8 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, cardTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', flexShrink: 1 }, muted: { color: colors.muted, fontSize: 12, marginTop: 4 }, score: { color: colors.primary, fontSize: 12, fontWeight: '800', marginTop: 6 }, info: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 13 }, infoLabel: { color: colors.muted, flex: 1 }, infoValue: { color: colors.ink, fontWeight: '800' }, instructions: { backgroundColor: '#f7f5ff', borderRadius: 14, padding: 13, marginTop: 16 }, instructionsTitle: { color: colors.ink, fontWeight: '900' }, file: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 12, backgroundColor: '#f7f5ff', paddingHorizontal: 12, marginBottom: 7 }, fileName: { flex: 1, color: colors.primary, fontWeight: '700' }, actions: { flexDirection: 'row', gap: 8, marginTop: 12 }, toggle: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, status: { borderRadius: 20, paddingHorizontal: 9, paddingVertical: 6 }, late: { color: colors.warning, fontWeight: '900', fontSize: 11, marginTop: 8 }, submissionText: { color: colors.ink, lineHeight: 23, marginVertical: 18 },
});
