import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { couponsApi, payoutsApi, refundsApi, revenueApi } from '../api/services';
import { getApiMessage } from '../api/client';
import { AppBar, BottomSheet, Button, Card, Field, MetricCard, Screen, SectionTitle, StateView } from '../components/ui';
import type { Coupon, Payout, RefundRequest, RevenueOverview, RootStackParamList } from '../types';
import { colors } from '../theme';

const money = (value: number, currency = 'VND') => `${new Intl.NumberFormat('vi-VN').format(value)} ${currency === 'VND' ? '₫' : currency}`;
const date = (value: string | null) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';

export function RefundsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'Refunds'>) {
  const [items, setItems] = useState<RefundRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await refundsApi.mine()).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const cancel = (item: RefundRequest) => Alert.alert('Hủy yêu cầu hoàn tiền?', 'Bạn có thể tạo yêu cầu mới nếu vẫn còn trong thời hạn.', [{ text: 'Giữ yêu cầu' }, { text: 'Hủy yêu cầu', style: 'destructive', onPress: async () => { try { await refundsApi.cancel(item.id); await load(); } catch (e) { Alert.alert('Không thể hủy', getApiMessage(e)); } } }]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Yêu cầu hoàn tiền" subtitle="Theo dõi các yêu cầu của bạn" onBack={navigation.goBack} />{loading || error || !items.length ? <StateView loading={loading} error={error} empty="Bạn chưa có yêu cầu hoàn tiền" onRetry={load} /> : items.map(item => <RefundCard key={item.id} item={item}>{item.status === 'PENDING' && <Button title="Hủy yêu cầu" variant="ghost" onPress={() => cancel(item)} />}</RefundCard>)}</Screen>;
}

export function AdminRefundsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'AdminRefunds'>) {
  const [items, setItems] = useState<RefundRequest[]>([]); const [selected, setSelected] = useState<RefundRequest | null>(null); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await refundsApi.adminList()).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const review = async (approve: boolean) => { if (!selected || note.trim().length < 3) return Alert.alert('Thiếu ghi chú', 'Ghi chú quản trị cần ít nhất 3 ký tự.'); setSaving(true); try { if (approve) await refundsApi.approve(selected.id, note.trim()); else await refundsApi.reject(selected.id, note.trim()); setSelected(null); setNote(''); await load(); } catch (e) { Alert.alert('Không thể xử lý', getApiMessage(e)); } finally { setSaving(false); } };
  return <View style={{ flex: 1 }}><Screen refreshing={loading} onRefresh={load}><AppBar title="Duyệt hoàn tiền" subtitle="Kiểm tra chính sách trước khi xử lý" onBack={navigation.goBack} />{loading || error || !items.length ? <StateView loading={loading} error={error} empty="Không có yêu cầu hoàn tiền" onRetry={load} /> : items.map(item => <RefundCard key={item.id} item={item}>{item.status === 'PENDING' && <Button title="Xem và xử lý" onPress={() => { setSelected(item); setNote(''); }} />}</RefundCard>)}</Screen><BottomSheet visible={!!selected} title="Xử lý hoàn tiền" onClose={() => setSelected(null)}>{selected && <><Text style={styles.sheetSummary}>{selected.user?.fullName || 'Học viên'} · {money(selected.requestedAmount)}</Text><Text style={styles.reason}>{selected.reason}</Text><Field label="Ghi chú quản trị" value={note} onChangeText={setNote} multiline placeholder="Lý do duyệt hoặc từ chối..." /><Button title="Duyệt và hoàn tiền" onPress={() => void review(true)} loading={saving} /><Button title="Từ chối yêu cầu" variant="danger" onPress={() => void review(false)} loading={saving} /></>}</BottomSheet></View>;
}

export function AdminCouponsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'AdminCoupons'>) {
  const [items, setItems] = useState<Coupon[]>([]); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setItems((await couponsApi.list()).data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const toggle = async (item: Coupon) => { try { await couponsApi.setStatus(item.id, !item.isActive); await load(); } catch (e) { Alert.alert('Không thể cập nhật', getApiMessage(e)); } };
  return <View style={{ flex: 1 }}><Screen refreshing={loading} onRefresh={load}><AppBar title="Mã giảm giá" subtitle="Quản lý coupon toàn hệ thống" onBack={navigation.goBack} onMore={() => setFormOpen(true)} /><Button title="＋ Tạo coupon" onPress={() => setFormOpen(true)} />{loading || error || !items.length ? <StateView loading={loading} error={error} empty="Chưa có coupon" onRetry={load} /> : items.map(item => <Card key={item.id}><View style={styles.couponTop}><View style={styles.ticket}><Ionicons name="ticket-outline" size={24} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.code}>{item.code}</Text><Text style={styles.couponName}>{item.name}</Text></View><Switch value={item.isActive} onValueChange={() => void toggle(item)} /></View><View style={styles.couponDetails}><Text style={styles.discount}>{item.discountType === 'PERCENTAGE' ? `${item.discountValue}%` : money(item.discountValue)}</Text><Text style={styles.meta}>{item.redeemedCount}/{item.maxRedemptions || '∞'} lượt · hết hạn {date(item.expiresAt)}</Text></View></Card>)}</Screen><BottomSheet visible={formOpen} title="Tạo coupon mới" onClose={() => setFormOpen(false)}><CouponForm onDone={async () => { setFormOpen(false); await load(); }} /></BottomSheet></View>;
}

function CouponForm({ onDone }: { onDone(): void }) {
  const [form, setForm] = useState(() => { const start = new Date(); const end = new Date(Date.now() + 30 * 86400000); return { code: '', name: '', description: '', discountType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED_AMOUNT', discountValue: '20', maxDiscountAmount: '100000', minOrderAmount: '0', startsAt: start.toISOString().slice(0, 16), expiresAt: end.toISOString().slice(0, 16), maxRedemptions: '100', isActive: true }; }); const [saving, setSaving] = useState(false);
  const set = (key: keyof typeof form) => (value: string | boolean) => setForm(old => ({ ...old, [key]: value }));
  const save = async () => { setSaving(true); try { await couponsApi.create({ code: form.code.trim().toUpperCase(), name: form.name.trim(), description: form.description.trim() || null, discountType: form.discountType, discountValue: Number(form.discountValue), maxDiscountAmount: form.discountType === 'PERCENTAGE' && Number(form.maxDiscountAmount) ? Number(form.maxDiscountAmount) : null, minOrderAmount: Number(form.minOrderAmount) || null, startsAt: new Date(form.startsAt).toISOString(), expiresAt: new Date(form.expiresAt).toISOString(), maxRedemptions: Number(form.maxRedemptions) || null, appliesToAllCourses: true, courseIds: [], isActive: form.isActive }); onDone(); } catch (e) { Alert.alert('Không thể tạo coupon', getApiMessage(e)); } finally { setSaving(false); } };
  return <ScrollView keyboardShouldPersistTaps="handled" style={{ maxHeight: 580 }}><Field label="Mã coupon" value={form.code} onChangeText={set('code')} autoCapitalize="characters" placeholder="WELCOME20" /><Field label="Tên chương trình" value={form.name} onChangeText={set('name')} /><Field label="Mô tả" value={form.description} onChangeText={set('description')} multiline /><View style={styles.typeRow}><Pressable style={[styles.type, form.discountType === 'PERCENTAGE' && styles.typeActive]} onPress={() => setForm(old => ({ ...old, discountType: 'PERCENTAGE' }))}><Text style={form.discountType === 'PERCENTAGE' ? styles.typeTextActive : styles.typeText}>Theo phần trăm</Text></Pressable><Pressable style={[styles.type, form.discountType === 'FIXED_AMOUNT' && styles.typeActive]} onPress={() => setForm(old => ({ ...old, discountType: 'FIXED_AMOUNT' }))}><Text style={form.discountType === 'FIXED_AMOUNT' ? styles.typeTextActive : styles.typeText}>Số tiền cố định</Text></Pressable></View><Field label={form.discountType === 'PERCENTAGE' ? 'Phần trăm giảm' : 'Số tiền giảm'} value={form.discountValue} onChangeText={set('discountValue')} keyboardType="number-pad" />{form.discountType === 'PERCENTAGE' && <Field label="Giảm tối đa" value={form.maxDiscountAmount} onChangeText={set('maxDiscountAmount')} keyboardType="number-pad" />}<Field label="Đơn tối thiểu" value={form.minOrderAmount} onChangeText={set('minOrderAmount')} keyboardType="number-pad" /><Field label="Bắt đầu (ISO)" value={form.startsAt} onChangeText={set('startsAt')} /><Field label="Hết hạn (ISO)" value={form.expiresAt} onChangeText={set('expiresAt')} /><Field label="Số lượt tối đa" value={form.maxRedemptions} onChangeText={set('maxRedemptions')} keyboardType="number-pad" /><Button title="Tạo coupon" onPress={save} loading={saving} disabled={!form.code.trim() || !form.name.trim()} /></ScrollView>;
}

export function RevenueScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'Revenue'>) {
  const [overview, setOverview] = useState<RevenueOverview | null>(null); const [earnings, setEarnings] = useState<any[]>([]); const [payouts, setPayouts] = useState<Payout[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [summary, earningResult, payoutResult] = await Promise.all([revenueApi.overview(), revenueApi.earnings(), revenueApi.payouts()]); setOverview(summary.data.data); setEarnings(earningResult.data.data); setPayouts(payoutResult.data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Doanh thu" subtitle="Số liệu thu nhập thực nhận" onBack={navigation.goBack} />{loading || error || !overview ? <StateView loading={loading} error={error} onRetry={load} /> : <><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginVertical: 16 }}><MetricCard icon="wallet-outline" label="Số dư khả dụng" value={money(overview.availableBalance)} tone={colors.success} /><MetricCard icon="time-outline" label="Đang chờ" value={money(overview.pendingBalance)} tone={colors.warning} /><MetricCard icon="cash-outline" label="Doanh thu gộp" value={money(overview.grossRevenue)} /><MetricCard icon="card-outline" label="Đã thanh toán" value={money(overview.paidAmount)} tone="#0ea5e9" /></ScrollView><SectionTitle title="Khoản thu gần đây" />{earnings.slice(0, 10).map(item => <Card key={item.id}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.course?.title || 'Doanh thu khóa học'}</Text><Text style={styles.meta}>{date(item.createdAt)} · {earningLabel[item.status] || item.status}</Text></View><Text style={styles.net}>+{money(item.netAmount)}</Text></View><Text style={styles.fee}>Gộp {money(item.grossAmount)} · phí nền tảng {money(item.platformFeeAmount)}</Text></Card>)}<SectionTitle title="Lịch sử payout" />{payouts.length ? payouts.map(item => <PayoutCard key={item.id} item={item} />) : <Text style={styles.meta}>Chưa có payout.</Text>}</>}</Screen>;
}

export function AdminPayoutsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'AdminPayouts'>) {
  const [balances, setBalances] = useState<Array<{ instructor?: { id: string; fullName: string; email: string }; availableAmount: number; earningCount: number; currency: string }>>([]); const [payouts, setPayouts] = useState<Payout[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [balanceResult, payoutResult] = await Promise.all([payoutsApi.balances(), payoutsApi.list()]); setBalances(balanceResult.data.data); setPayouts(payoutResult.data.data); setError(''); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const create = async (instructorId: string) => { try { await payoutsApi.create(instructorId); await load(); } catch (e) { Alert.alert('Không thể tạo payout', getApiMessage(e)); } };
  const process = async (item: Payout) => { try { await payoutsApi.process(item.id, true); await load(); } catch (e) { Alert.alert('Không thể xử lý payout', getApiMessage(e)); } };
  return <Screen refreshing={loading} onRefresh={load}><AppBar title="Payout giảng viên" subtitle="Sandbox — không chuyển tiền thật" onBack={navigation.goBack} />{loading || error ? <StateView loading={loading} error={error} onRetry={load} /> : <><SectionTitle title="Số dư khả dụng" />{balances.length ? balances.map(item => <Card key={item.instructor?.id || item.currency}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.instructor?.fullName || 'Giảng viên'}</Text><Text style={styles.meta}>{item.instructor?.email} · {item.earningCount} khoản thu</Text></View><Text style={styles.net}>{money(item.availableAmount, item.currency)}</Text></View><Button title="Tạo payout" onPress={() => item.instructor && void create(item.instructor.id)} disabled={!item.availableAmount || !item.instructor} /></Card>) : <Text style={styles.meta}>Không có số dư khả dụng.</Text>}<SectionTitle title="Lịch sử payout" />{payouts.map(item => <PayoutCard key={item.id} item={item}>{(item.status === 'PENDING' || item.status === 'FAILED') && <Button title={item.status === 'FAILED' ? 'Thử xử lý lại' : 'Xử lý sandbox'} onPress={() => void process(item)} />}</PayoutCard>)}</>}</Screen>;
}

function RefundCard({ item, children }: { item: RefundRequest; children?: React.ReactNode }) { return <Card><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.order?.orderNumber || 'Yêu cầu hoàn tiền'}</Text><Text style={styles.meta}>{date(item.createdAt)}</Text></View><StatusBadge status={item.status} /></View><Text style={styles.refundAmount}>{money(item.requestedAmount, item.order?.currency)}</Text><Text style={styles.reason}>{item.reason}</Text>{item.adminNote && <Text style={styles.adminNote}>Phản hồi: {item.adminNote}</Text>}{children}</Card>; }
function PayoutCard({ item, children }: { item: Payout; children?: React.ReactNode }) { return <Card><View style={styles.row}><View><Text style={styles.cardTitle}>{money(item.amount, item.currency)}</Text><Text style={styles.meta}>{date(item.createdAt)}</Text></View><StatusBadge status={item.status} /></View>{item.failureReason && <Text style={styles.adminNote}>{item.failureReason}</Text>}{children}</Card>; }
function StatusBadge({ status }: { status: string }) { const tone = ['APPROVED', 'PAID'].includes(status) ? colors.success : ['REJECTED', 'FAILED'].includes(status) ? colors.danger : status === 'PENDING' ? colors.warning : colors.primary; return <View style={[styles.badge, { backgroundColor: `${tone}18` }]}><Text style={{ color: tone, fontSize: 10, fontWeight: '900' }}>{status}</Text></View>; }
const earningLabel: Record<string, string> = { PENDING: 'Đang chờ', AVAILABLE: 'Khả dụng', PAID: 'Đã thanh toán', REVERSED: 'Đã hoàn lại' };
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, cardTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, meta: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 }, badge: { borderRadius: 20, paddingHorizontal: 9, paddingVertical: 6 }, refundAmount: { color: colors.primary, fontSize: 22, fontWeight: '900', marginTop: 15 }, reason: { color: colors.ink, lineHeight: 22, marginTop: 10 }, adminNote: { color: colors.muted, fontStyle: 'italic', backgroundColor: '#f6f4fb', borderRadius: 11, padding: 11, marginTop: 12 }, sheetSummary: { color: colors.primary, fontSize: 18, fontWeight: '900' }, couponTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, ticket: { width: 48, height: 48, borderRadius: 15, backgroundColor: '#eee9ff', alignItems: 'center', justifyContent: 'center' }, code: { color: colors.primary, fontSize: 18, fontWeight: '900', letterSpacing: 1 }, couponName: { color: colors.muted, fontSize: 12, marginTop: 3 }, couponDetails: { marginTop: 14, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 8 }, discount: { color: colors.ink, fontSize: 24, fontWeight: '900' }, typeRow: { flexDirection: 'row', gap: 8, marginBottom: 14 }, type: { flex: 1, minHeight: 46, borderRadius: 13, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, typeActive: { backgroundColor: colors.primary, borderColor: colors.primary }, typeText: { color: colors.muted, fontWeight: '800', fontSize: 12 }, typeTextActive: { color: '#fff', fontWeight: '800', fontSize: 12 }, net: { color: colors.success, fontSize: 17, fontWeight: '900' }, fee: { color: colors.muted, fontSize: 11, marginTop: 12 } });
