import { useCallback, useEffect, useRef, useState } from 'react';
import { FlatList, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { getApiMessage } from '../api/client';
import { messagesApi } from '../api/services';
import { useAuth } from '../auth/AuthContext';
import { AppBar, Card, Screen } from '../components/ui';
import { useMessages } from '../messages/MessageContext';
import type { DirectMessage, MessageContact, RootStackParamList } from '../types';
import { colors } from '../theme';

function Avatar({ contact, size = 48 }: { contact: MessageContact; size?: number }) {
  return contact.avatarUrl ? <Image source={{ uri: contact.avatarUrl }} style={{ width: size, height: size, borderRadius: size / 3 }} /> : <View style={[styles.avatar, { width: size, height: size, borderRadius: size / 3 }]}><Text style={styles.avatarText}>{contact.fullName.charAt(0).toUpperCase()}</Text></View>;
}
function EmptyState({ title, message }: { title: string; message: string }) { return <View style={styles.empty}><Ionicons name="chatbubbles-outline" size={39} color={colors.primary} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyMessage}>{message}</Text></View>; }

export function MessagesScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'Messages'>) {
  const { conversations, refreshConversations } = useMessages(); const [contacts, setContacts] = useState<MessageContact[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const loadContacts = useCallback(async (value = search) => { setLoading(true); setError(''); try { setContacts((await messagesApi.contacts(value)).data.data); } catch (e) { setError(getApiMessage(e)); } finally { setLoading(false); } }, [search]);
  useFocusEffect(useCallback(() => { void refreshConversations(); }, [refreshConversations]));
  useEffect(() => {
    const target = conversations.find(item => item.contact.id === route.params?.initialUserId)?.contact;
    if (target) { navigation.setParams({ initialUserId: undefined }); navigation.navigate('Chat', { contact: target }); }
  }, [conversations, navigation, route.params?.initialUserId]);
  useEffect(() => { const timer = setTimeout(() => { if (search.trim()) void loadContacts(search); else setContacts([]); }, 350); return () => clearTimeout(timer); }, [loadContacts, search]);
  const open = (contact: MessageContact) => navigation.navigate('Chat', { contact });
  return <Screen topInset refreshing={loading} onRefresh={() => void refreshConversations()}><AppBar title="Tin nhắn" subtitle="Trao đổi trực tiếp trong LMS" /><View style={styles.search}><Ionicons name="search" size={20} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Tìm người dùng..." style={styles.searchInput} autoCapitalize="none" /></View>
    {!!error && <Text style={styles.error}>{error}</Text>}
    {search.trim() ? <><Text style={styles.sectionLabel}>KẾT QUẢ TÌM KIẾM</Text>{contacts.map(contact => <ContactRow key={contact.id} contact={contact} onPress={() => open(contact)} />)}{!loading && !contacts.length && <EmptyState title="Không tìm thấy người dùng" message="Thử tìm bằng tên hoặc email khác." />}</> : <><Text style={styles.sectionLabel}>CUỘC TRÒ CHUYỆN</Text>{conversations.map(item => <ContactRow key={item.contact.id} contact={item.contact} message={item.lastMessage.content} unread={item.unreadCount} time={item.lastMessage.createdAt} onPress={() => open(item.contact)} />)}{!loading && !conversations.length && <EmptyState title="Chưa có tin nhắn" message="Tìm một học viên hoặc giảng viên để bắt đầu trao đổi." />}</>}
  </Screen>;
}

function ContactRow({ contact, message, unread = 0, time, onPress }: { contact: MessageContact; message?: string; unread?: number; time?: string; onPress(): void }) {
  return <Pressable onPress={onPress}><Card style={styles.contact}><Avatar contact={contact} /><View style={{ flex: 1 }}><Text style={styles.contactName}>{contact.fullName}</Text><Text numberOfLines={1} style={[styles.preview, unread > 0 && styles.previewUnread]}>{message || `${contact.role}${contact.email ? ` · ${contact.email}` : ''}`}</Text></View><View style={styles.trailing}>{time && <Text style={styles.time}>{new Date(time).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</Text>}{unread > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{unread > 99 ? '99+' : unread}</Text></View>}</View></Card></Pressable>;
}

export function ChatScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'Chat'>) {
  const { user } = useAuth(); const { realtimeVersion, refreshConversations } = useMessages(); const { contact } = route.params;
  const [messages, setMessages] = useState<DirectMessage[]>([]); const [content, setContent] = useState(''); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const list = useRef<FlatList<DirectMessage>>(null);
  const load = useCallback(async () => { try { setMessages((await messagesApi.history(contact.id)).data.data.messages); setError(''); await refreshConversations(); } catch (e) { setError(getApiMessage(e)); } }, [contact.id, refreshConversations]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { if (realtimeVersion) void load(); }, [load, realtimeVersion]);
  useEffect(() => { if (messages.length) requestAnimationFrame(() => list.current?.scrollToEnd({ animated: true })); }, [messages.length]);
  async function send() { const text = content.trim(); if (!text || sending) return; setSending(true); setContent(''); try { const message = (await messagesApi.send(contact.id, text)).data.data; setMessages(old => [...old, message]); await refreshConversations(); } catch (e) { setContent(text); setError(getApiMessage(e)); } finally { setSending(false); } }
  return <KeyboardAvoidingView style={styles.chatPage} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={90}><AppBar title={contact.fullName} subtitle={contact.role} onBack={navigation.goBack} />{!!error && <Text style={styles.chatError}>{error}</Text>}<FlatList ref={list} data={messages} keyExtractor={item => item.id} contentContainerStyle={styles.messageList} onContentSizeChange={() => list.current?.scrollToEnd({ animated: false })} renderItem={({ item }) => { const mine = item.senderId === user?.id; return <View style={[styles.bubble, mine ? styles.bubbleMine : styles.bubbleOther]}><Text style={[styles.message, mine && styles.messageMine]}>{item.content}</Text><Text style={[styles.messageTime, mine && styles.messageTimeMine]}>{new Date(item.createdAt).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</Text></View>; }} ListEmptyComponent={<EmptyState title="Bắt đầu cuộc trò chuyện" message={`Gửi lời chào tới ${contact.fullName}.`} />} /><View style={styles.composer}><TextInput value={content} onChangeText={setContent} placeholder="Nhập tin nhắn..." multiline maxLength={5000} style={styles.composerInput} /><Pressable disabled={!content.trim() || sending} onPress={() => void send()} style={[styles.send, (!content.trim() || sending) && { opacity: .45 }]}><Ionicons name="send" size={21} color="#fff" /></Pressable></View></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ search: { minHeight: 52, borderRadius: 16, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 14, marginVertical: 16 }, searchInput: { flex: 1, color: colors.ink, fontSize: 15 }, sectionLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1, marginBottom: 9 }, error: { color: colors.danger, marginBottom: 10 }, empty: { alignItems: 'center', paddingVertical: 45, paddingHorizontal: 20 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: '900', marginTop: 12 }, emptyMessage: { color: colors.muted, textAlign: 'center', lineHeight: 19, marginTop: 5 }, contact: { minHeight: 74, padding: 12, marginBottom: 9, flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { backgroundColor: '#eee9ff', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontSize: 19, fontWeight: '900' }, contactName: { color: colors.ink, fontWeight: '900' }, preview: { color: colors.muted, fontSize: 12, marginTop: 4 }, previewUnread: { color: colors.ink, fontWeight: '800' }, trailing: { alignItems: 'flex-end', gap: 6 }, time: { color: colors.muted, fontSize: 9 }, badge: { minWidth: 21, height: 21, borderRadius: 11, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 }, badgeText: { color: '#fff', fontSize: 10, fontWeight: '900' }, chatPage: { flex: 1, backgroundColor: '#f7f8fc' }, chatError: { color: colors.danger, paddingHorizontal: 16, paddingTop: 8 }, messageList: { flexGrow: 1, padding: 15, justifyContent: 'flex-end' }, bubble: { maxWidth: '82%', borderRadius: 18, paddingHorizontal: 13, paddingVertical: 9, marginVertical: 4 }, bubbleMine: { alignSelf: 'flex-end', backgroundColor: colors.primary, borderBottomRightRadius: 5 }, bubbleOther: { alignSelf: 'flex-start', backgroundColor: '#fff', borderBottomLeftRadius: 5 }, message: { color: colors.ink, lineHeight: 20 }, messageMine: { color: '#fff' }, messageTime: { color: colors.muted, fontSize: 8, alignSelf: 'flex-end', marginTop: 4 }, messageTimeMine: { color: '#ded7ff' }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: 9, padding: 10, paddingBottom: Platform.OS === 'ios' ? 18 : 10, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: colors.border }, composerInput: { flex: 1, maxHeight: 110, minHeight: 44, borderRadius: 18, backgroundColor: '#f2f3f8', paddingHorizontal: 14, paddingVertical: 11, color: colors.ink }, send: { width: 45, height: 45, borderRadius: 15, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' } });
