
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CourseGradeRule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CourseGradeRule
 * 
 */
export type CourseGradeRuleModel = runtime.Types.Result.DefaultSelection<Prisma.$CourseGradeRulePayload>

export type AggregateCourseGradeRule = {
  _count: CourseGradeRuleCountAggregateOutputType | null
  _avg: CourseGradeRuleAvgAggregateOutputType | null
  _sum: CourseGradeRuleSumAggregateOutputType | null
  _min: CourseGradeRuleMinAggregateOutputType | null
  _max: CourseGradeRuleMaxAggregateOutputType | null
}

export type CourseGradeRuleAvgAggregateOutputType = {
  assignmentWeight: runtime.Decimal | null
  quizWeight: runtime.Decimal | null
  passingScore: runtime.Decimal | null
}

export type CourseGradeRuleSumAggregateOutputType = {
  assignmentWeight: runtime.Decimal | null
  quizWeight: runtime.Decimal | null
  passingScore: runtime.Decimal | null
}

export type CourseGradeRuleMinAggregateOutputType = {
  id: string | null
  courseId: string | null
  assignmentWeight: runtime.Decimal | null
  quizWeight: runtime.Decimal | null
  passingScore: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CourseGradeRuleMaxAggregateOutputType = {
  id: string | null
  courseId: string | null
  assignmentWeight: runtime.Decimal | null
  quizWeight: runtime.Decimal | null
  passingScore: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CourseGradeRuleCountAggregateOutputType = {
  id: number
  courseId: number
  assignmentWeight: number
  quizWeight: number
  passingScore: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CourseGradeRuleAvgAggregateInputType = {
  assignmentWeight?: true
  quizWeight?: true
  passingScore?: true
}

export type CourseGradeRuleSumAggregateInputType = {
  assignmentWeight?: true
  quizWeight?: true
  passingScore?: true
}

export type CourseGradeRuleMinAggregateInputType = {
  id?: true
  courseId?: true
  assignmentWeight?: true
  quizWeight?: true
  passingScore?: true
  createdAt?: true
  updatedAt?: true
}

export type CourseGradeRuleMaxAggregateInputType = {
  id?: true
  courseId?: true
  assignmentWeight?: true
  quizWeight?: true
  passingScore?: true
  createdAt?: true
  updatedAt?: true
}

export type CourseGradeRuleCountAggregateInputType = {
  id?: true
  courseId?: true
  assignmentWeight?: true
  quizWeight?: true
  passingScore?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CourseGradeRuleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CourseGradeRule to aggregate.
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseGradeRules to fetch.
   */
  orderBy?: Prisma.CourseGradeRuleOrderByWithRelationInput | Prisma.CourseGradeRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CourseGradeRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseGradeRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseGradeRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CourseGradeRules
  **/
  _count?: true | CourseGradeRuleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CourseGradeRuleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CourseGradeRuleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CourseGradeRuleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CourseGradeRuleMaxAggregateInputType
}

export type GetCourseGradeRuleAggregateType<T extends CourseGradeRuleAggregateArgs> = {
      [P in keyof T & keyof AggregateCourseGradeRule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourseGradeRule[P]>
    : Prisma.GetScalarType<T[P], AggregateCourseGradeRule[P]>
}




export type CourseGradeRuleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CourseGradeRuleWhereInput
  orderBy?: Prisma.CourseGradeRuleOrderByWithAggregationInput | Prisma.CourseGradeRuleOrderByWithAggregationInput[]
  by: Prisma.CourseGradeRuleScalarFieldEnum[] | Prisma.CourseGradeRuleScalarFieldEnum
  having?: Prisma.CourseGradeRuleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CourseGradeRuleCountAggregateInputType | true
  _avg?: CourseGradeRuleAvgAggregateInputType
  _sum?: CourseGradeRuleSumAggregateInputType
  _min?: CourseGradeRuleMinAggregateInputType
  _max?: CourseGradeRuleMaxAggregateInputType
}

export type CourseGradeRuleGroupByOutputType = {
  id: string
  courseId: string
  assignmentWeight: runtime.Decimal
  quizWeight: runtime.Decimal
  passingScore: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: CourseGradeRuleCountAggregateOutputType | null
  _avg: CourseGradeRuleAvgAggregateOutputType | null
  _sum: CourseGradeRuleSumAggregateOutputType | null
  _min: CourseGradeRuleMinAggregateOutputType | null
  _max: CourseGradeRuleMaxAggregateOutputType | null
}

export type GetCourseGradeRuleGroupByPayload<T extends CourseGradeRuleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CourseGradeRuleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CourseGradeRuleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CourseGradeRuleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CourseGradeRuleGroupByOutputType[P]>
      }
    >
  >



export type CourseGradeRuleWhereInput = {
  AND?: Prisma.CourseGradeRuleWhereInput | Prisma.CourseGradeRuleWhereInput[]
  OR?: Prisma.CourseGradeRuleWhereInput[]
  NOT?: Prisma.CourseGradeRuleWhereInput | Prisma.CourseGradeRuleWhereInput[]
  id?: Prisma.UuidFilter<"CourseGradeRule"> | string
  courseId?: Prisma.UuidFilter<"CourseGradeRule"> | string
  assignmentWeight?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CourseGradeRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CourseGradeRule"> | Date | string
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}

export type CourseGradeRuleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  course?: Prisma.CourseOrderByWithRelationInput
}

export type CourseGradeRuleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  courseId?: string
  AND?: Prisma.CourseGradeRuleWhereInput | Prisma.CourseGradeRuleWhereInput[]
  OR?: Prisma.CourseGradeRuleWhereInput[]
  NOT?: Prisma.CourseGradeRuleWhereInput | Prisma.CourseGradeRuleWhereInput[]
  assignmentWeight?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"CourseGradeRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CourseGradeRule"> | Date | string
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}, "id" | "courseId">

export type CourseGradeRuleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CourseGradeRuleCountOrderByAggregateInput
  _avg?: Prisma.CourseGradeRuleAvgOrderByAggregateInput
  _max?: Prisma.CourseGradeRuleMaxOrderByAggregateInput
  _min?: Prisma.CourseGradeRuleMinOrderByAggregateInput
  _sum?: Prisma.CourseGradeRuleSumOrderByAggregateInput
}

export type CourseGradeRuleScalarWhereWithAggregatesInput = {
  AND?: Prisma.CourseGradeRuleScalarWhereWithAggregatesInput | Prisma.CourseGradeRuleScalarWhereWithAggregatesInput[]
  OR?: Prisma.CourseGradeRuleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CourseGradeRuleScalarWhereWithAggregatesInput | Prisma.CourseGradeRuleScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"CourseGradeRule"> | string
  courseId?: Prisma.UuidWithAggregatesFilter<"CourseGradeRule"> | string
  assignmentWeight?: Prisma.DecimalWithAggregatesFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalWithAggregatesFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalWithAggregatesFilter<"CourseGradeRule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CourseGradeRule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CourseGradeRule"> | Date | string
}

export type CourseGradeRuleCreateInput = {
  id?: string
  assignmentWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  course: Prisma.CourseCreateNestedOneWithoutGradeRuleInput
}

export type CourseGradeRuleUncheckedCreateInput = {
  id?: string
  courseId: string
  assignmentWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourseGradeRuleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  course?: Prisma.CourseUpdateOneRequiredWithoutGradeRuleNestedInput
}

export type CourseGradeRuleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourseGradeRuleCreateManyInput = {
  id?: string
  courseId: string
  assignmentWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourseGradeRuleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourseGradeRuleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourseGradeRuleNullableScalarRelationFilter = {
  is?: Prisma.CourseGradeRuleWhereInput | null
  isNot?: Prisma.CourseGradeRuleWhereInput | null
}

export type CourseGradeRuleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourseGradeRuleAvgOrderByAggregateInput = {
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
}

export type CourseGradeRuleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourseGradeRuleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourseGradeRuleSumOrderByAggregateInput = {
  assignmentWeight?: Prisma.SortOrder
  quizWeight?: Prisma.SortOrder
  passingScore?: Prisma.SortOrder
}

export type CourseGradeRuleCreateNestedOneWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
  connectOrCreate?: Prisma.CourseGradeRuleCreateOrConnectWithoutCourseInput
  connect?: Prisma.CourseGradeRuleWhereUniqueInput
}

export type CourseGradeRuleUncheckedCreateNestedOneWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
  connectOrCreate?: Prisma.CourseGradeRuleCreateOrConnectWithoutCourseInput
  connect?: Prisma.CourseGradeRuleWhereUniqueInput
}

export type CourseGradeRuleUpdateOneWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
  connectOrCreate?: Prisma.CourseGradeRuleCreateOrConnectWithoutCourseInput
  upsert?: Prisma.CourseGradeRuleUpsertWithoutCourseInput
  disconnect?: Prisma.CourseGradeRuleWhereInput | boolean
  delete?: Prisma.CourseGradeRuleWhereInput | boolean
  connect?: Prisma.CourseGradeRuleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourseGradeRuleUpdateToOneWithWhereWithoutCourseInput, Prisma.CourseGradeRuleUpdateWithoutCourseInput>, Prisma.CourseGradeRuleUncheckedUpdateWithoutCourseInput>
}

export type CourseGradeRuleUncheckedUpdateOneWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
  connectOrCreate?: Prisma.CourseGradeRuleCreateOrConnectWithoutCourseInput
  upsert?: Prisma.CourseGradeRuleUpsertWithoutCourseInput
  disconnect?: Prisma.CourseGradeRuleWhereInput | boolean
  delete?: Prisma.CourseGradeRuleWhereInput | boolean
  connect?: Prisma.CourseGradeRuleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourseGradeRuleUpdateToOneWithWhereWithoutCourseInput, Prisma.CourseGradeRuleUpdateWithoutCourseInput>, Prisma.CourseGradeRuleUncheckedUpdateWithoutCourseInput>
}

export type CourseGradeRuleCreateWithoutCourseInput = {
  id?: string
  assignmentWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourseGradeRuleUncheckedCreateWithoutCourseInput = {
  id?: string
  assignmentWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourseGradeRuleCreateOrConnectWithoutCourseInput = {
  where: Prisma.CourseGradeRuleWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
}

export type CourseGradeRuleUpsertWithoutCourseInput = {
  update: Prisma.XOR<Prisma.CourseGradeRuleUpdateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.CourseGradeRuleCreateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedCreateWithoutCourseInput>
  where?: Prisma.CourseGradeRuleWhereInput
}

export type CourseGradeRuleUpdateToOneWithWhereWithoutCourseInput = {
  where?: Prisma.CourseGradeRuleWhereInput
  data: Prisma.XOR<Prisma.CourseGradeRuleUpdateWithoutCourseInput, Prisma.CourseGradeRuleUncheckedUpdateWithoutCourseInput>
}

export type CourseGradeRuleUpdateWithoutCourseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourseGradeRuleUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignmentWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  quizWeight?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  passingScore?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CourseGradeRuleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  courseId?: boolean
  assignmentWeight?: boolean
  quizWeight?: boolean
  passingScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseGradeRule"]>

export type CourseGradeRuleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  courseId?: boolean
  assignmentWeight?: boolean
  quizWeight?: boolean
  passingScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseGradeRule"]>

export type CourseGradeRuleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  courseId?: boolean
  assignmentWeight?: boolean
  quizWeight?: boolean
  passingScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseGradeRule"]>

export type CourseGradeRuleSelectScalar = {
  id?: boolean
  courseId?: boolean
  assignmentWeight?: boolean
  quizWeight?: boolean
  passingScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CourseGradeRuleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "courseId" | "assignmentWeight" | "quizWeight" | "passingScore" | "createdAt" | "updatedAt", ExtArgs["result"]["courseGradeRule"]>
export type CourseGradeRuleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type CourseGradeRuleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type CourseGradeRuleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}

export type $CourseGradeRulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CourseGradeRule"
  objects: {
    course: Prisma.$CoursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    courseId: string
    assignmentWeight: runtime.Decimal
    quizWeight: runtime.Decimal
    passingScore: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["courseGradeRule"]>
  composites: {}
}

export type CourseGradeRuleGetPayload<S extends boolean | null | undefined | CourseGradeRuleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload, S>

export type CourseGradeRuleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CourseGradeRuleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CourseGradeRuleCountAggregateInputType | true
  }

export interface CourseGradeRuleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CourseGradeRule'], meta: { name: 'CourseGradeRule' } }
  /**
   * Find zero or one CourseGradeRule that matches the filter.
   * @param {CourseGradeRuleFindUniqueArgs} args - Arguments to find a CourseGradeRule
   * @example
   * // Get one CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CourseGradeRuleFindUniqueArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CourseGradeRule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CourseGradeRuleFindUniqueOrThrowArgs} args - Arguments to find a CourseGradeRule
   * @example
   * // Get one CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CourseGradeRuleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CourseGradeRule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleFindFirstArgs} args - Arguments to find a CourseGradeRule
   * @example
   * // Get one CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CourseGradeRuleFindFirstArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleFindFirstArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CourseGradeRule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleFindFirstOrThrowArgs} args - Arguments to find a CourseGradeRule
   * @example
   * // Get one CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CourseGradeRuleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CourseGradeRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CourseGradeRules
   * const courseGradeRules = await prisma.courseGradeRule.findMany()
   * 
   * // Get first 10 CourseGradeRules
   * const courseGradeRules = await prisma.courseGradeRule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const courseGradeRuleWithIdOnly = await prisma.courseGradeRule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CourseGradeRuleFindManyArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CourseGradeRule.
   * @param {CourseGradeRuleCreateArgs} args - Arguments to create a CourseGradeRule.
   * @example
   * // Create one CourseGradeRule
   * const CourseGradeRule = await prisma.courseGradeRule.create({
   *   data: {
   *     // ... data to create a CourseGradeRule
   *   }
   * })
   * 
   */
  create<T extends CourseGradeRuleCreateArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleCreateArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CourseGradeRules.
   * @param {CourseGradeRuleCreateManyArgs} args - Arguments to create many CourseGradeRules.
   * @example
   * // Create many CourseGradeRules
   * const courseGradeRule = await prisma.courseGradeRule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CourseGradeRuleCreateManyArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CourseGradeRules and returns the data saved in the database.
   * @param {CourseGradeRuleCreateManyAndReturnArgs} args - Arguments to create many CourseGradeRules.
   * @example
   * // Create many CourseGradeRules
   * const courseGradeRule = await prisma.courseGradeRule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CourseGradeRules and only return the `id`
   * const courseGradeRuleWithIdOnly = await prisma.courseGradeRule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CourseGradeRuleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CourseGradeRule.
   * @param {CourseGradeRuleDeleteArgs} args - Arguments to delete one CourseGradeRule.
   * @example
   * // Delete one CourseGradeRule
   * const CourseGradeRule = await prisma.courseGradeRule.delete({
   *   where: {
   *     // ... filter to delete one CourseGradeRule
   *   }
   * })
   * 
   */
  delete<T extends CourseGradeRuleDeleteArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleDeleteArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CourseGradeRule.
   * @param {CourseGradeRuleUpdateArgs} args - Arguments to update one CourseGradeRule.
   * @example
   * // Update one CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CourseGradeRuleUpdateArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleUpdateArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CourseGradeRules.
   * @param {CourseGradeRuleDeleteManyArgs} args - Arguments to filter CourseGradeRules to delete.
   * @example
   * // Delete a few CourseGradeRules
   * const { count } = await prisma.courseGradeRule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CourseGradeRuleDeleteManyArgs>(args?: Prisma.SelectSubset<T, CourseGradeRuleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CourseGradeRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CourseGradeRules
   * const courseGradeRule = await prisma.courseGradeRule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CourseGradeRuleUpdateManyArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CourseGradeRules and returns the data updated in the database.
   * @param {CourseGradeRuleUpdateManyAndReturnArgs} args - Arguments to update many CourseGradeRules.
   * @example
   * // Update many CourseGradeRules
   * const courseGradeRule = await prisma.courseGradeRule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CourseGradeRules and only return the `id`
   * const courseGradeRuleWithIdOnly = await prisma.courseGradeRule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CourseGradeRuleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CourseGradeRule.
   * @param {CourseGradeRuleUpsertArgs} args - Arguments to update or create a CourseGradeRule.
   * @example
   * // Update or create a CourseGradeRule
   * const courseGradeRule = await prisma.courseGradeRule.upsert({
   *   create: {
   *     // ... data to create a CourseGradeRule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CourseGradeRule we want to update
   *   }
   * })
   */
  upsert<T extends CourseGradeRuleUpsertArgs>(args: Prisma.SelectSubset<T, CourseGradeRuleUpsertArgs<ExtArgs>>): Prisma.Prisma__CourseGradeRuleClient<runtime.Types.Result.GetResult<Prisma.$CourseGradeRulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CourseGradeRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleCountArgs} args - Arguments to filter CourseGradeRules to count.
   * @example
   * // Count the number of CourseGradeRules
   * const count = await prisma.courseGradeRule.count({
   *   where: {
   *     // ... the filter for the CourseGradeRules we want to count
   *   }
   * })
  **/
  count<T extends CourseGradeRuleCountArgs>(
    args?: Prisma.Subset<T, CourseGradeRuleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CourseGradeRuleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CourseGradeRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CourseGradeRuleAggregateArgs>(args: Prisma.Subset<T, CourseGradeRuleAggregateArgs>): Prisma.PrismaPromise<GetCourseGradeRuleAggregateType<T>>

  /**
   * Group by CourseGradeRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGradeRuleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CourseGradeRuleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CourseGradeRuleGroupByArgs['orderBy'] }
      : { orderBy?: CourseGradeRuleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CourseGradeRuleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCourseGradeRuleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CourseGradeRule model
 */
readonly fields: CourseGradeRuleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CourseGradeRule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CourseGradeRuleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  course<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CourseGradeRule model
 */
export interface CourseGradeRuleFieldRefs {
  readonly id: Prisma.FieldRef<"CourseGradeRule", 'String'>
  readonly courseId: Prisma.FieldRef<"CourseGradeRule", 'String'>
  readonly assignmentWeight: Prisma.FieldRef<"CourseGradeRule", 'Decimal'>
  readonly quizWeight: Prisma.FieldRef<"CourseGradeRule", 'Decimal'>
  readonly passingScore: Prisma.FieldRef<"CourseGradeRule", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"CourseGradeRule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CourseGradeRule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CourseGradeRule findUnique
 */
export type CourseGradeRuleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter, which CourseGradeRule to fetch.
   */
  where: Prisma.CourseGradeRuleWhereUniqueInput
}

/**
 * CourseGradeRule findUniqueOrThrow
 */
export type CourseGradeRuleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter, which CourseGradeRule to fetch.
   */
  where: Prisma.CourseGradeRuleWhereUniqueInput
}

/**
 * CourseGradeRule findFirst
 */
export type CourseGradeRuleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter, which CourseGradeRule to fetch.
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseGradeRules to fetch.
   */
  orderBy?: Prisma.CourseGradeRuleOrderByWithRelationInput | Prisma.CourseGradeRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CourseGradeRules.
   */
  cursor?: Prisma.CourseGradeRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseGradeRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseGradeRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CourseGradeRules.
   */
  distinct?: Prisma.CourseGradeRuleScalarFieldEnum | Prisma.CourseGradeRuleScalarFieldEnum[]
}

/**
 * CourseGradeRule findFirstOrThrow
 */
export type CourseGradeRuleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter, which CourseGradeRule to fetch.
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseGradeRules to fetch.
   */
  orderBy?: Prisma.CourseGradeRuleOrderByWithRelationInput | Prisma.CourseGradeRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CourseGradeRules.
   */
  cursor?: Prisma.CourseGradeRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseGradeRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseGradeRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CourseGradeRules.
   */
  distinct?: Prisma.CourseGradeRuleScalarFieldEnum | Prisma.CourseGradeRuleScalarFieldEnum[]
}

/**
 * CourseGradeRule findMany
 */
export type CourseGradeRuleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter, which CourseGradeRules to fetch.
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseGradeRules to fetch.
   */
  orderBy?: Prisma.CourseGradeRuleOrderByWithRelationInput | Prisma.CourseGradeRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CourseGradeRules.
   */
  cursor?: Prisma.CourseGradeRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseGradeRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseGradeRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CourseGradeRules.
   */
  distinct?: Prisma.CourseGradeRuleScalarFieldEnum | Prisma.CourseGradeRuleScalarFieldEnum[]
}

/**
 * CourseGradeRule create
 */
export type CourseGradeRuleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * The data needed to create a CourseGradeRule.
   */
  data: Prisma.XOR<Prisma.CourseGradeRuleCreateInput, Prisma.CourseGradeRuleUncheckedCreateInput>
}

/**
 * CourseGradeRule createMany
 */
export type CourseGradeRuleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CourseGradeRules.
   */
  data: Prisma.CourseGradeRuleCreateManyInput | Prisma.CourseGradeRuleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CourseGradeRule createManyAndReturn
 */
export type CourseGradeRuleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * The data used to create many CourseGradeRules.
   */
  data: Prisma.CourseGradeRuleCreateManyInput | Prisma.CourseGradeRuleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CourseGradeRule update
 */
export type CourseGradeRuleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * The data needed to update a CourseGradeRule.
   */
  data: Prisma.XOR<Prisma.CourseGradeRuleUpdateInput, Prisma.CourseGradeRuleUncheckedUpdateInput>
  /**
   * Choose, which CourseGradeRule to update.
   */
  where: Prisma.CourseGradeRuleWhereUniqueInput
}

/**
 * CourseGradeRule updateMany
 */
export type CourseGradeRuleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CourseGradeRules.
   */
  data: Prisma.XOR<Prisma.CourseGradeRuleUpdateManyMutationInput, Prisma.CourseGradeRuleUncheckedUpdateManyInput>
  /**
   * Filter which CourseGradeRules to update
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * Limit how many CourseGradeRules to update.
   */
  limit?: number
}

/**
 * CourseGradeRule updateManyAndReturn
 */
export type CourseGradeRuleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * The data used to update CourseGradeRules.
   */
  data: Prisma.XOR<Prisma.CourseGradeRuleUpdateManyMutationInput, Prisma.CourseGradeRuleUncheckedUpdateManyInput>
  /**
   * Filter which CourseGradeRules to update
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * Limit how many CourseGradeRules to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CourseGradeRule upsert
 */
export type CourseGradeRuleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * The filter to search for the CourseGradeRule to update in case it exists.
   */
  where: Prisma.CourseGradeRuleWhereUniqueInput
  /**
   * In case the CourseGradeRule found by the `where` argument doesn't exist, create a new CourseGradeRule with this data.
   */
  create: Prisma.XOR<Prisma.CourseGradeRuleCreateInput, Prisma.CourseGradeRuleUncheckedCreateInput>
  /**
   * In case the CourseGradeRule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CourseGradeRuleUpdateInput, Prisma.CourseGradeRuleUncheckedUpdateInput>
}

/**
 * CourseGradeRule delete
 */
export type CourseGradeRuleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
  /**
   * Filter which CourseGradeRule to delete.
   */
  where: Prisma.CourseGradeRuleWhereUniqueInput
}

/**
 * CourseGradeRule deleteMany
 */
export type CourseGradeRuleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CourseGradeRules to delete
   */
  where?: Prisma.CourseGradeRuleWhereInput
  /**
   * Limit how many CourseGradeRules to delete.
   */
  limit?: number
}

/**
 * CourseGradeRule without action
 */
export type CourseGradeRuleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseGradeRule
   */
  select?: Prisma.CourseGradeRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseGradeRule
   */
  omit?: Prisma.CourseGradeRuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseGradeRuleInclude<ExtArgs> | null
}
