
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LessonContent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model LessonContent
 * 
 */
export type LessonContentModel = runtime.Types.Result.DefaultSelection<Prisma.$LessonContentPayload>

export type AggregateLessonContent = {
  _count: LessonContentCountAggregateOutputType | null
  _avg: LessonContentAvgAggregateOutputType | null
  _sum: LessonContentSumAggregateOutputType | null
  _min: LessonContentMinAggregateOutputType | null
  _max: LessonContentMaxAggregateOutputType | null
}

export type LessonContentAvgAggregateOutputType = {
  sizeBytes: number | null
  position: number | null
}

export type LessonContentSumAggregateOutputType = {
  sizeBytes: number | null
  position: number | null
}

export type LessonContentMinAggregateOutputType = {
  id: string | null
  lessonId: string | null
  contentType: $Enums.LessonType | null
  textContent: string | null
  fileUrl: string | null
  originalName: string | null
  mimeType: string | null
  sizeBytes: number | null
  position: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LessonContentMaxAggregateOutputType = {
  id: string | null
  lessonId: string | null
  contentType: $Enums.LessonType | null
  textContent: string | null
  fileUrl: string | null
  originalName: string | null
  mimeType: string | null
  sizeBytes: number | null
  position: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LessonContentCountAggregateOutputType = {
  id: number
  lessonId: number
  contentType: number
  textContent: number
  fileUrl: number
  originalName: number
  mimeType: number
  sizeBytes: number
  position: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LessonContentAvgAggregateInputType = {
  sizeBytes?: true
  position?: true
}

export type LessonContentSumAggregateInputType = {
  sizeBytes?: true
  position?: true
}

export type LessonContentMinAggregateInputType = {
  id?: true
  lessonId?: true
  contentType?: true
  textContent?: true
  fileUrl?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  position?: true
  createdAt?: true
  updatedAt?: true
}

export type LessonContentMaxAggregateInputType = {
  id?: true
  lessonId?: true
  contentType?: true
  textContent?: true
  fileUrl?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  position?: true
  createdAt?: true
  updatedAt?: true
}

export type LessonContentCountAggregateInputType = {
  id?: true
  lessonId?: true
  contentType?: true
  textContent?: true
  fileUrl?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  position?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LessonContentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LessonContent to aggregate.
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LessonContents to fetch.
   */
  orderBy?: Prisma.LessonContentOrderByWithRelationInput | Prisma.LessonContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LessonContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LessonContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LessonContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LessonContents
  **/
  _count?: true | LessonContentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LessonContentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LessonContentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LessonContentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LessonContentMaxAggregateInputType
}

export type GetLessonContentAggregateType<T extends LessonContentAggregateArgs> = {
      [P in keyof T & keyof AggregateLessonContent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLessonContent[P]>
    : Prisma.GetScalarType<T[P], AggregateLessonContent[P]>
}




export type LessonContentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LessonContentWhereInput
  orderBy?: Prisma.LessonContentOrderByWithAggregationInput | Prisma.LessonContentOrderByWithAggregationInput[]
  by: Prisma.LessonContentScalarFieldEnum[] | Prisma.LessonContentScalarFieldEnum
  having?: Prisma.LessonContentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LessonContentCountAggregateInputType | true
  _avg?: LessonContentAvgAggregateInputType
  _sum?: LessonContentSumAggregateInputType
  _min?: LessonContentMinAggregateInputType
  _max?: LessonContentMaxAggregateInputType
}

export type LessonContentGroupByOutputType = {
  id: string
  lessonId: string
  contentType: $Enums.LessonType
  textContent: string | null
  fileUrl: string | null
  originalName: string | null
  mimeType: string | null
  sizeBytes: number | null
  position: number
  createdAt: Date
  updatedAt: Date
  _count: LessonContentCountAggregateOutputType | null
  _avg: LessonContentAvgAggregateOutputType | null
  _sum: LessonContentSumAggregateOutputType | null
  _min: LessonContentMinAggregateOutputType | null
  _max: LessonContentMaxAggregateOutputType | null
}

export type GetLessonContentGroupByPayload<T extends LessonContentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LessonContentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LessonContentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LessonContentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LessonContentGroupByOutputType[P]>
      }
    >
  >



export type LessonContentWhereInput = {
  AND?: Prisma.LessonContentWhereInput | Prisma.LessonContentWhereInput[]
  OR?: Prisma.LessonContentWhereInput[]
  NOT?: Prisma.LessonContentWhereInput | Prisma.LessonContentWhereInput[]
  id?: Prisma.UuidFilter<"LessonContent"> | string
  lessonId?: Prisma.UuidFilter<"LessonContent"> | string
  contentType?: Prisma.EnumLessonTypeFilter<"LessonContent"> | $Enums.LessonType
  textContent?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  fileUrl?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  originalName?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  mimeType?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"LessonContent"> | number | null
  position?: Prisma.IntFilter<"LessonContent"> | number
  createdAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
  lesson?: Prisma.XOR<Prisma.LessonScalarRelationFilter, Prisma.LessonWhereInput>
}

export type LessonContentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  textContent?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  originalName?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  position?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lesson?: Prisma.LessonOrderByWithRelationInput
}

export type LessonContentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  lessonId_position?: Prisma.LessonContentLessonIdPositionCompoundUniqueInput
  AND?: Prisma.LessonContentWhereInput | Prisma.LessonContentWhereInput[]
  OR?: Prisma.LessonContentWhereInput[]
  NOT?: Prisma.LessonContentWhereInput | Prisma.LessonContentWhereInput[]
  lessonId?: Prisma.UuidFilter<"LessonContent"> | string
  contentType?: Prisma.EnumLessonTypeFilter<"LessonContent"> | $Enums.LessonType
  textContent?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  fileUrl?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  originalName?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  mimeType?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"LessonContent"> | number | null
  position?: Prisma.IntFilter<"LessonContent"> | number
  createdAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
  lesson?: Prisma.XOR<Prisma.LessonScalarRelationFilter, Prisma.LessonWhereInput>
}, "id" | "lessonId_position">

export type LessonContentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  textContent?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  originalName?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  position?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LessonContentCountOrderByAggregateInput
  _avg?: Prisma.LessonContentAvgOrderByAggregateInput
  _max?: Prisma.LessonContentMaxOrderByAggregateInput
  _min?: Prisma.LessonContentMinOrderByAggregateInput
  _sum?: Prisma.LessonContentSumOrderByAggregateInput
}

export type LessonContentScalarWhereWithAggregatesInput = {
  AND?: Prisma.LessonContentScalarWhereWithAggregatesInput | Prisma.LessonContentScalarWhereWithAggregatesInput[]
  OR?: Prisma.LessonContentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LessonContentScalarWhereWithAggregatesInput | Prisma.LessonContentScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"LessonContent"> | string
  lessonId?: Prisma.UuidWithAggregatesFilter<"LessonContent"> | string
  contentType?: Prisma.EnumLessonTypeWithAggregatesFilter<"LessonContent"> | $Enums.LessonType
  textContent?: Prisma.StringNullableWithAggregatesFilter<"LessonContent"> | string | null
  fileUrl?: Prisma.StringNullableWithAggregatesFilter<"LessonContent"> | string | null
  originalName?: Prisma.StringNullableWithAggregatesFilter<"LessonContent"> | string | null
  mimeType?: Prisma.StringNullableWithAggregatesFilter<"LessonContent"> | string | null
  sizeBytes?: Prisma.IntNullableWithAggregatesFilter<"LessonContent"> | number | null
  position?: Prisma.IntWithAggregatesFilter<"LessonContent"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LessonContent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LessonContent"> | Date | string
}

export type LessonContentCreateInput = {
  id?: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lesson: Prisma.LessonCreateNestedOneWithoutContentsInput
}

export type LessonContentUncheckedCreateInput = {
  id?: string
  lessonId: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LessonContentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lesson?: Prisma.LessonUpdateOneRequiredWithoutContentsNestedInput
}

export type LessonContentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LessonContentCreateManyInput = {
  id?: string
  lessonId: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LessonContentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LessonContentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LessonContentLessonIdPositionCompoundUniqueInput = {
  lessonId: string
  position: number
}

export type LessonContentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  textContent?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  position?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LessonContentAvgOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type LessonContentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  textContent?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  position?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LessonContentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  textContent?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  position?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LessonContentSumOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type LessonContentListRelationFilter = {
  every?: Prisma.LessonContentWhereInput
  some?: Prisma.LessonContentWhereInput
  none?: Prisma.LessonContentWhereInput
}

export type LessonContentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumLessonTypeFieldUpdateOperationsInput = {
  set?: $Enums.LessonType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type LessonContentCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput> | Prisma.LessonContentCreateWithoutLessonInput[] | Prisma.LessonContentUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.LessonContentCreateOrConnectWithoutLessonInput | Prisma.LessonContentCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.LessonContentCreateManyLessonInputEnvelope
  connect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
}

export type LessonContentUncheckedCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput> | Prisma.LessonContentCreateWithoutLessonInput[] | Prisma.LessonContentUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.LessonContentCreateOrConnectWithoutLessonInput | Prisma.LessonContentCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.LessonContentCreateManyLessonInputEnvelope
  connect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
}

export type LessonContentUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput> | Prisma.LessonContentCreateWithoutLessonInput[] | Prisma.LessonContentUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.LessonContentCreateOrConnectWithoutLessonInput | Prisma.LessonContentCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.LessonContentUpsertWithWhereUniqueWithoutLessonInput | Prisma.LessonContentUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.LessonContentCreateManyLessonInputEnvelope
  set?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  disconnect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  delete?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  connect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  update?: Prisma.LessonContentUpdateWithWhereUniqueWithoutLessonInput | Prisma.LessonContentUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.LessonContentUpdateManyWithWhereWithoutLessonInput | Prisma.LessonContentUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.LessonContentScalarWhereInput | Prisma.LessonContentScalarWhereInput[]
}

export type LessonContentUncheckedUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput> | Prisma.LessonContentCreateWithoutLessonInput[] | Prisma.LessonContentUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.LessonContentCreateOrConnectWithoutLessonInput | Prisma.LessonContentCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.LessonContentUpsertWithWhereUniqueWithoutLessonInput | Prisma.LessonContentUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.LessonContentCreateManyLessonInputEnvelope
  set?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  disconnect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  delete?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  connect?: Prisma.LessonContentWhereUniqueInput | Prisma.LessonContentWhereUniqueInput[]
  update?: Prisma.LessonContentUpdateWithWhereUniqueWithoutLessonInput | Prisma.LessonContentUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.LessonContentUpdateManyWithWhereWithoutLessonInput | Prisma.LessonContentUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.LessonContentScalarWhereInput | Prisma.LessonContentScalarWhereInput[]
}

export type LessonContentCreateWithoutLessonInput = {
  id?: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LessonContentUncheckedCreateWithoutLessonInput = {
  id?: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LessonContentCreateOrConnectWithoutLessonInput = {
  where: Prisma.LessonContentWhereUniqueInput
  create: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput>
}

export type LessonContentCreateManyLessonInputEnvelope = {
  data: Prisma.LessonContentCreateManyLessonInput | Prisma.LessonContentCreateManyLessonInput[]
  skipDuplicates?: boolean
}

export type LessonContentUpsertWithWhereUniqueWithoutLessonInput = {
  where: Prisma.LessonContentWhereUniqueInput
  update: Prisma.XOR<Prisma.LessonContentUpdateWithoutLessonInput, Prisma.LessonContentUncheckedUpdateWithoutLessonInput>
  create: Prisma.XOR<Prisma.LessonContentCreateWithoutLessonInput, Prisma.LessonContentUncheckedCreateWithoutLessonInput>
}

export type LessonContentUpdateWithWhereUniqueWithoutLessonInput = {
  where: Prisma.LessonContentWhereUniqueInput
  data: Prisma.XOR<Prisma.LessonContentUpdateWithoutLessonInput, Prisma.LessonContentUncheckedUpdateWithoutLessonInput>
}

export type LessonContentUpdateManyWithWhereWithoutLessonInput = {
  where: Prisma.LessonContentScalarWhereInput
  data: Prisma.XOR<Prisma.LessonContentUpdateManyMutationInput, Prisma.LessonContentUncheckedUpdateManyWithoutLessonInput>
}

export type LessonContentScalarWhereInput = {
  AND?: Prisma.LessonContentScalarWhereInput | Prisma.LessonContentScalarWhereInput[]
  OR?: Prisma.LessonContentScalarWhereInput[]
  NOT?: Prisma.LessonContentScalarWhereInput | Prisma.LessonContentScalarWhereInput[]
  id?: Prisma.UuidFilter<"LessonContent"> | string
  lessonId?: Prisma.UuidFilter<"LessonContent"> | string
  contentType?: Prisma.EnumLessonTypeFilter<"LessonContent"> | $Enums.LessonType
  textContent?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  fileUrl?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  originalName?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  mimeType?: Prisma.StringNullableFilter<"LessonContent"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"LessonContent"> | number | null
  position?: Prisma.IntFilter<"LessonContent"> | number
  createdAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LessonContent"> | Date | string
}

export type LessonContentCreateManyLessonInput = {
  id?: string
  contentType: $Enums.LessonType
  textContent?: string | null
  fileUrl?: string | null
  originalName?: string | null
  mimeType?: string | null
  sizeBytes?: number | null
  position: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LessonContentUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LessonContentUncheckedUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LessonContentUncheckedUpdateManyWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.EnumLessonTypeFieldUpdateOperationsInput | $Enums.LessonType
  textContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  originalName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  position?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LessonContentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lessonId?: boolean
  contentType?: boolean
  textContent?: boolean
  fileUrl?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  position?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lessonContent"]>

export type LessonContentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lessonId?: boolean
  contentType?: boolean
  textContent?: boolean
  fileUrl?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  position?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lessonContent"]>

export type LessonContentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lessonId?: boolean
  contentType?: boolean
  textContent?: boolean
  fileUrl?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  position?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lessonContent"]>

export type LessonContentSelectScalar = {
  id?: boolean
  lessonId?: boolean
  contentType?: boolean
  textContent?: boolean
  fileUrl?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  position?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LessonContentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lessonId" | "contentType" | "textContent" | "fileUrl" | "originalName" | "mimeType" | "sizeBytes" | "position" | "createdAt" | "updatedAt", ExtArgs["result"]["lessonContent"]>
export type LessonContentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}
export type LessonContentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}
export type LessonContentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}

export type $LessonContentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LessonContent"
  objects: {
    lesson: Prisma.$LessonPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    lessonId: string
    contentType: $Enums.LessonType
    textContent: string | null
    fileUrl: string | null
    originalName: string | null
    mimeType: string | null
    sizeBytes: number | null
    position: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["lessonContent"]>
  composites: {}
}

export type LessonContentGetPayload<S extends boolean | null | undefined | LessonContentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LessonContentPayload, S>

export type LessonContentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LessonContentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LessonContentCountAggregateInputType | true
  }

export interface LessonContentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LessonContent'], meta: { name: 'LessonContent' } }
  /**
   * Find zero or one LessonContent that matches the filter.
   * @param {LessonContentFindUniqueArgs} args - Arguments to find a LessonContent
   * @example
   * // Get one LessonContent
   * const lessonContent = await prisma.lessonContent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LessonContentFindUniqueArgs>(args: Prisma.SelectSubset<T, LessonContentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LessonContent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LessonContentFindUniqueOrThrowArgs} args - Arguments to find a LessonContent
   * @example
   * // Get one LessonContent
   * const lessonContent = await prisma.lessonContent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LessonContentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LessonContentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LessonContent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentFindFirstArgs} args - Arguments to find a LessonContent
   * @example
   * // Get one LessonContent
   * const lessonContent = await prisma.lessonContent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LessonContentFindFirstArgs>(args?: Prisma.SelectSubset<T, LessonContentFindFirstArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LessonContent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentFindFirstOrThrowArgs} args - Arguments to find a LessonContent
   * @example
   * // Get one LessonContent
   * const lessonContent = await prisma.lessonContent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LessonContentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LessonContentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LessonContents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LessonContents
   * const lessonContents = await prisma.lessonContent.findMany()
   * 
   * // Get first 10 LessonContents
   * const lessonContents = await prisma.lessonContent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lessonContentWithIdOnly = await prisma.lessonContent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LessonContentFindManyArgs>(args?: Prisma.SelectSubset<T, LessonContentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LessonContent.
   * @param {LessonContentCreateArgs} args - Arguments to create a LessonContent.
   * @example
   * // Create one LessonContent
   * const LessonContent = await prisma.lessonContent.create({
   *   data: {
   *     // ... data to create a LessonContent
   *   }
   * })
   * 
   */
  create<T extends LessonContentCreateArgs>(args: Prisma.SelectSubset<T, LessonContentCreateArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LessonContents.
   * @param {LessonContentCreateManyArgs} args - Arguments to create many LessonContents.
   * @example
   * // Create many LessonContents
   * const lessonContent = await prisma.lessonContent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LessonContentCreateManyArgs>(args?: Prisma.SelectSubset<T, LessonContentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LessonContents and returns the data saved in the database.
   * @param {LessonContentCreateManyAndReturnArgs} args - Arguments to create many LessonContents.
   * @example
   * // Create many LessonContents
   * const lessonContent = await prisma.lessonContent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LessonContents and only return the `id`
   * const lessonContentWithIdOnly = await prisma.lessonContent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LessonContentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LessonContentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LessonContent.
   * @param {LessonContentDeleteArgs} args - Arguments to delete one LessonContent.
   * @example
   * // Delete one LessonContent
   * const LessonContent = await prisma.lessonContent.delete({
   *   where: {
   *     // ... filter to delete one LessonContent
   *   }
   * })
   * 
   */
  delete<T extends LessonContentDeleteArgs>(args: Prisma.SelectSubset<T, LessonContentDeleteArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LessonContent.
   * @param {LessonContentUpdateArgs} args - Arguments to update one LessonContent.
   * @example
   * // Update one LessonContent
   * const lessonContent = await prisma.lessonContent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LessonContentUpdateArgs>(args: Prisma.SelectSubset<T, LessonContentUpdateArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LessonContents.
   * @param {LessonContentDeleteManyArgs} args - Arguments to filter LessonContents to delete.
   * @example
   * // Delete a few LessonContents
   * const { count } = await prisma.lessonContent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LessonContentDeleteManyArgs>(args?: Prisma.SelectSubset<T, LessonContentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LessonContents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LessonContents
   * const lessonContent = await prisma.lessonContent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LessonContentUpdateManyArgs>(args: Prisma.SelectSubset<T, LessonContentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LessonContents and returns the data updated in the database.
   * @param {LessonContentUpdateManyAndReturnArgs} args - Arguments to update many LessonContents.
   * @example
   * // Update many LessonContents
   * const lessonContent = await prisma.lessonContent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LessonContents and only return the `id`
   * const lessonContentWithIdOnly = await prisma.lessonContent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LessonContentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LessonContentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LessonContent.
   * @param {LessonContentUpsertArgs} args - Arguments to update or create a LessonContent.
   * @example
   * // Update or create a LessonContent
   * const lessonContent = await prisma.lessonContent.upsert({
   *   create: {
   *     // ... data to create a LessonContent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LessonContent we want to update
   *   }
   * })
   */
  upsert<T extends LessonContentUpsertArgs>(args: Prisma.SelectSubset<T, LessonContentUpsertArgs<ExtArgs>>): Prisma.Prisma__LessonContentClient<runtime.Types.Result.GetResult<Prisma.$LessonContentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LessonContents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentCountArgs} args - Arguments to filter LessonContents to count.
   * @example
   * // Count the number of LessonContents
   * const count = await prisma.lessonContent.count({
   *   where: {
   *     // ... the filter for the LessonContents we want to count
   *   }
   * })
  **/
  count<T extends LessonContentCountArgs>(
    args?: Prisma.Subset<T, LessonContentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LessonContentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LessonContent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LessonContentAggregateArgs>(args: Prisma.Subset<T, LessonContentAggregateArgs>): Prisma.PrismaPromise<GetLessonContentAggregateType<T>>

  /**
   * Group by LessonContent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonContentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LessonContentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LessonContentGroupByArgs['orderBy'] }
      : { orderBy?: LessonContentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LessonContentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLessonContentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LessonContent model
 */
readonly fields: LessonContentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LessonContent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LessonContentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lesson<T extends Prisma.LessonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LessonDefaultArgs<ExtArgs>>): Prisma.Prisma__LessonClient<runtime.Types.Result.GetResult<Prisma.$LessonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LessonContent model
 */
export interface LessonContentFieldRefs {
  readonly id: Prisma.FieldRef<"LessonContent", 'String'>
  readonly lessonId: Prisma.FieldRef<"LessonContent", 'String'>
  readonly contentType: Prisma.FieldRef<"LessonContent", 'LessonType'>
  readonly textContent: Prisma.FieldRef<"LessonContent", 'String'>
  readonly fileUrl: Prisma.FieldRef<"LessonContent", 'String'>
  readonly originalName: Prisma.FieldRef<"LessonContent", 'String'>
  readonly mimeType: Prisma.FieldRef<"LessonContent", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"LessonContent", 'Int'>
  readonly position: Prisma.FieldRef<"LessonContent", 'Int'>
  readonly createdAt: Prisma.FieldRef<"LessonContent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LessonContent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LessonContent findUnique
 */
export type LessonContentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter, which LessonContent to fetch.
   */
  where: Prisma.LessonContentWhereUniqueInput
}

/**
 * LessonContent findUniqueOrThrow
 */
export type LessonContentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter, which LessonContent to fetch.
   */
  where: Prisma.LessonContentWhereUniqueInput
}

/**
 * LessonContent findFirst
 */
export type LessonContentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter, which LessonContent to fetch.
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LessonContents to fetch.
   */
  orderBy?: Prisma.LessonContentOrderByWithRelationInput | Prisma.LessonContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LessonContents.
   */
  cursor?: Prisma.LessonContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LessonContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LessonContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LessonContents.
   */
  distinct?: Prisma.LessonContentScalarFieldEnum | Prisma.LessonContentScalarFieldEnum[]
}

/**
 * LessonContent findFirstOrThrow
 */
export type LessonContentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter, which LessonContent to fetch.
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LessonContents to fetch.
   */
  orderBy?: Prisma.LessonContentOrderByWithRelationInput | Prisma.LessonContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LessonContents.
   */
  cursor?: Prisma.LessonContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LessonContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LessonContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LessonContents.
   */
  distinct?: Prisma.LessonContentScalarFieldEnum | Prisma.LessonContentScalarFieldEnum[]
}

/**
 * LessonContent findMany
 */
export type LessonContentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter, which LessonContents to fetch.
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LessonContents to fetch.
   */
  orderBy?: Prisma.LessonContentOrderByWithRelationInput | Prisma.LessonContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LessonContents.
   */
  cursor?: Prisma.LessonContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LessonContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LessonContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LessonContents.
   */
  distinct?: Prisma.LessonContentScalarFieldEnum | Prisma.LessonContentScalarFieldEnum[]
}

/**
 * LessonContent create
 */
export type LessonContentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * The data needed to create a LessonContent.
   */
  data: Prisma.XOR<Prisma.LessonContentCreateInput, Prisma.LessonContentUncheckedCreateInput>
}

/**
 * LessonContent createMany
 */
export type LessonContentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LessonContents.
   */
  data: Prisma.LessonContentCreateManyInput | Prisma.LessonContentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LessonContent createManyAndReturn
 */
export type LessonContentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * The data used to create many LessonContents.
   */
  data: Prisma.LessonContentCreateManyInput | Prisma.LessonContentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LessonContent update
 */
export type LessonContentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * The data needed to update a LessonContent.
   */
  data: Prisma.XOR<Prisma.LessonContentUpdateInput, Prisma.LessonContentUncheckedUpdateInput>
  /**
   * Choose, which LessonContent to update.
   */
  where: Prisma.LessonContentWhereUniqueInput
}

/**
 * LessonContent updateMany
 */
export type LessonContentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LessonContents.
   */
  data: Prisma.XOR<Prisma.LessonContentUpdateManyMutationInput, Prisma.LessonContentUncheckedUpdateManyInput>
  /**
   * Filter which LessonContents to update
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * Limit how many LessonContents to update.
   */
  limit?: number
}

/**
 * LessonContent updateManyAndReturn
 */
export type LessonContentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * The data used to update LessonContents.
   */
  data: Prisma.XOR<Prisma.LessonContentUpdateManyMutationInput, Prisma.LessonContentUncheckedUpdateManyInput>
  /**
   * Filter which LessonContents to update
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * Limit how many LessonContents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LessonContent upsert
 */
export type LessonContentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * The filter to search for the LessonContent to update in case it exists.
   */
  where: Prisma.LessonContentWhereUniqueInput
  /**
   * In case the LessonContent found by the `where` argument doesn't exist, create a new LessonContent with this data.
   */
  create: Prisma.XOR<Prisma.LessonContentCreateInput, Prisma.LessonContentUncheckedCreateInput>
  /**
   * In case the LessonContent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LessonContentUpdateInput, Prisma.LessonContentUncheckedUpdateInput>
}

/**
 * LessonContent delete
 */
export type LessonContentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
  /**
   * Filter which LessonContent to delete.
   */
  where: Prisma.LessonContentWhereUniqueInput
}

/**
 * LessonContent deleteMany
 */
export type LessonContentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LessonContents to delete
   */
  where?: Prisma.LessonContentWhereInput
  /**
   * Limit how many LessonContents to delete.
   */
  limit?: number
}

/**
 * LessonContent without action
 */
export type LessonContentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LessonContent
   */
  select?: Prisma.LessonContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LessonContent
   */
  omit?: Prisma.LessonContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonContentInclude<ExtArgs> | null
}
