
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubmissionFeedback` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SubmissionFeedback
 * 
 */
export type SubmissionFeedbackModel = runtime.Types.Result.DefaultSelection<Prisma.$SubmissionFeedbackPayload>

export type AggregateSubmissionFeedback = {
  _count: SubmissionFeedbackCountAggregateOutputType | null
  _avg: SubmissionFeedbackAvgAggregateOutputType | null
  _sum: SubmissionFeedbackSumAggregateOutputType | null
  _min: SubmissionFeedbackMinAggregateOutputType | null
  _max: SubmissionFeedbackMaxAggregateOutputType | null
}

export type SubmissionFeedbackAvgAggregateOutputType = {
  score: runtime.Decimal | null
}

export type SubmissionFeedbackSumAggregateOutputType = {
  score: runtime.Decimal | null
}

export type SubmissionFeedbackMinAggregateOutputType = {
  id: string | null
  submissionId: string | null
  graderId: string | null
  score: runtime.Decimal | null
  comment: string | null
  gradedAt: Date | null
  updatedAt: Date | null
}

export type SubmissionFeedbackMaxAggregateOutputType = {
  id: string | null
  submissionId: string | null
  graderId: string | null
  score: runtime.Decimal | null
  comment: string | null
  gradedAt: Date | null
  updatedAt: Date | null
}

export type SubmissionFeedbackCountAggregateOutputType = {
  id: number
  submissionId: number
  graderId: number
  score: number
  comment: number
  gradedAt: number
  updatedAt: number
  _all: number
}


export type SubmissionFeedbackAvgAggregateInputType = {
  score?: true
}

export type SubmissionFeedbackSumAggregateInputType = {
  score?: true
}

export type SubmissionFeedbackMinAggregateInputType = {
  id?: true
  submissionId?: true
  graderId?: true
  score?: true
  comment?: true
  gradedAt?: true
  updatedAt?: true
}

export type SubmissionFeedbackMaxAggregateInputType = {
  id?: true
  submissionId?: true
  graderId?: true
  score?: true
  comment?: true
  gradedAt?: true
  updatedAt?: true
}

export type SubmissionFeedbackCountAggregateInputType = {
  id?: true
  submissionId?: true
  graderId?: true
  score?: true
  comment?: true
  gradedAt?: true
  updatedAt?: true
  _all?: true
}

export type SubmissionFeedbackAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubmissionFeedback to aggregate.
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionFeedbacks to fetch.
   */
  orderBy?: Prisma.SubmissionFeedbackOrderByWithRelationInput | Prisma.SubmissionFeedbackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubmissionFeedbackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionFeedbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionFeedbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubmissionFeedbacks
  **/
  _count?: true | SubmissionFeedbackCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SubmissionFeedbackAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SubmissionFeedbackSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubmissionFeedbackMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubmissionFeedbackMaxAggregateInputType
}

export type GetSubmissionFeedbackAggregateType<T extends SubmissionFeedbackAggregateArgs> = {
      [P in keyof T & keyof AggregateSubmissionFeedback]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubmissionFeedback[P]>
    : Prisma.GetScalarType<T[P], AggregateSubmissionFeedback[P]>
}




export type SubmissionFeedbackGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubmissionFeedbackWhereInput
  orderBy?: Prisma.SubmissionFeedbackOrderByWithAggregationInput | Prisma.SubmissionFeedbackOrderByWithAggregationInput[]
  by: Prisma.SubmissionFeedbackScalarFieldEnum[] | Prisma.SubmissionFeedbackScalarFieldEnum
  having?: Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubmissionFeedbackCountAggregateInputType | true
  _avg?: SubmissionFeedbackAvgAggregateInputType
  _sum?: SubmissionFeedbackSumAggregateInputType
  _min?: SubmissionFeedbackMinAggregateInputType
  _max?: SubmissionFeedbackMaxAggregateInputType
}

export type SubmissionFeedbackGroupByOutputType = {
  id: string
  submissionId: string
  graderId: string
  score: runtime.Decimal
  comment: string | null
  gradedAt: Date
  updatedAt: Date
  _count: SubmissionFeedbackCountAggregateOutputType | null
  _avg: SubmissionFeedbackAvgAggregateOutputType | null
  _sum: SubmissionFeedbackSumAggregateOutputType | null
  _min: SubmissionFeedbackMinAggregateOutputType | null
  _max: SubmissionFeedbackMaxAggregateOutputType | null
}

export type GetSubmissionFeedbackGroupByPayload<T extends SubmissionFeedbackGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubmissionFeedbackGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubmissionFeedbackGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubmissionFeedbackGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubmissionFeedbackGroupByOutputType[P]>
      }
    >
  >



export type SubmissionFeedbackWhereInput = {
  AND?: Prisma.SubmissionFeedbackWhereInput | Prisma.SubmissionFeedbackWhereInput[]
  OR?: Prisma.SubmissionFeedbackWhereInput[]
  NOT?: Prisma.SubmissionFeedbackWhereInput | Prisma.SubmissionFeedbackWhereInput[]
  id?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  submissionId?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  graderId?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  score?: Prisma.DecimalFilter<"SubmissionFeedback"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.StringNullableFilter<"SubmissionFeedback"> | string | null
  gradedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
  submission?: Prisma.XOR<Prisma.AssignmentSubmissionScalarRelationFilter, Prisma.AssignmentSubmissionWhereInput>
  grader?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SubmissionFeedbackOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  graderId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  gradedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  submission?: Prisma.AssignmentSubmissionOrderByWithRelationInput
  grader?: Prisma.UserOrderByWithRelationInput
}

export type SubmissionFeedbackWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  submissionId?: string
  AND?: Prisma.SubmissionFeedbackWhereInput | Prisma.SubmissionFeedbackWhereInput[]
  OR?: Prisma.SubmissionFeedbackWhereInput[]
  NOT?: Prisma.SubmissionFeedbackWhereInput | Prisma.SubmissionFeedbackWhereInput[]
  graderId?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  score?: Prisma.DecimalFilter<"SubmissionFeedback"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.StringNullableFilter<"SubmissionFeedback"> | string | null
  gradedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
  submission?: Prisma.XOR<Prisma.AssignmentSubmissionScalarRelationFilter, Prisma.AssignmentSubmissionWhereInput>
  grader?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "submissionId">

export type SubmissionFeedbackOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  graderId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  gradedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SubmissionFeedbackCountOrderByAggregateInput
  _avg?: Prisma.SubmissionFeedbackAvgOrderByAggregateInput
  _max?: Prisma.SubmissionFeedbackMaxOrderByAggregateInput
  _min?: Prisma.SubmissionFeedbackMinOrderByAggregateInput
  _sum?: Prisma.SubmissionFeedbackSumOrderByAggregateInput
}

export type SubmissionFeedbackScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput | Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput | Prisma.SubmissionFeedbackScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"SubmissionFeedback"> | string
  submissionId?: Prisma.UuidWithAggregatesFilter<"SubmissionFeedback"> | string
  graderId?: Prisma.UuidWithAggregatesFilter<"SubmissionFeedback"> | string
  score?: Prisma.DecimalWithAggregatesFilter<"SubmissionFeedback"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.StringNullableWithAggregatesFilter<"SubmissionFeedback"> | string | null
  gradedAt?: Prisma.DateTimeWithAggregatesFilter<"SubmissionFeedback"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SubmissionFeedback"> | Date | string
}

export type SubmissionFeedbackCreateInput = {
  id?: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
  submission: Prisma.AssignmentSubmissionCreateNestedOneWithoutFeedbackInput
  grader: Prisma.UserCreateNestedOneWithoutSubmissionFeedbackInput
}

export type SubmissionFeedbackUncheckedCreateInput = {
  id?: string
  submissionId: string
  graderId: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionFeedbackUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submission?: Prisma.AssignmentSubmissionUpdateOneRequiredWithoutFeedbackNestedInput
  grader?: Prisma.UserUpdateOneRequiredWithoutSubmissionFeedbackNestedInput
}

export type SubmissionFeedbackUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  graderId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionFeedbackCreateManyInput = {
  id?: string
  submissionId: string
  graderId: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionFeedbackUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionFeedbackUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  graderId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionFeedbackListRelationFilter = {
  every?: Prisma.SubmissionFeedbackWhereInput
  some?: Prisma.SubmissionFeedbackWhereInput
  none?: Prisma.SubmissionFeedbackWhereInput
}

export type SubmissionFeedbackOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubmissionFeedbackNullableScalarRelationFilter = {
  is?: Prisma.SubmissionFeedbackWhereInput | null
  isNot?: Prisma.SubmissionFeedbackWhereInput | null
}

export type SubmissionFeedbackCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  graderId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  gradedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionFeedbackAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type SubmissionFeedbackMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  graderId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  gradedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionFeedbackMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  graderId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  gradedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionFeedbackSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type SubmissionFeedbackCreateNestedManyWithoutGraderInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput> | Prisma.SubmissionFeedbackCreateWithoutGraderInput[] | Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput[]
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput | Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput[]
  createMany?: Prisma.SubmissionFeedbackCreateManyGraderInputEnvelope
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
}

export type SubmissionFeedbackUncheckedCreateNestedManyWithoutGraderInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput> | Prisma.SubmissionFeedbackCreateWithoutGraderInput[] | Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput[]
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput | Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput[]
  createMany?: Prisma.SubmissionFeedbackCreateManyGraderInputEnvelope
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
}

export type SubmissionFeedbackUpdateManyWithoutGraderNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput> | Prisma.SubmissionFeedbackCreateWithoutGraderInput[] | Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput[]
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput | Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput[]
  upsert?: Prisma.SubmissionFeedbackUpsertWithWhereUniqueWithoutGraderInput | Prisma.SubmissionFeedbackUpsertWithWhereUniqueWithoutGraderInput[]
  createMany?: Prisma.SubmissionFeedbackCreateManyGraderInputEnvelope
  set?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  disconnect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  delete?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  update?: Prisma.SubmissionFeedbackUpdateWithWhereUniqueWithoutGraderInput | Prisma.SubmissionFeedbackUpdateWithWhereUniqueWithoutGraderInput[]
  updateMany?: Prisma.SubmissionFeedbackUpdateManyWithWhereWithoutGraderInput | Prisma.SubmissionFeedbackUpdateManyWithWhereWithoutGraderInput[]
  deleteMany?: Prisma.SubmissionFeedbackScalarWhereInput | Prisma.SubmissionFeedbackScalarWhereInput[]
}

export type SubmissionFeedbackUncheckedUpdateManyWithoutGraderNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput> | Prisma.SubmissionFeedbackCreateWithoutGraderInput[] | Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput[]
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput | Prisma.SubmissionFeedbackCreateOrConnectWithoutGraderInput[]
  upsert?: Prisma.SubmissionFeedbackUpsertWithWhereUniqueWithoutGraderInput | Prisma.SubmissionFeedbackUpsertWithWhereUniqueWithoutGraderInput[]
  createMany?: Prisma.SubmissionFeedbackCreateManyGraderInputEnvelope
  set?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  disconnect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  delete?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput | Prisma.SubmissionFeedbackWhereUniqueInput[]
  update?: Prisma.SubmissionFeedbackUpdateWithWhereUniqueWithoutGraderInput | Prisma.SubmissionFeedbackUpdateWithWhereUniqueWithoutGraderInput[]
  updateMany?: Prisma.SubmissionFeedbackUpdateManyWithWhereWithoutGraderInput | Prisma.SubmissionFeedbackUpdateManyWithWhereWithoutGraderInput[]
  deleteMany?: Prisma.SubmissionFeedbackScalarWhereInput | Prisma.SubmissionFeedbackScalarWhereInput[]
}

export type SubmissionFeedbackCreateNestedOneWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutSubmissionInput
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput
}

export type SubmissionFeedbackUncheckedCreateNestedOneWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutSubmissionInput
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput
}

export type SubmissionFeedbackUpdateOneWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutSubmissionInput
  upsert?: Prisma.SubmissionFeedbackUpsertWithoutSubmissionInput
  disconnect?: Prisma.SubmissionFeedbackWhereInput | boolean
  delete?: Prisma.SubmissionFeedbackWhereInput | boolean
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubmissionFeedbackUpdateToOneWithWhereWithoutSubmissionInput, Prisma.SubmissionFeedbackUpdateWithoutSubmissionInput>, Prisma.SubmissionFeedbackUncheckedUpdateWithoutSubmissionInput>
}

export type SubmissionFeedbackUncheckedUpdateOneWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
  connectOrCreate?: Prisma.SubmissionFeedbackCreateOrConnectWithoutSubmissionInput
  upsert?: Prisma.SubmissionFeedbackUpsertWithoutSubmissionInput
  disconnect?: Prisma.SubmissionFeedbackWhereInput | boolean
  delete?: Prisma.SubmissionFeedbackWhereInput | boolean
  connect?: Prisma.SubmissionFeedbackWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubmissionFeedbackUpdateToOneWithWhereWithoutSubmissionInput, Prisma.SubmissionFeedbackUpdateWithoutSubmissionInput>, Prisma.SubmissionFeedbackUncheckedUpdateWithoutSubmissionInput>
}

export type SubmissionFeedbackCreateWithoutGraderInput = {
  id?: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
  submission: Prisma.AssignmentSubmissionCreateNestedOneWithoutFeedbackInput
}

export type SubmissionFeedbackUncheckedCreateWithoutGraderInput = {
  id?: string
  submissionId: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionFeedbackCreateOrConnectWithoutGraderInput = {
  where: Prisma.SubmissionFeedbackWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput>
}

export type SubmissionFeedbackCreateManyGraderInputEnvelope = {
  data: Prisma.SubmissionFeedbackCreateManyGraderInput | Prisma.SubmissionFeedbackCreateManyGraderInput[]
  skipDuplicates?: boolean
}

export type SubmissionFeedbackUpsertWithWhereUniqueWithoutGraderInput = {
  where: Prisma.SubmissionFeedbackWhereUniqueInput
  update: Prisma.XOR<Prisma.SubmissionFeedbackUpdateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedUpdateWithoutGraderInput>
  create: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutGraderInput>
}

export type SubmissionFeedbackUpdateWithWhereUniqueWithoutGraderInput = {
  where: Prisma.SubmissionFeedbackWhereUniqueInput
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateWithoutGraderInput, Prisma.SubmissionFeedbackUncheckedUpdateWithoutGraderInput>
}

export type SubmissionFeedbackUpdateManyWithWhereWithoutGraderInput = {
  where: Prisma.SubmissionFeedbackScalarWhereInput
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateManyMutationInput, Prisma.SubmissionFeedbackUncheckedUpdateManyWithoutGraderInput>
}

export type SubmissionFeedbackScalarWhereInput = {
  AND?: Prisma.SubmissionFeedbackScalarWhereInput | Prisma.SubmissionFeedbackScalarWhereInput[]
  OR?: Prisma.SubmissionFeedbackScalarWhereInput[]
  NOT?: Prisma.SubmissionFeedbackScalarWhereInput | Prisma.SubmissionFeedbackScalarWhereInput[]
  id?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  submissionId?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  graderId?: Prisma.UuidFilter<"SubmissionFeedback"> | string
  score?: Prisma.DecimalFilter<"SubmissionFeedback"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.StringNullableFilter<"SubmissionFeedback"> | string | null
  gradedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SubmissionFeedback"> | Date | string
}

export type SubmissionFeedbackCreateWithoutSubmissionInput = {
  id?: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
  grader: Prisma.UserCreateNestedOneWithoutSubmissionFeedbackInput
}

export type SubmissionFeedbackUncheckedCreateWithoutSubmissionInput = {
  id?: string
  graderId: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionFeedbackCreateOrConnectWithoutSubmissionInput = {
  where: Prisma.SubmissionFeedbackWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
}

export type SubmissionFeedbackUpsertWithoutSubmissionInput = {
  update: Prisma.XOR<Prisma.SubmissionFeedbackUpdateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedUpdateWithoutSubmissionInput>
  create: Prisma.XOR<Prisma.SubmissionFeedbackCreateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedCreateWithoutSubmissionInput>
  where?: Prisma.SubmissionFeedbackWhereInput
}

export type SubmissionFeedbackUpdateToOneWithWhereWithoutSubmissionInput = {
  where?: Prisma.SubmissionFeedbackWhereInput
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateWithoutSubmissionInput, Prisma.SubmissionFeedbackUncheckedUpdateWithoutSubmissionInput>
}

export type SubmissionFeedbackUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grader?: Prisma.UserUpdateOneRequiredWithoutSubmissionFeedbackNestedInput
}

export type SubmissionFeedbackUncheckedUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  graderId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionFeedbackCreateManyGraderInput = {
  id?: string
  submissionId: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: string | null
  gradedAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionFeedbackUpdateWithoutGraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submission?: Prisma.AssignmentSubmissionUpdateOneRequiredWithoutFeedbackNestedInput
}

export type SubmissionFeedbackUncheckedUpdateWithoutGraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionFeedbackUncheckedUpdateManyWithoutGraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gradedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SubmissionFeedbackSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  graderId?: boolean
  score?: boolean
  comment?: boolean
  gradedAt?: boolean
  updatedAt?: boolean
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submissionFeedback"]>

export type SubmissionFeedbackSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  graderId?: boolean
  score?: boolean
  comment?: boolean
  gradedAt?: boolean
  updatedAt?: boolean
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submissionFeedback"]>

export type SubmissionFeedbackSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  graderId?: boolean
  score?: boolean
  comment?: boolean
  gradedAt?: boolean
  updatedAt?: boolean
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submissionFeedback"]>

export type SubmissionFeedbackSelectScalar = {
  id?: boolean
  submissionId?: boolean
  graderId?: boolean
  score?: boolean
  comment?: boolean
  gradedAt?: boolean
  updatedAt?: boolean
}

export type SubmissionFeedbackOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "submissionId" | "graderId" | "score" | "comment" | "gradedAt" | "updatedAt", ExtArgs["result"]["submissionFeedback"]>
export type SubmissionFeedbackInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SubmissionFeedbackIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SubmissionFeedbackIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>
  grader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SubmissionFeedbackPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubmissionFeedback"
  objects: {
    submission: Prisma.$AssignmentSubmissionPayload<ExtArgs>
    grader: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    submissionId: string
    graderId: string
    score: runtime.Decimal
    comment: string | null
    gradedAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["submissionFeedback"]>
  composites: {}
}

export type SubmissionFeedbackGetPayload<S extends boolean | null | undefined | SubmissionFeedbackDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload, S>

export type SubmissionFeedbackCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubmissionFeedbackFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubmissionFeedbackCountAggregateInputType | true
  }

export interface SubmissionFeedbackDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubmissionFeedback'], meta: { name: 'SubmissionFeedback' } }
  /**
   * Find zero or one SubmissionFeedback that matches the filter.
   * @param {SubmissionFeedbackFindUniqueArgs} args - Arguments to find a SubmissionFeedback
   * @example
   * // Get one SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubmissionFeedbackFindUniqueArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubmissionFeedback that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubmissionFeedbackFindUniqueOrThrowArgs} args - Arguments to find a SubmissionFeedback
   * @example
   * // Get one SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubmissionFeedbackFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubmissionFeedback that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackFindFirstArgs} args - Arguments to find a SubmissionFeedback
   * @example
   * // Get one SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubmissionFeedbackFindFirstArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubmissionFeedback that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackFindFirstOrThrowArgs} args - Arguments to find a SubmissionFeedback
   * @example
   * // Get one SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubmissionFeedbackFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubmissionFeedbacks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubmissionFeedbacks
   * const submissionFeedbacks = await prisma.submissionFeedback.findMany()
   * 
   * // Get first 10 SubmissionFeedbacks
   * const submissionFeedbacks = await prisma.submissionFeedback.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const submissionFeedbackWithIdOnly = await prisma.submissionFeedback.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubmissionFeedbackFindManyArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubmissionFeedback.
   * @param {SubmissionFeedbackCreateArgs} args - Arguments to create a SubmissionFeedback.
   * @example
   * // Create one SubmissionFeedback
   * const SubmissionFeedback = await prisma.submissionFeedback.create({
   *   data: {
   *     // ... data to create a SubmissionFeedback
   *   }
   * })
   * 
   */
  create<T extends SubmissionFeedbackCreateArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackCreateArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubmissionFeedbacks.
   * @param {SubmissionFeedbackCreateManyArgs} args - Arguments to create many SubmissionFeedbacks.
   * @example
   * // Create many SubmissionFeedbacks
   * const submissionFeedback = await prisma.submissionFeedback.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubmissionFeedbackCreateManyArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubmissionFeedbacks and returns the data saved in the database.
   * @param {SubmissionFeedbackCreateManyAndReturnArgs} args - Arguments to create many SubmissionFeedbacks.
   * @example
   * // Create many SubmissionFeedbacks
   * const submissionFeedback = await prisma.submissionFeedback.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubmissionFeedbacks and only return the `id`
   * const submissionFeedbackWithIdOnly = await prisma.submissionFeedback.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubmissionFeedbackCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubmissionFeedback.
   * @param {SubmissionFeedbackDeleteArgs} args - Arguments to delete one SubmissionFeedback.
   * @example
   * // Delete one SubmissionFeedback
   * const SubmissionFeedback = await prisma.submissionFeedback.delete({
   *   where: {
   *     // ... filter to delete one SubmissionFeedback
   *   }
   * })
   * 
   */
  delete<T extends SubmissionFeedbackDeleteArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackDeleteArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubmissionFeedback.
   * @param {SubmissionFeedbackUpdateArgs} args - Arguments to update one SubmissionFeedback.
   * @example
   * // Update one SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubmissionFeedbackUpdateArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackUpdateArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubmissionFeedbacks.
   * @param {SubmissionFeedbackDeleteManyArgs} args - Arguments to filter SubmissionFeedbacks to delete.
   * @example
   * // Delete a few SubmissionFeedbacks
   * const { count } = await prisma.submissionFeedback.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubmissionFeedbackDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubmissionFeedbackDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubmissionFeedbacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubmissionFeedbacks
   * const submissionFeedback = await prisma.submissionFeedback.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubmissionFeedbackUpdateManyArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubmissionFeedbacks and returns the data updated in the database.
   * @param {SubmissionFeedbackUpdateManyAndReturnArgs} args - Arguments to update many SubmissionFeedbacks.
   * @example
   * // Update many SubmissionFeedbacks
   * const submissionFeedback = await prisma.submissionFeedback.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubmissionFeedbacks and only return the `id`
   * const submissionFeedbackWithIdOnly = await prisma.submissionFeedback.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubmissionFeedbackUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubmissionFeedback.
   * @param {SubmissionFeedbackUpsertArgs} args - Arguments to update or create a SubmissionFeedback.
   * @example
   * // Update or create a SubmissionFeedback
   * const submissionFeedback = await prisma.submissionFeedback.upsert({
   *   create: {
   *     // ... data to create a SubmissionFeedback
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubmissionFeedback we want to update
   *   }
   * })
   */
  upsert<T extends SubmissionFeedbackUpsertArgs>(args: Prisma.SelectSubset<T, SubmissionFeedbackUpsertArgs<ExtArgs>>): Prisma.Prisma__SubmissionFeedbackClient<runtime.Types.Result.GetResult<Prisma.$SubmissionFeedbackPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubmissionFeedbacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackCountArgs} args - Arguments to filter SubmissionFeedbacks to count.
   * @example
   * // Count the number of SubmissionFeedbacks
   * const count = await prisma.submissionFeedback.count({
   *   where: {
   *     // ... the filter for the SubmissionFeedbacks we want to count
   *   }
   * })
  **/
  count<T extends SubmissionFeedbackCountArgs>(
    args?: Prisma.Subset<T, SubmissionFeedbackCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubmissionFeedbackCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubmissionFeedback.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubmissionFeedbackAggregateArgs>(args: Prisma.Subset<T, SubmissionFeedbackAggregateArgs>): Prisma.PrismaPromise<GetSubmissionFeedbackAggregateType<T>>

  /**
   * Group by SubmissionFeedback.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFeedbackGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubmissionFeedbackGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubmissionFeedbackGroupByArgs['orderBy'] }
      : { orderBy?: SubmissionFeedbackGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubmissionFeedbackGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubmissionFeedbackGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubmissionFeedback model
 */
readonly fields: SubmissionFeedbackFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubmissionFeedback.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubmissionFeedbackClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  submission<T extends Prisma.AssignmentSubmissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssignmentSubmissionDefaultArgs<ExtArgs>>): Prisma.Prisma__AssignmentSubmissionClient<runtime.Types.Result.GetResult<Prisma.$AssignmentSubmissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  grader<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubmissionFeedback model
 */
export interface SubmissionFeedbackFieldRefs {
  readonly id: Prisma.FieldRef<"SubmissionFeedback", 'String'>
  readonly submissionId: Prisma.FieldRef<"SubmissionFeedback", 'String'>
  readonly graderId: Prisma.FieldRef<"SubmissionFeedback", 'String'>
  readonly score: Prisma.FieldRef<"SubmissionFeedback", 'Decimal'>
  readonly comment: Prisma.FieldRef<"SubmissionFeedback", 'String'>
  readonly gradedAt: Prisma.FieldRef<"SubmissionFeedback", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SubmissionFeedback", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SubmissionFeedback findUnique
 */
export type SubmissionFeedbackFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionFeedback to fetch.
   */
  where: Prisma.SubmissionFeedbackWhereUniqueInput
}

/**
 * SubmissionFeedback findUniqueOrThrow
 */
export type SubmissionFeedbackFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionFeedback to fetch.
   */
  where: Prisma.SubmissionFeedbackWhereUniqueInput
}

/**
 * SubmissionFeedback findFirst
 */
export type SubmissionFeedbackFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionFeedback to fetch.
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionFeedbacks to fetch.
   */
  orderBy?: Prisma.SubmissionFeedbackOrderByWithRelationInput | Prisma.SubmissionFeedbackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubmissionFeedbacks.
   */
  cursor?: Prisma.SubmissionFeedbackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionFeedbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionFeedbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubmissionFeedbacks.
   */
  distinct?: Prisma.SubmissionFeedbackScalarFieldEnum | Prisma.SubmissionFeedbackScalarFieldEnum[]
}

/**
 * SubmissionFeedback findFirstOrThrow
 */
export type SubmissionFeedbackFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionFeedback to fetch.
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionFeedbacks to fetch.
   */
  orderBy?: Prisma.SubmissionFeedbackOrderByWithRelationInput | Prisma.SubmissionFeedbackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubmissionFeedbacks.
   */
  cursor?: Prisma.SubmissionFeedbackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionFeedbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionFeedbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubmissionFeedbacks.
   */
  distinct?: Prisma.SubmissionFeedbackScalarFieldEnum | Prisma.SubmissionFeedbackScalarFieldEnum[]
}

/**
 * SubmissionFeedback findMany
 */
export type SubmissionFeedbackFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter, which SubmissionFeedbacks to fetch.
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubmissionFeedbacks to fetch.
   */
  orderBy?: Prisma.SubmissionFeedbackOrderByWithRelationInput | Prisma.SubmissionFeedbackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubmissionFeedbacks.
   */
  cursor?: Prisma.SubmissionFeedbackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubmissionFeedbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubmissionFeedbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubmissionFeedbacks.
   */
  distinct?: Prisma.SubmissionFeedbackScalarFieldEnum | Prisma.SubmissionFeedbackScalarFieldEnum[]
}

/**
 * SubmissionFeedback create
 */
export type SubmissionFeedbackCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * The data needed to create a SubmissionFeedback.
   */
  data: Prisma.XOR<Prisma.SubmissionFeedbackCreateInput, Prisma.SubmissionFeedbackUncheckedCreateInput>
}

/**
 * SubmissionFeedback createMany
 */
export type SubmissionFeedbackCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubmissionFeedbacks.
   */
  data: Prisma.SubmissionFeedbackCreateManyInput | Prisma.SubmissionFeedbackCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubmissionFeedback createManyAndReturn
 */
export type SubmissionFeedbackCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * The data used to create many SubmissionFeedbacks.
   */
  data: Prisma.SubmissionFeedbackCreateManyInput | Prisma.SubmissionFeedbackCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubmissionFeedback update
 */
export type SubmissionFeedbackUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * The data needed to update a SubmissionFeedback.
   */
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateInput, Prisma.SubmissionFeedbackUncheckedUpdateInput>
  /**
   * Choose, which SubmissionFeedback to update.
   */
  where: Prisma.SubmissionFeedbackWhereUniqueInput
}

/**
 * SubmissionFeedback updateMany
 */
export type SubmissionFeedbackUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubmissionFeedbacks.
   */
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateManyMutationInput, Prisma.SubmissionFeedbackUncheckedUpdateManyInput>
  /**
   * Filter which SubmissionFeedbacks to update
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * Limit how many SubmissionFeedbacks to update.
   */
  limit?: number
}

/**
 * SubmissionFeedback updateManyAndReturn
 */
export type SubmissionFeedbackUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * The data used to update SubmissionFeedbacks.
   */
  data: Prisma.XOR<Prisma.SubmissionFeedbackUpdateManyMutationInput, Prisma.SubmissionFeedbackUncheckedUpdateManyInput>
  /**
   * Filter which SubmissionFeedbacks to update
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * Limit how many SubmissionFeedbacks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubmissionFeedback upsert
 */
export type SubmissionFeedbackUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * The filter to search for the SubmissionFeedback to update in case it exists.
   */
  where: Prisma.SubmissionFeedbackWhereUniqueInput
  /**
   * In case the SubmissionFeedback found by the `where` argument doesn't exist, create a new SubmissionFeedback with this data.
   */
  create: Prisma.XOR<Prisma.SubmissionFeedbackCreateInput, Prisma.SubmissionFeedbackUncheckedCreateInput>
  /**
   * In case the SubmissionFeedback was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubmissionFeedbackUpdateInput, Prisma.SubmissionFeedbackUncheckedUpdateInput>
}

/**
 * SubmissionFeedback delete
 */
export type SubmissionFeedbackDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
  /**
   * Filter which SubmissionFeedback to delete.
   */
  where: Prisma.SubmissionFeedbackWhereUniqueInput
}

/**
 * SubmissionFeedback deleteMany
 */
export type SubmissionFeedbackDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubmissionFeedbacks to delete
   */
  where?: Prisma.SubmissionFeedbackWhereInput
  /**
   * Limit how many SubmissionFeedbacks to delete.
   */
  limit?: number
}

/**
 * SubmissionFeedback without action
 */
export type SubmissionFeedbackDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionFeedback
   */
  select?: Prisma.SubmissionFeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubmissionFeedback
   */
  omit?: Prisma.SubmissionFeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionFeedbackInclude<ExtArgs> | null
}
