
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VideoWatchEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model VideoWatchEvent
 * 
 */
export type VideoWatchEventModel = runtime.Types.Result.DefaultSelection<Prisma.$VideoWatchEventPayload>

export type AggregateVideoWatchEvent = {
  _count: VideoWatchEventCountAggregateOutputType | null
  _avg: VideoWatchEventAvgAggregateOutputType | null
  _sum: VideoWatchEventSumAggregateOutputType | null
  _min: VideoWatchEventMinAggregateOutputType | null
  _max: VideoWatchEventMaxAggregateOutputType | null
}

export type VideoWatchEventAvgAggregateOutputType = {
  startPositionSeconds: number | null
  endPositionSeconds: number | null
  watchedSeconds: number | null
}

export type VideoWatchEventSumAggregateOutputType = {
  startPositionSeconds: number | null
  endPositionSeconds: number | null
  watchedSeconds: number | null
}

export type VideoWatchEventMinAggregateOutputType = {
  id: string | null
  userId: string | null
  courseId: string | null
  lessonId: string | null
  sessionId: string | null
  startedAt: Date | null
  endedAt: Date | null
  startPositionSeconds: number | null
  endPositionSeconds: number | null
  watchedSeconds: number | null
  completed: boolean | null
  createdAt: Date | null
}

export type VideoWatchEventMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  courseId: string | null
  lessonId: string | null
  sessionId: string | null
  startedAt: Date | null
  endedAt: Date | null
  startPositionSeconds: number | null
  endPositionSeconds: number | null
  watchedSeconds: number | null
  completed: boolean | null
  createdAt: Date | null
}

export type VideoWatchEventCountAggregateOutputType = {
  id: number
  userId: number
  courseId: number
  lessonId: number
  sessionId: number
  startedAt: number
  endedAt: number
  startPositionSeconds: number
  endPositionSeconds: number
  watchedSeconds: number
  completed: number
  createdAt: number
  _all: number
}


export type VideoWatchEventAvgAggregateInputType = {
  startPositionSeconds?: true
  endPositionSeconds?: true
  watchedSeconds?: true
}

export type VideoWatchEventSumAggregateInputType = {
  startPositionSeconds?: true
  endPositionSeconds?: true
  watchedSeconds?: true
}

export type VideoWatchEventMinAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  lessonId?: true
  sessionId?: true
  startedAt?: true
  endedAt?: true
  startPositionSeconds?: true
  endPositionSeconds?: true
  watchedSeconds?: true
  completed?: true
  createdAt?: true
}

export type VideoWatchEventMaxAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  lessonId?: true
  sessionId?: true
  startedAt?: true
  endedAt?: true
  startPositionSeconds?: true
  endPositionSeconds?: true
  watchedSeconds?: true
  completed?: true
  createdAt?: true
}

export type VideoWatchEventCountAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  lessonId?: true
  sessionId?: true
  startedAt?: true
  endedAt?: true
  startPositionSeconds?: true
  endPositionSeconds?: true
  watchedSeconds?: true
  completed?: true
  createdAt?: true
  _all?: true
}

export type VideoWatchEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoWatchEvent to aggregate.
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoWatchEvents to fetch.
   */
  orderBy?: Prisma.VideoWatchEventOrderByWithRelationInput | Prisma.VideoWatchEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VideoWatchEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoWatchEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoWatchEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VideoWatchEvents
  **/
  _count?: true | VideoWatchEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VideoWatchEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VideoWatchEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VideoWatchEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VideoWatchEventMaxAggregateInputType
}

export type GetVideoWatchEventAggregateType<T extends VideoWatchEventAggregateArgs> = {
      [P in keyof T & keyof AggregateVideoWatchEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideoWatchEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateVideoWatchEvent[P]>
}




export type VideoWatchEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoWatchEventWhereInput
  orderBy?: Prisma.VideoWatchEventOrderByWithAggregationInput | Prisma.VideoWatchEventOrderByWithAggregationInput[]
  by: Prisma.VideoWatchEventScalarFieldEnum[] | Prisma.VideoWatchEventScalarFieldEnum
  having?: Prisma.VideoWatchEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VideoWatchEventCountAggregateInputType | true
  _avg?: VideoWatchEventAvgAggregateInputType
  _sum?: VideoWatchEventSumAggregateInputType
  _min?: VideoWatchEventMinAggregateInputType
  _max?: VideoWatchEventMaxAggregateInputType
}

export type VideoWatchEventGroupByOutputType = {
  id: string
  userId: string
  courseId: string
  lessonId: string
  sessionId: string
  startedAt: Date
  endedAt: Date | null
  startPositionSeconds: number
  endPositionSeconds: number | null
  watchedSeconds: number
  completed: boolean
  createdAt: Date
  _count: VideoWatchEventCountAggregateOutputType | null
  _avg: VideoWatchEventAvgAggregateOutputType | null
  _sum: VideoWatchEventSumAggregateOutputType | null
  _min: VideoWatchEventMinAggregateOutputType | null
  _max: VideoWatchEventMaxAggregateOutputType | null
}

export type GetVideoWatchEventGroupByPayload<T extends VideoWatchEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoWatchEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VideoWatchEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VideoWatchEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VideoWatchEventGroupByOutputType[P]>
      }
    >
  >



export type VideoWatchEventWhereInput = {
  AND?: Prisma.VideoWatchEventWhereInput | Prisma.VideoWatchEventWhereInput[]
  OR?: Prisma.VideoWatchEventWhereInput[]
  NOT?: Prisma.VideoWatchEventWhereInput | Prisma.VideoWatchEventWhereInput[]
  id?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  userId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  courseId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  lessonId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  sessionId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  startedAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"VideoWatchEvent"> | Date | string | null
  startPositionSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  endPositionSeconds?: Prisma.IntNullableFilter<"VideoWatchEvent"> | number | null
  watchedSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  completed?: Prisma.BoolFilter<"VideoWatchEvent"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  lesson?: Prisma.XOR<Prisma.LessonScalarRelationFilter, Prisma.LessonWhereInput>
}

export type VideoWatchEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  course?: Prisma.CourseOrderByWithRelationInput
  lesson?: Prisma.LessonOrderByWithRelationInput
}

export type VideoWatchEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_sessionId_startedAt?: Prisma.VideoWatchEventUserIdSessionIdStartedAtCompoundUniqueInput
  AND?: Prisma.VideoWatchEventWhereInput | Prisma.VideoWatchEventWhereInput[]
  OR?: Prisma.VideoWatchEventWhereInput[]
  NOT?: Prisma.VideoWatchEventWhereInput | Prisma.VideoWatchEventWhereInput[]
  userId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  courseId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  lessonId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  sessionId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  startedAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"VideoWatchEvent"> | Date | string | null
  startPositionSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  endPositionSeconds?: Prisma.IntNullableFilter<"VideoWatchEvent"> | number | null
  watchedSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  completed?: Prisma.BoolFilter<"VideoWatchEvent"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  lesson?: Prisma.XOR<Prisma.LessonScalarRelationFilter, Prisma.LessonWhereInput>
}, "id" | "userId_sessionId_startedAt">

export type VideoWatchEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.VideoWatchEventCountOrderByAggregateInput
  _avg?: Prisma.VideoWatchEventAvgOrderByAggregateInput
  _max?: Prisma.VideoWatchEventMaxOrderByAggregateInput
  _min?: Prisma.VideoWatchEventMinOrderByAggregateInput
  _sum?: Prisma.VideoWatchEventSumOrderByAggregateInput
}

export type VideoWatchEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.VideoWatchEventScalarWhereWithAggregatesInput | Prisma.VideoWatchEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.VideoWatchEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VideoWatchEventScalarWhereWithAggregatesInput | Prisma.VideoWatchEventScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"VideoWatchEvent"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"VideoWatchEvent"> | string
  courseId?: Prisma.UuidWithAggregatesFilter<"VideoWatchEvent"> | string
  lessonId?: Prisma.UuidWithAggregatesFilter<"VideoWatchEvent"> | string
  sessionId?: Prisma.UuidWithAggregatesFilter<"VideoWatchEvent"> | string
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"VideoWatchEvent"> | Date | string
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"VideoWatchEvent"> | Date | string | null
  startPositionSeconds?: Prisma.IntWithAggregatesFilter<"VideoWatchEvent"> | number
  endPositionSeconds?: Prisma.IntNullableWithAggregatesFilter<"VideoWatchEvent"> | number | null
  watchedSeconds?: Prisma.IntWithAggregatesFilter<"VideoWatchEvent"> | number
  completed?: Prisma.BoolWithAggregatesFilter<"VideoWatchEvent"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VideoWatchEvent"> | Date | string
}

export type VideoWatchEventCreateInput = {
  id?: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVideoWatchEventsInput
  course: Prisma.CourseCreateNestedOneWithoutVideoWatchEventsInput
  lesson: Prisma.LessonCreateNestedOneWithoutVideoWatchEventsInput
}

export type VideoWatchEventUncheckedCreateInput = {
  id?: string
  userId: string
  courseId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVideoWatchEventsNestedInput
  course?: Prisma.CourseUpdateOneRequiredWithoutVideoWatchEventsNestedInput
  lesson?: Prisma.LessonUpdateOneRequiredWithoutVideoWatchEventsNestedInput
}

export type VideoWatchEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventCreateManyInput = {
  id?: string
  userId: string
  courseId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventListRelationFilter = {
  every?: Prisma.VideoWatchEventWhereInput
  some?: Prisma.VideoWatchEventWhereInput
  none?: Prisma.VideoWatchEventWhereInput
}

export type VideoWatchEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VideoWatchEventUserIdSessionIdStartedAtCompoundUniqueInput = {
  userId: string
  sessionId: string
  startedAt: Date | string
}

export type VideoWatchEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VideoWatchEventAvgOrderByAggregateInput = {
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
}

export type VideoWatchEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VideoWatchEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VideoWatchEventSumOrderByAggregateInput = {
  startPositionSeconds?: Prisma.SortOrder
  endPositionSeconds?: Prisma.SortOrder
  watchedSeconds?: Prisma.SortOrder
}

export type VideoWatchEventCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput> | Prisma.VideoWatchEventCreateWithoutUserInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutUserInput | Prisma.VideoWatchEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VideoWatchEventCreateManyUserInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput> | Prisma.VideoWatchEventCreateWithoutUserInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutUserInput | Prisma.VideoWatchEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VideoWatchEventCreateManyUserInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput> | Prisma.VideoWatchEventCreateWithoutUserInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutUserInput | Prisma.VideoWatchEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutUserInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VideoWatchEventCreateManyUserInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutUserInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutUserInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput> | Prisma.VideoWatchEventCreateWithoutUserInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutUserInput | Prisma.VideoWatchEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutUserInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VideoWatchEventCreateManyUserInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutUserInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutUserInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput> | Prisma.VideoWatchEventCreateWithoutCourseInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput | Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.VideoWatchEventCreateManyCourseInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput> | Prisma.VideoWatchEventCreateWithoutCourseInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput | Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.VideoWatchEventCreateManyCourseInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput> | Prisma.VideoWatchEventCreateWithoutCourseInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput | Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutCourseInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.VideoWatchEventCreateManyCourseInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutCourseInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutCourseInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput> | Prisma.VideoWatchEventCreateWithoutCourseInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput | Prisma.VideoWatchEventCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutCourseInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.VideoWatchEventCreateManyCourseInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutCourseInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutCourseInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput> | Prisma.VideoWatchEventCreateWithoutLessonInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput | Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.VideoWatchEventCreateManyLessonInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUncheckedCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput> | Prisma.VideoWatchEventCreateWithoutLessonInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput | Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.VideoWatchEventCreateManyLessonInputEnvelope
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
}

export type VideoWatchEventUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput> | Prisma.VideoWatchEventCreateWithoutLessonInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput | Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutLessonInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.VideoWatchEventCreateManyLessonInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutLessonInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutLessonInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventUncheckedUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput> | Prisma.VideoWatchEventCreateWithoutLessonInput[] | Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput | Prisma.VideoWatchEventCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutLessonInput | Prisma.VideoWatchEventUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.VideoWatchEventCreateManyLessonInputEnvelope
  set?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  disconnect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  delete?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  connect?: Prisma.VideoWatchEventWhereUniqueInput | Prisma.VideoWatchEventWhereUniqueInput[]
  update?: Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutLessonInput | Prisma.VideoWatchEventUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.VideoWatchEventUpdateManyWithWhereWithoutLessonInput | Prisma.VideoWatchEventUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
}

export type VideoWatchEventCreateWithoutUserInput = {
  id?: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
  course: Prisma.CourseCreateNestedOneWithoutVideoWatchEventsInput
  lesson: Prisma.LessonCreateNestedOneWithoutVideoWatchEventsInput
}

export type VideoWatchEventUncheckedCreateWithoutUserInput = {
  id?: string
  courseId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventCreateOrConnectWithoutUserInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput>
}

export type VideoWatchEventCreateManyUserInputEnvelope = {
  data: Prisma.VideoWatchEventCreateManyUserInput | Prisma.VideoWatchEventCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type VideoWatchEventUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutUserInput, Prisma.VideoWatchEventUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutUserInput, Prisma.VideoWatchEventUncheckedCreateWithoutUserInput>
}

export type VideoWatchEventUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutUserInput, Prisma.VideoWatchEventUncheckedUpdateWithoutUserInput>
}

export type VideoWatchEventUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.VideoWatchEventScalarWhereInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateManyMutationInput, Prisma.VideoWatchEventUncheckedUpdateManyWithoutUserInput>
}

export type VideoWatchEventScalarWhereInput = {
  AND?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
  OR?: Prisma.VideoWatchEventScalarWhereInput[]
  NOT?: Prisma.VideoWatchEventScalarWhereInput | Prisma.VideoWatchEventScalarWhereInput[]
  id?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  userId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  courseId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  lessonId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  sessionId?: Prisma.UuidFilter<"VideoWatchEvent"> | string
  startedAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"VideoWatchEvent"> | Date | string | null
  startPositionSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  endPositionSeconds?: Prisma.IntNullableFilter<"VideoWatchEvent"> | number | null
  watchedSeconds?: Prisma.IntFilter<"VideoWatchEvent"> | number
  completed?: Prisma.BoolFilter<"VideoWatchEvent"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VideoWatchEvent"> | Date | string
}

export type VideoWatchEventCreateWithoutCourseInput = {
  id?: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVideoWatchEventsInput
  lesson: Prisma.LessonCreateNestedOneWithoutVideoWatchEventsInput
}

export type VideoWatchEventUncheckedCreateWithoutCourseInput = {
  id?: string
  userId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventCreateOrConnectWithoutCourseInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput>
}

export type VideoWatchEventCreateManyCourseInputEnvelope = {
  data: Prisma.VideoWatchEventCreateManyCourseInput | Prisma.VideoWatchEventCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type VideoWatchEventUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutCourseInput, Prisma.VideoWatchEventUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutCourseInput, Prisma.VideoWatchEventUncheckedCreateWithoutCourseInput>
}

export type VideoWatchEventUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutCourseInput, Prisma.VideoWatchEventUncheckedUpdateWithoutCourseInput>
}

export type VideoWatchEventUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.VideoWatchEventScalarWhereInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateManyMutationInput, Prisma.VideoWatchEventUncheckedUpdateManyWithoutCourseInput>
}

export type VideoWatchEventCreateWithoutLessonInput = {
  id?: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVideoWatchEventsInput
  course: Prisma.CourseCreateNestedOneWithoutVideoWatchEventsInput
}

export type VideoWatchEventUncheckedCreateWithoutLessonInput = {
  id?: string
  userId: string
  courseId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventCreateOrConnectWithoutLessonInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput>
}

export type VideoWatchEventCreateManyLessonInputEnvelope = {
  data: Prisma.VideoWatchEventCreateManyLessonInput | Prisma.VideoWatchEventCreateManyLessonInput[]
  skipDuplicates?: boolean
}

export type VideoWatchEventUpsertWithWhereUniqueWithoutLessonInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutLessonInput, Prisma.VideoWatchEventUncheckedUpdateWithoutLessonInput>
  create: Prisma.XOR<Prisma.VideoWatchEventCreateWithoutLessonInput, Prisma.VideoWatchEventUncheckedCreateWithoutLessonInput>
}

export type VideoWatchEventUpdateWithWhereUniqueWithoutLessonInput = {
  where: Prisma.VideoWatchEventWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateWithoutLessonInput, Prisma.VideoWatchEventUncheckedUpdateWithoutLessonInput>
}

export type VideoWatchEventUpdateManyWithWhereWithoutLessonInput = {
  where: Prisma.VideoWatchEventScalarWhereInput
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateManyMutationInput, Prisma.VideoWatchEventUncheckedUpdateManyWithoutLessonInput>
}

export type VideoWatchEventCreateManyUserInput = {
  id?: string
  courseId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  course?: Prisma.CourseUpdateOneRequiredWithoutVideoWatchEventsNestedInput
  lesson?: Prisma.LessonUpdateOneRequiredWithoutVideoWatchEventsNestedInput
}

export type VideoWatchEventUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventCreateManyCourseInput = {
  id?: string
  userId: string
  lessonId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventUpdateWithoutCourseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVideoWatchEventsNestedInput
  lesson?: Prisma.LessonUpdateOneRequiredWithoutVideoWatchEventsNestedInput
}

export type VideoWatchEventUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventUncheckedUpdateManyWithoutCourseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventCreateManyLessonInput = {
  id?: string
  userId: string
  courseId: string
  sessionId: string
  startedAt: Date | string
  endedAt?: Date | string | null
  startPositionSeconds: number
  endPositionSeconds?: number | null
  watchedSeconds: number
  completed?: boolean
  createdAt?: Date | string
}

export type VideoWatchEventUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVideoWatchEventsNestedInput
  course?: Prisma.CourseUpdateOneRequiredWithoutVideoWatchEventsNestedInput
}

export type VideoWatchEventUncheckedUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoWatchEventUncheckedUpdateManyWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  startPositionSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  endPositionSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  watchedSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type VideoWatchEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  lessonId?: boolean
  sessionId?: boolean
  startedAt?: boolean
  endedAt?: boolean
  startPositionSeconds?: boolean
  endPositionSeconds?: boolean
  watchedSeconds?: boolean
  completed?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoWatchEvent"]>

export type VideoWatchEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  lessonId?: boolean
  sessionId?: boolean
  startedAt?: boolean
  endedAt?: boolean
  startPositionSeconds?: boolean
  endPositionSeconds?: boolean
  watchedSeconds?: boolean
  completed?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoWatchEvent"]>

export type VideoWatchEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  lessonId?: boolean
  sessionId?: boolean
  startedAt?: boolean
  endedAt?: boolean
  startPositionSeconds?: boolean
  endPositionSeconds?: boolean
  watchedSeconds?: boolean
  completed?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoWatchEvent"]>

export type VideoWatchEventSelectScalar = {
  id?: boolean
  userId?: boolean
  courseId?: boolean
  lessonId?: boolean
  sessionId?: boolean
  startedAt?: boolean
  endedAt?: boolean
  startPositionSeconds?: boolean
  endPositionSeconds?: boolean
  watchedSeconds?: boolean
  completed?: boolean
  createdAt?: boolean
}

export type VideoWatchEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "courseId" | "lessonId" | "sessionId" | "startedAt" | "endedAt" | "startPositionSeconds" | "endPositionSeconds" | "watchedSeconds" | "completed" | "createdAt", ExtArgs["result"]["videoWatchEvent"]>
export type VideoWatchEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}
export type VideoWatchEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}
export type VideoWatchEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.LessonDefaultArgs<ExtArgs>
}

export type $VideoWatchEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VideoWatchEvent"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    course: Prisma.$CoursePayload<ExtArgs>
    lesson: Prisma.$LessonPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    courseId: string
    lessonId: string
    sessionId: string
    startedAt: Date
    endedAt: Date | null
    startPositionSeconds: number
    endPositionSeconds: number | null
    watchedSeconds: number
    completed: boolean
    createdAt: Date
  }, ExtArgs["result"]["videoWatchEvent"]>
  composites: {}
}

export type VideoWatchEventGetPayload<S extends boolean | null | undefined | VideoWatchEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload, S>

export type VideoWatchEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VideoWatchEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VideoWatchEventCountAggregateInputType | true
  }

export interface VideoWatchEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VideoWatchEvent'], meta: { name: 'VideoWatchEvent' } }
  /**
   * Find zero or one VideoWatchEvent that matches the filter.
   * @param {VideoWatchEventFindUniqueArgs} args - Arguments to find a VideoWatchEvent
   * @example
   * // Get one VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoWatchEventFindUniqueArgs>(args: Prisma.SelectSubset<T, VideoWatchEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VideoWatchEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoWatchEventFindUniqueOrThrowArgs} args - Arguments to find a VideoWatchEvent
   * @example
   * // Get one VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoWatchEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VideoWatchEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoWatchEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventFindFirstArgs} args - Arguments to find a VideoWatchEvent
   * @example
   * // Get one VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoWatchEventFindFirstArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoWatchEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventFindFirstOrThrowArgs} args - Arguments to find a VideoWatchEvent
   * @example
   * // Get one VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoWatchEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VideoWatchEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VideoWatchEvents
   * const videoWatchEvents = await prisma.videoWatchEvent.findMany()
   * 
   * // Get first 10 VideoWatchEvents
   * const videoWatchEvents = await prisma.videoWatchEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const videoWatchEventWithIdOnly = await prisma.videoWatchEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VideoWatchEventFindManyArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VideoWatchEvent.
   * @param {VideoWatchEventCreateArgs} args - Arguments to create a VideoWatchEvent.
   * @example
   * // Create one VideoWatchEvent
   * const VideoWatchEvent = await prisma.videoWatchEvent.create({
   *   data: {
   *     // ... data to create a VideoWatchEvent
   *   }
   * })
   * 
   */
  create<T extends VideoWatchEventCreateArgs>(args: Prisma.SelectSubset<T, VideoWatchEventCreateArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VideoWatchEvents.
   * @param {VideoWatchEventCreateManyArgs} args - Arguments to create many VideoWatchEvents.
   * @example
   * // Create many VideoWatchEvents
   * const videoWatchEvent = await prisma.videoWatchEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VideoWatchEventCreateManyArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VideoWatchEvents and returns the data saved in the database.
   * @param {VideoWatchEventCreateManyAndReturnArgs} args - Arguments to create many VideoWatchEvents.
   * @example
   * // Create many VideoWatchEvents
   * const videoWatchEvent = await prisma.videoWatchEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VideoWatchEvents and only return the `id`
   * const videoWatchEventWithIdOnly = await prisma.videoWatchEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VideoWatchEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VideoWatchEvent.
   * @param {VideoWatchEventDeleteArgs} args - Arguments to delete one VideoWatchEvent.
   * @example
   * // Delete one VideoWatchEvent
   * const VideoWatchEvent = await prisma.videoWatchEvent.delete({
   *   where: {
   *     // ... filter to delete one VideoWatchEvent
   *   }
   * })
   * 
   */
  delete<T extends VideoWatchEventDeleteArgs>(args: Prisma.SelectSubset<T, VideoWatchEventDeleteArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VideoWatchEvent.
   * @param {VideoWatchEventUpdateArgs} args - Arguments to update one VideoWatchEvent.
   * @example
   * // Update one VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VideoWatchEventUpdateArgs>(args: Prisma.SelectSubset<T, VideoWatchEventUpdateArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VideoWatchEvents.
   * @param {VideoWatchEventDeleteManyArgs} args - Arguments to filter VideoWatchEvents to delete.
   * @example
   * // Delete a few VideoWatchEvents
   * const { count } = await prisma.videoWatchEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VideoWatchEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, VideoWatchEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoWatchEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VideoWatchEvents
   * const videoWatchEvent = await prisma.videoWatchEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VideoWatchEventUpdateManyArgs>(args: Prisma.SelectSubset<T, VideoWatchEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoWatchEvents and returns the data updated in the database.
   * @param {VideoWatchEventUpdateManyAndReturnArgs} args - Arguments to update many VideoWatchEvents.
   * @example
   * // Update many VideoWatchEvents
   * const videoWatchEvent = await prisma.videoWatchEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VideoWatchEvents and only return the `id`
   * const videoWatchEventWithIdOnly = await prisma.videoWatchEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VideoWatchEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VideoWatchEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VideoWatchEvent.
   * @param {VideoWatchEventUpsertArgs} args - Arguments to update or create a VideoWatchEvent.
   * @example
   * // Update or create a VideoWatchEvent
   * const videoWatchEvent = await prisma.videoWatchEvent.upsert({
   *   create: {
   *     // ... data to create a VideoWatchEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VideoWatchEvent we want to update
   *   }
   * })
   */
  upsert<T extends VideoWatchEventUpsertArgs>(args: Prisma.SelectSubset<T, VideoWatchEventUpsertArgs<ExtArgs>>): Prisma.Prisma__VideoWatchEventClient<runtime.Types.Result.GetResult<Prisma.$VideoWatchEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VideoWatchEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventCountArgs} args - Arguments to filter VideoWatchEvents to count.
   * @example
   * // Count the number of VideoWatchEvents
   * const count = await prisma.videoWatchEvent.count({
   *   where: {
   *     // ... the filter for the VideoWatchEvents we want to count
   *   }
   * })
  **/
  count<T extends VideoWatchEventCountArgs>(
    args?: Prisma.Subset<T, VideoWatchEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VideoWatchEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VideoWatchEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VideoWatchEventAggregateArgs>(args: Prisma.Subset<T, VideoWatchEventAggregateArgs>): Prisma.PrismaPromise<GetVideoWatchEventAggregateType<T>>

  /**
   * Group by VideoWatchEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoWatchEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VideoWatchEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoWatchEventGroupByArgs['orderBy'] }
      : { orderBy?: VideoWatchEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VideoWatchEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideoWatchEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VideoWatchEvent model
 */
readonly fields: VideoWatchEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VideoWatchEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoWatchEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  course<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  lesson<T extends Prisma.LessonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LessonDefaultArgs<ExtArgs>>): Prisma.Prisma__LessonClient<runtime.Types.Result.GetResult<Prisma.$LessonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VideoWatchEvent model
 */
export interface VideoWatchEventFieldRefs {
  readonly id: Prisma.FieldRef<"VideoWatchEvent", 'String'>
  readonly userId: Prisma.FieldRef<"VideoWatchEvent", 'String'>
  readonly courseId: Prisma.FieldRef<"VideoWatchEvent", 'String'>
  readonly lessonId: Prisma.FieldRef<"VideoWatchEvent", 'String'>
  readonly sessionId: Prisma.FieldRef<"VideoWatchEvent", 'String'>
  readonly startedAt: Prisma.FieldRef<"VideoWatchEvent", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"VideoWatchEvent", 'DateTime'>
  readonly startPositionSeconds: Prisma.FieldRef<"VideoWatchEvent", 'Int'>
  readonly endPositionSeconds: Prisma.FieldRef<"VideoWatchEvent", 'Int'>
  readonly watchedSeconds: Prisma.FieldRef<"VideoWatchEvent", 'Int'>
  readonly completed: Prisma.FieldRef<"VideoWatchEvent", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"VideoWatchEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VideoWatchEvent findUnique
 */
export type VideoWatchEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter, which VideoWatchEvent to fetch.
   */
  where: Prisma.VideoWatchEventWhereUniqueInput
}

/**
 * VideoWatchEvent findUniqueOrThrow
 */
export type VideoWatchEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter, which VideoWatchEvent to fetch.
   */
  where: Prisma.VideoWatchEventWhereUniqueInput
}

/**
 * VideoWatchEvent findFirst
 */
export type VideoWatchEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter, which VideoWatchEvent to fetch.
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoWatchEvents to fetch.
   */
  orderBy?: Prisma.VideoWatchEventOrderByWithRelationInput | Prisma.VideoWatchEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoWatchEvents.
   */
  cursor?: Prisma.VideoWatchEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoWatchEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoWatchEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoWatchEvents.
   */
  distinct?: Prisma.VideoWatchEventScalarFieldEnum | Prisma.VideoWatchEventScalarFieldEnum[]
}

/**
 * VideoWatchEvent findFirstOrThrow
 */
export type VideoWatchEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter, which VideoWatchEvent to fetch.
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoWatchEvents to fetch.
   */
  orderBy?: Prisma.VideoWatchEventOrderByWithRelationInput | Prisma.VideoWatchEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoWatchEvents.
   */
  cursor?: Prisma.VideoWatchEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoWatchEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoWatchEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoWatchEvents.
   */
  distinct?: Prisma.VideoWatchEventScalarFieldEnum | Prisma.VideoWatchEventScalarFieldEnum[]
}

/**
 * VideoWatchEvent findMany
 */
export type VideoWatchEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter, which VideoWatchEvents to fetch.
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoWatchEvents to fetch.
   */
  orderBy?: Prisma.VideoWatchEventOrderByWithRelationInput | Prisma.VideoWatchEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VideoWatchEvents.
   */
  cursor?: Prisma.VideoWatchEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoWatchEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoWatchEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoWatchEvents.
   */
  distinct?: Prisma.VideoWatchEventScalarFieldEnum | Prisma.VideoWatchEventScalarFieldEnum[]
}

/**
 * VideoWatchEvent create
 */
export type VideoWatchEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * The data needed to create a VideoWatchEvent.
   */
  data: Prisma.XOR<Prisma.VideoWatchEventCreateInput, Prisma.VideoWatchEventUncheckedCreateInput>
}

/**
 * VideoWatchEvent createMany
 */
export type VideoWatchEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VideoWatchEvents.
   */
  data: Prisma.VideoWatchEventCreateManyInput | Prisma.VideoWatchEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VideoWatchEvent createManyAndReturn
 */
export type VideoWatchEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * The data used to create many VideoWatchEvents.
   */
  data: Prisma.VideoWatchEventCreateManyInput | Prisma.VideoWatchEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VideoWatchEvent update
 */
export type VideoWatchEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * The data needed to update a VideoWatchEvent.
   */
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateInput, Prisma.VideoWatchEventUncheckedUpdateInput>
  /**
   * Choose, which VideoWatchEvent to update.
   */
  where: Prisma.VideoWatchEventWhereUniqueInput
}

/**
 * VideoWatchEvent updateMany
 */
export type VideoWatchEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VideoWatchEvents.
   */
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateManyMutationInput, Prisma.VideoWatchEventUncheckedUpdateManyInput>
  /**
   * Filter which VideoWatchEvents to update
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * Limit how many VideoWatchEvents to update.
   */
  limit?: number
}

/**
 * VideoWatchEvent updateManyAndReturn
 */
export type VideoWatchEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * The data used to update VideoWatchEvents.
   */
  data: Prisma.XOR<Prisma.VideoWatchEventUpdateManyMutationInput, Prisma.VideoWatchEventUncheckedUpdateManyInput>
  /**
   * Filter which VideoWatchEvents to update
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * Limit how many VideoWatchEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VideoWatchEvent upsert
 */
export type VideoWatchEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * The filter to search for the VideoWatchEvent to update in case it exists.
   */
  where: Prisma.VideoWatchEventWhereUniqueInput
  /**
   * In case the VideoWatchEvent found by the `where` argument doesn't exist, create a new VideoWatchEvent with this data.
   */
  create: Prisma.XOR<Prisma.VideoWatchEventCreateInput, Prisma.VideoWatchEventUncheckedCreateInput>
  /**
   * In case the VideoWatchEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoWatchEventUpdateInput, Prisma.VideoWatchEventUncheckedUpdateInput>
}

/**
 * VideoWatchEvent delete
 */
export type VideoWatchEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
  /**
   * Filter which VideoWatchEvent to delete.
   */
  where: Prisma.VideoWatchEventWhereUniqueInput
}

/**
 * VideoWatchEvent deleteMany
 */
export type VideoWatchEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoWatchEvents to delete
   */
  where?: Prisma.VideoWatchEventWhereInput
  /**
   * Limit how many VideoWatchEvents to delete.
   */
  limit?: number
}

/**
 * VideoWatchEvent without action
 */
export type VideoWatchEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoWatchEvent
   */
  select?: Prisma.VideoWatchEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoWatchEvent
   */
  omit?: Prisma.VideoWatchEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoWatchEventInclude<ExtArgs> | null
}
