import { allocateDiscount, calculateEarning, toVnd, vndNumber } from "../../common/utils/money.js";
import { prisma } from "../../config/database.js";
import { env } from "../../config/env.js";
import type { RevenueQuery } from "./earning.types.js";

export function buildEarningRows(order: { id: string; discount: unknown; currency: string; items: Array<{ id: string; courseId: string; priceSnapshot: unknown; course: { instructorId: string } }> }, paymentId: string, paidAt: Date) {
  const prices = order.items.map(item => toVnd(item.priceSnapshot, "price snapshot"));
  const discounts = allocateDiscount(prices, toVnd(order.discount, "order discount"));
  const availableAt = new Date(paidAt.getTime() + env.commerceRefundWindowDays * 86_400_000);
  return order.items.map((item, index) => { const gross = prices[index]! - discounts[index]!; const earning = calculateEarning(gross, env.commercePlatformFeePercent); return { instructorId: item.course.instructorId, courseId: item.courseId, orderId: order.id, orderItemId: item.id, paymentId, ...earning, platformFeeRate: env.commercePlatformFeePercent, currency: order.currency, availableAt }; });
}

export async function releasePendingEarnings(now = new Date()) { return prisma.instructorEarning.updateMany({ where: { status: "PENDING", availableAt: { lte: now } }, data: { status: "AVAILABLE" } }); }
const amount = (value: unknown) => Number(value ?? 0);
const dateWhere = (query: RevenueQuery) => ({ gte: query.fromDate, lt: query.toExclusive });
export async function overview(instructorId: string, query: RevenueQuery) {
  await releasePendingEarnings(); const rows = await prisma.instructorEarning.findMany({ where: { instructorId, createdAt: dateWhere(query) }, select: { grossAmount: true, platformFeeAmount: true, netAmount: true, status: true } });
  const sum = (key: "grossAmount" | "platformFeeAmount" | "netAmount", status?: string) => vndNumber(rows.filter(row => !status || row.status === status).reduce((total, row) => total + toVnd(row[key], key), 0n));
  return { data: { grossRevenue: sum("grossAmount"), platformFees: sum("platformFeeAmount"), netRevenue: sum("netAmount"), pendingBalance: sum("netAmount", "PENDING"), availableBalance: sum("netAmount", "AVAILABLE"), paidAmount: sum("netAmount", "PAID"), reversedAmount: sum("netAmount", "REVERSED"), currency: "VND" }, meta: { from: query.from, to: query.to, timezone: "Asia/Ho_Chi_Minh" } };
}
export async function earnings(instructorId: string, query: RevenueQuery) { await releasePendingEarnings(); const where = { instructorId, createdAt: dateWhere(query), ...(query.status ? { status: query.status } : {}) }; const [rows, total] = await Promise.all([prisma.instructorEarning.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit, include: { course: { select: { id: true, title: true, slug: true } }, order: { select: { id: true, orderNumber: true } } } }), prisma.instructorEarning.count({ where })]); return { data: rows.map(row => ({ ...row, grossAmount: amount(row.grossAmount), platformFeeRate: amount(row.platformFeeRate), platformFeeAmount: amount(row.platformFeeAmount), netAmount: amount(row.netAmount) })), meta: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
export async function revenueByCourse(instructorId: string, query: RevenueQuery) { const rows = await prisma.instructorEarning.findMany({ where: { instructorId, createdAt: dateWhere(query) }, include: { course: { select: { id: true, title: true } } } }); const grouped = new Map<string, { courseId: string; title: string; successfulOrders: number; refundCount: number; grossRevenue: bigint; platformFees: bigint; netRevenue: bigint; currency: string }>(); for (const row of rows) { const value = grouped.get(row.courseId) ?? { courseId: row.courseId, title: row.course.title, successfulOrders: 0, refundCount: 0, grossRevenue: 0n, platformFees: 0n, netRevenue: 0n, currency: row.currency }; value.successfulOrders += 1; if (row.status === "REVERSED") value.refundCount += 1; value.grossRevenue += toVnd(row.grossAmount); value.platformFees += toVnd(row.platformFeeAmount); value.netRevenue += toVnd(row.netAmount); grouped.set(row.courseId, value); } return [...grouped.values()].sort((a, b) => a.netRevenue === b.netRevenue ? 0 : a.netRevenue > b.netRevenue ? -1 : 1).map(row => ({ ...row, grossRevenue: vndNumber(row.grossRevenue), platformFees: vndNumber(row.platformFees), netRevenue: vndNumber(row.netRevenue) })); }
export async function instructorPayouts(instructorId: string, query: RevenueQuery) { const [rows, total] = await Promise.all([prisma.payout.findMany({ where: { instructorId, createdAt: dateWhere(query) }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit, include: { _count: { select: { earnings: true } } } }), prisma.payout.count({ where: { instructorId, createdAt: dateWhere(query) } })]); return { data: rows.map(row => ({ ...row, amount: amount(row.amount) })), meta: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
