<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import BaseInput from '@/components/ui/BaseInput.vue'
import { useApi } from '@/composables/useApi'
import type { ApiResponse, Certificate } from '@/types'
const route = useRoute(), router = useRouter(), api = useApi(), code = ref(String(route.params.code || '')), certificate = ref<(Certificate & { isValid?: boolean }) | null>(null), error = ref(''), searched = ref(false)
async function verify() { if (!code.value.trim()) return; error.value = ''; searched.value = true; try { const response = await api.get<ApiResponse<Certificate & { isValid?: boolean }>>(`/certificates/verify/${encodeURIComponent(code.value.trim())}`); certificate.value = response.data || null; if (route.params.code !== code.value.trim()) await router.replace(`/certificates/verify/${encodeURIComponent(code.value.trim())}`) } catch (cause) { certificate.value = null; error.value = cause instanceof Error ? cause.message : 'Không tìm thấy chứng chỉ' } }
onMounted(() => { if (code.value) void verify() })
</script>

<template><DefaultLayout><main><section class="verify-hero"><div class="app-page max-w-3xl px-4 py-14 text-center text-white sm:px-6 sm:py-20"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-white/25 bg-white/10 text-2xl">✓</span><h1 class="mt-5 text-3xl font-black tracking-tight sm:text-5xl">Xác minh chứng chỉ</h1><p class="mx-auto mt-3 max-w-xl text-sm leading-6 text-purple-100 sm:text-base">Kiểm tra tính xác thực của chứng chỉ do LMS Platform phát hành bằng mã xác minh.</p><form class="mx-auto mt-8 flex max-w-xl flex-col gap-3 rounded-2xl bg-white p-3 shadow-2xl sm:flex-row" @submit.prevent="verify"><BaseInput id="certificate-code" v-model="code" class="min-w-0 flex-1 text-left" placeholder="Nhập mã xác minh"/><BaseButton type="submit" size="lg" :loading="api.loading.value">Xác minh</BaseButton></form></div></section><section class="app-page max-w-3xl px-4 py-10 sm:px-6"><p v-if="error" class="rounded-2xl border border-red-200 bg-red-50 p-5 text-center text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300"><b>Không xác minh được chứng chỉ.</b><br><span class="text-sm">{{ error }}</span></p><article v-if="certificate" :class="['verification-card', certificate.revokedAt ? 'verification-card--revoked' : 'verification-card--valid']"><span class="verification-mark">{{ certificate.revokedAt ? '×' : '✓' }}</span><p class="text-xs font-black uppercase tracking-[.18em]">{{ certificate.revokedAt ? 'Certificate revoked' : 'Verified certificate' }}</p><h2 class="mt-3 text-3xl font-black">{{ certificate.revokedAt ? 'Chứng chỉ đã bị thu hồi' : 'Chứng chỉ hợp lệ' }}</h2><p class="mt-2 text-sm opacity-75">Thông tin được đối chiếu trực tiếp từ hệ thống LMS Platform.</p><div class="mt-7 rounded-2xl bg-white/65 p-6 text-left text-slate-900 dark:bg-slate-950/40 dark:text-white"><p class="text-xs font-bold uppercase tracking-wider opacity-50">Khóa học</p><h3 class="mt-2 text-xl font-extrabold">{{ certificate.courseTitleSnapshot }}</h3><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="opacity-55">Học viên</dt><dd class="mt-1 font-bold">{{ certificate.studentNameSnapshot }}</dd></div><div><dt class="opacity-55">Giảng viên</dt><dd class="mt-1 font-bold">{{ certificate.instructorNameSnapshot }}</dd></div><div><dt class="opacity-55">Mã chứng chỉ</dt><dd class="mt-1 font-mono font-bold">{{ certificate.certificateNumber }}</dd></div><div><dt class="opacity-55">Ngày cấp</dt><dd class="mt-1 font-bold">{{ new Date(certificate.issuedAt).toLocaleDateString('vi-VN') }}</dd></div></dl></div></article><div v-else-if="!searched" class="py-8 text-center text-sm text-slate-500">Mã xác minh thường nằm ở cuối chứng chỉ của bạn.</div></section></main></DefaultLayout></template>

<style scoped>.verify-hero{background:radial-gradient(circle at 15% 0,rgba(236,72,153,.5),transparent 30%),linear-gradient(125deg,#312e81,#6d28d9 55%,#9333ea)}.verification-card{position:relative;overflow:hidden;border-radius:1.75rem;padding:2.25rem;text-align:center;box-shadow:var(--shadow-md)}.verification-card--valid{border:1px solid #a7f3d0;background:linear-gradient(135deg,#ecfdf5,#d1fae5);color:#065f46}.verification-card--revoked{border:1px solid #fecaca;background:linear-gradient(135deg,#fef2f2,#fee2e2);color:#991b1b}.verification-mark{display:grid;width:4.5rem;height:4.5rem;margin:0 auto 1.25rem;place-items:center;border:2px solid currentColor;border-radius:50%;font-size:2rem;font-weight:900}:global(.dark) .verification-card--valid{border-color:#065f46;background:linear-gradient(135deg,#052e24,#064e3b);color:#a7f3d0}:global(.dark) .verification-card--revoked{border-color:#7f1d1d;background:linear-gradient(135deg,#450a0a,#7f1d1d);color:#fecaca}</style>
