import { randomBytes } from "node:crypto"; import { AppError } from "../../common/errors/AppError.js"; import { prisma } from "../../config/database.js"; import { safelyRunCommunication } from "../../services/communication/communication.service.js"; import { UUID } from "../interactions/access.js"; import { createNotification } from "../notifications/notification.service.js";
const select = { id: true, certificateNumber: true, verificationCode: true, enrollmentId: true, studentId: true, courseId: true, studentNameSnapshot: true, courseTitleSnapshot: true, instructorNameSnapshot: true, issuedAt: true, revokedAt: true };
const certNumber = () => `LMS-${new Date().getUTCFullYear()}-${randomBytes(6).toString("hex").toUpperCase()}`;
export async function issueCertificate(courseId: string, studentId: string) {
  if (!UUID.test(courseId)) throw new AppError(404, "Course not found");
  const existing = await prisma.certificate.findUnique({ where: { studentId_courseId: { studentId, courseId } }, select }); if (existing) return existing;
  const enrollment = await prisma.enrollment.findUnique({ where: { studentId_courseId: { studentId, courseId } }, include: { student: { select: { fullName: true } }, course: { select: { title: true, instructor: { select: { fullName: true } } } } } });
  if (!enrollment) throw new AppError(403, "Course enrollment is required");
  const progress = Number(enrollment.progressPercent); if (enrollment.status !== "COMPLETED" || progress < 100) throw new AppError(409, "Complete all required lessons before requesting a certificate", { progressPercent: progress });
  const quizzes = await prisma.quiz.findMany({ where: { isPublished: true, OR: [{ section: { courseId } }, { lesson: { section: { courseId } } }] }, select: { id: true, attempts: { where: { studentId, status: "SUBMITTED", passed: true }, select: { id: true }, take: 1 } } });
  const passed = quizzes.filter(quiz => quiz.attempts.length > 0).length; if (passed !== quizzes.length) throw new AppError(409, "Pass every published quiz before requesting a certificate", { totalQuizzes: quizzes.length, passedQuizzes: passed });
  const certificate = await prisma.certificate.create({ data: { certificateNumber: certNumber(), verificationCode: randomBytes(24).toString("hex"), enrollmentId: enrollment.id, studentId, courseId, studentNameSnapshot: enrollment.student.fullName, courseTitleSnapshot: enrollment.course.title, instructorNameSnapshot: enrollment.course.instructor.fullName }, select });
  await safelyRunCommunication(() => createNotification({ userId: studentId, type: "CERTIFICATE_ISSUED", title: "Chứng chỉ đã được phát hành", message: enrollment.course.title, data: { url: `/certificates/${certificate.id}`, certificateId: certificate.id, courseId } }));
  return certificate;
}
export async function listMyCertificates(studentId: string) { return prisma.certificate.findMany({ where: { studentId }, orderBy: { issuedAt: "desc" }, select }); }
export async function getCertificate(certificateId: string, userId: string, admin = false) { if (!UUID.test(certificateId)) throw new AppError(404, "Certificate not found"); const item = await prisma.certificate.findUnique({ where: { id: certificateId }, select }); if (!item || (!admin && item.studentId !== userId)) throw new AppError(404, "Certificate not found"); return item; }
export async function verifyCertificate(code: string) { const normalized = code.trim(); if (!normalized) throw new AppError(404, "Certificate not found"); const item = await prisma.certificate.findFirst({ where: { OR: [{ certificateNumber: normalized.toUpperCase() }, { verificationCode: normalized.toLowerCase() }] }, select: { certificateNumber: true, studentNameSnapshot: true, courseTitleSnapshot: true, instructorNameSnapshot: true, issuedAt: true, revokedAt: true } }); if (!item) throw new AppError(404, "Certificate not found"); return { valid: item.revokedAt === null, certificate: item }; }
export async function revokeCertificate(certificateId: string) { if (!UUID.test(certificateId)) throw new AppError(404, "Certificate not found"); try { return await prisma.certificate.update({ where: { id: certificateId }, data: { revokedAt: new Date() }, select }); } catch { throw new AppError(404, "Certificate not found"); } }
