<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import InstructorLayout from '@/layouts/InstructorLayout.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import BaseInput from '@/components/ui/BaseInput.vue'
import BaseTextarea from '@/components/ui/BaseTextarea.vue'
import BaseModal from '@/components/ui/BaseModal.vue'
import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'
import { useApi } from '@/composables/useApi'
import type { ApiResponse, Assignment, CourseGradeRule } from '@/types'

const route = useRoute(), api = useApi(), courseId = String(route.params.courseId)
const items = ref<Assignment[]>([]), rule = ref<CourseGradeRule>({ courseId, assignmentWeight:60, quizWeight:40, passingScore:70 })
const error = ref(''), message = ref(''), showForm = ref(false), editingId = ref(''), saving = ref(false)
const title = ref(''), description = ref(''), instructions = ref(''), dueAt = ref(''), maxScore = ref('100'), allowResubmission = ref(false), maxSubmissions = ref('1'), allowLateSubmissions = ref(false), isPublished = ref(false)
const localDate = (date:string) => { const value=new Date(date); return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16) }
const formatDate = (date:string) => new Date(date).toLocaleString('vi-VN')
function resetForm(){ editingId.value='';title.value='';description.value='';instructions.value='';dueAt.value=localDate(new Date(Date.now()+86400000).toISOString());maxScore.value='100';allowResubmission.value=false;maxSubmissions.value='1';allowLateSubmissions.value=false;isPublished.value=false }
function create(){ resetForm(); showForm.value=true }
function edit(item:Assignment){ editingId.value=item.id;title.value=item.title;description.value=item.description||'';instructions.value=item.instructions||'';dueAt.value=localDate(item.dueAt);maxScore.value=String(item.maxScore);allowResubmission.value=item.allowResubmission;maxSubmissions.value=String(item.maxSubmissions);allowLateSubmissions.value=item.allowLateSubmissions;isPublished.value=item.isPublished;showForm.value=true }
async function load(){ error.value='';try{const [assignments,gradeRule]=await Promise.all([api.get<ApiResponse<Assignment[]>>(`/courses/${courseId}/assignments`),api.get<ApiResponse<CourseGradeRule>>(`/courses/${courseId}/grades/rule`)]);items.value=assignments.data||[];if(gradeRule.data)rule.value=gradeRule.data}catch(cause){error.value=cause instanceof Error?cause.message:'Không thể tải bài tập'} }
async function save(){ saving.value=true;error.value='';try{const body={title:title.value.trim(),description:description.value.trim()||null,instructions:instructions.value.trim()||null,dueAt:new Date(dueAt.value).toISOString(),maxScore:Number(maxScore.value),allowResubmission:allowResubmission.value,maxSubmissions:allowResubmission.value?Number(maxSubmissions.value):1,allowLateSubmissions:allowLateSubmissions.value,isPublished:isPublished.value};if(editingId.value)await api.patch(`/assignments/${editingId.value}`,body);else await api.post(`/courses/${courseId}/assignments`,body);showForm.value=false;message.value=editingId.value?'Đã cập nhật bài tập.':'Đã tạo bài tập.';await load()}catch(cause){error.value=cause instanceof Error?cause.message:'Không thể lưu bài tập'}finally{saving.value=false}}
async function remove(item:Assignment){if(!confirm(`Xóa bài tập “${item.title}”?`))return;try{await api.del(`/assignments/${item.id}`);await load()}catch(cause){error.value=cause instanceof Error?cause.message:'Không thể xóa bài tập'}}
async function saveRule(){error.value='';try{await api.put(`/courses/${courseId}/grades/rule`,{assignmentWeight:Number(rule.value.assignmentWeight),quizWeight:Number(rule.value.quizWeight),passingScore:Number(rule.value.passingScore)});message.value='Đã lưu quy tắc tính điểm.'}catch(cause){error.value=cause instanceof Error?cause.message:'Không thể lưu quy tắc điểm'}}
onMounted(load)
</script>

<template><InstructorLayout><main class="mx-auto max-w-6xl"><header class="flex flex-wrap items-end justify-between gap-4"><div><RouterLink to="/instructor/courses" class="text-sm font-bold text-purple-600">← Khóa học của tôi</RouterLink><p class="mt-4 text-sm font-bold uppercase tracking-wider text-purple-600">Sprint 7 · Assignment</p><h1 class="app-page-title mt-2">Bài tập và chấm điểm</h1><p class="app-page-description">Thiết lập hạn nộp, cho phép nộp lại và theo dõi kết quả học viên.</p></div><BaseButton size="lg" @click="create">+ Tạo bài tập</BaseButton></header>
<p v-if="message" class="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-700">{{message}}</p><p v-if="error" class="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{{error}}</p>
<section class="surface-card mt-7 p-6"><div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-xl font-black">Quy tắc điểm tổng kết</h2><p class="mt-1 text-sm text-slate-500">Tổng trọng số bài tập và quiz phải bằng 100%.</p></div><BaseButton variant="secondary" @click="saveRule">Lưu quy tắc</BaseButton></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><BaseInput id="assignment-weight" v-model="rule.assignmentWeight" type="number" label="Bài tập (%)"/><BaseInput id="quiz-weight" v-model="rule.quizWeight" type="number" label="Quiz (%)"/><BaseInput id="passing-score" v-model="rule.passingScore" type="number" label="Điểm đạt (%)"/></div></section>
<LoadingSpinner v-if="api.loading.value&&!items.length" class="py-20"/><section v-else-if="items.length" class="mt-7 grid gap-5 lg:grid-cols-2"><article v-for="item in items" :key="item.id" class="surface-card overflow-hidden"><div class="border-b border-slate-100 p-6 dark:border-slate-800"><div class="flex items-start justify-between gap-3"><span :class="['rounded-full px-3 py-1 text-xs font-bold',item.isPublished?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700']">{{item.isPublished?'Đã giao':'Bản nháp'}}</span><b class="text-purple-700">{{item.maxScore}} điểm</b></div><h2 class="mt-4 text-xl font-black">{{item.title}}</h2><p class="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{{item.description||'Chưa có mô tả.'}}</p></div><div class="p-6"><dl class="grid grid-cols-2 gap-4 text-sm"><div><dt class="text-slate-400">Hạn nộp</dt><dd class="mt-1 font-bold">{{formatDate(item.dueAt)}}</dd></div><div><dt class="text-slate-400">Bài đã nộp</dt><dd class="mt-1 font-bold">{{item._count?.submissions||0}}</dd></div><div><dt class="text-slate-400">Nộp lại</dt><dd class="mt-1 font-bold">{{item.allowResubmission?`Tối đa ${item.maxSubmissions} lần`:'Không'}}</dd></div><div><dt class="text-slate-400">Nộp trễ</dt><dd class="mt-1 font-bold">{{item.allowLateSubmissions?'Cho phép':'Không'}}</dd></div></dl><div class="mt-6 flex flex-wrap gap-2"><RouterLink :to="`/instructor/assignments/${item.id}/submissions`" class="flex-1"><BaseButton :full-width="true">Xem & chấm bài</BaseButton></RouterLink><BaseButton variant="secondary" @click="edit(item)">Sửa</BaseButton><BaseButton variant="ghost" @click="remove(item)">Xóa</BaseButton></div></div></article></section>
<section v-else class="surface-card mt-7 grid min-h-72 place-items-center p-8 text-center"><div><span class="text-5xl">📝</span><h2 class="mt-4 text-xl font-black">Chưa có bài tập</h2><p class="mt-2 text-sm text-slate-500">Tạo bài tập đầu tiên và đặt hạn nộp cho học viên.</p><BaseButton class="mt-5" @click="create">Tạo bài tập</BaseButton></div></section>
<BaseModal :show="showForm" :title="editingId?'Chỉnh sửa bài tập':'Tạo bài tập mới'" size="lg" @close="showForm=false"><form class="space-y-4" @submit.prevent="save"><BaseInput id="assignment-title" v-model="title" label="Tên bài tập" required/><BaseTextarea id="assignment-description" v-model="description" label="Mô tả" :rows="3"/><BaseTextarea id="assignment-instructions" v-model="instructions" label="Hướng dẫn thực hiện" :rows="5"/><div class="grid gap-4 sm:grid-cols-2"><BaseInput id="assignment-due" v-model="dueAt" type="datetime-local" label="Hạn nộp" required/><BaseInput id="assignment-max" v-model="maxScore" type="number" label="Điểm tối đa" required/></div><div class="grid gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-slate-800/50"><label class="flex items-center gap-3 text-sm font-semibold"><input v-model="allowResubmission" type="checkbox">Cho phép nộp lại</label><BaseInput v-if="allowResubmission" id="max-submissions" v-model="maxSubmissions" type="number" label="Số lần nộp tối đa"/><label class="flex items-center gap-3 text-sm font-semibold"><input v-model="allowLateSubmissions" type="checkbox">Cho phép nộp sau hạn</label><label class="flex items-center gap-3 text-sm font-semibold"><input v-model="isPublished" type="checkbox">Giao bài ngay cho học viên</label></div><div class="flex justify-end gap-3 pt-2"><BaseButton variant="secondary" @click="showForm=false">Hủy</BaseButton><BaseButton type="submit" :loading="saving">{{editingId?'Lưu thay đổi':'Tạo bài tập'}}</BaseButton></div></form></BaseModal></main></InstructorLayout></template>
