<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import InstructorLayout from '@/layouts/InstructorLayout.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import { useApi } from '@/composables/useApi'
import type { ApiResponse, Quiz, QuizQuestion } from '@/types'
const route=useRoute(),api=useApi(),lessonId=String(route.params.lessonId)
const quiz=ref<Quiz|null>(null),error=ref(''),form=ref({title:'Bài kiểm tra',description:'',passingScore:70,maxAttempts:3,timeLimitMinutes:15})
async function load(){const id=String(route.query.quizId||'');if(!id)return;try{const r=await api.get<ApiResponse<Quiz>>(`/quizzes/${id}`);quiz.value=r.data||null;if(quiz.value)form.value={title:quiz.value.title,description:quiz.value.description||'',passingScore:quiz.value.passingScore,maxAttempts:quiz.value.maxAttempts,timeLimitMinutes:quiz.value.timeLimitMinutes||15}}catch(e){error.value=e instanceof Error?e.message:'Không tải được quiz'}}
async function saveQuiz(){try{const payload={...form.value,description:form.value.description||null,timeLimitMinutes:Number(form.value.timeLimitMinutes)};const r=quiz.value?await api.patch<ApiResponse<Quiz>>(`/quizzes/${quiz.value.id}`,payload):await api.post<ApiResponse<Quiz>>(`/lessons/${lessonId}/quizzes`,payload);quiz.value=r.data||quiz.value;history.replaceState({},'',`${location.pathname}?quizId=${quiz.value?.id}`)}catch(e){error.value=e instanceof Error?e.message:'Không lưu được quiz'}}
async function addQuestion(){if(!quiz.value)return;const text=prompt('Nội dung câu hỏi?')?.trim();if(!text)return;await api.post(`/quizzes/${quiz.value.id}/questions`,{text,points:1,position:(quiz.value.questions?.length||0)+1});await reload()}
async function addOption(q:QuizQuestion){const text=prompt('Nội dung đáp án?')?.trim();if(!text)return;const isCorrect=confirm('Đây có phải đáp án đúng?');await api.post(`/questions/${q.id}/options`,{text,isCorrect,position:q.options.length+1});await reload()}
async function removeQuestion(q:QuizQuestion){if(confirm('Xóa câu hỏi này?')){await api.del(`/questions/${q.id}`);await reload()}}
async function removeOption(id:string){await api.del(`/options/${id}`);await reload()}
async function reload(){if(!quiz.value)return;const r=await api.get<ApiResponse<Quiz>>(`/quizzes/${quiz.value.id}`);quiz.value=r.data||null}
async function publish(){if(!quiz.value)return;await api.patch(`/quizzes/${quiz.value.id}`,{isPublished:!quiz.value.isPublished});await reload()}
onMounted(load)
</script>
<template><InstructorLayout><div class="max-w-4xl space-y-6"><div><button class="text-sm text-purple-600" @click="$router.back()">← Quay lại course builder</button><h1 class="mt-2 text-3xl font-extrabold">Quiz builder</h1></div><p v-if="error" class="rounded-xl bg-red-50 p-3 text-red-700">{{ error }}</p>
<form class="grid gap-4 rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="saveQuiz"><input v-model="form.title" required class="rounded-xl border p-3 dark:bg-slate-800" placeholder="Tên bài kiểm tra"><textarea v-model="form.description" class="rounded-xl border p-3 dark:bg-slate-800" placeholder="Mô tả"></textarea><div class="grid grid-cols-3 gap-3"><label>Điểm đạt<input v-model.number="form.passingScore" type="number" min="0" max="100" class="mt-1 w-full rounded-lg border p-2 dark:bg-slate-800"></label><label>Số lần làm<input v-model.number="form.maxAttempts" type="number" min="1" max="20" class="mt-1 w-full rounded-lg border p-2 dark:bg-slate-800"></label><label>Thời gian (phút)<input v-model.number="form.timeLimitMinutes" type="number" min="1" class="mt-1 w-full rounded-lg border p-2 dark:bg-slate-800"></label></div><div class="flex gap-3"><BaseButton type="submit">{{ quiz?'Lưu quiz':'Tạo quiz' }}</BaseButton><BaseButton v-if="quiz" type="button" variant="outline" @click="publish">{{ quiz.isPublished?'Chuyển về nháp':'Xuất bản' }}</BaseButton></div></form>
<div v-if="quiz" class="space-y-4"><div class="flex justify-between"><h2 class="text-xl font-bold">Câu hỏi ({{ quiz.questions?.length||0 }})</h2><BaseButton size="sm" @click="addQuestion">+ Câu hỏi</BaseButton></div><article v-for="(question,index) in quiz.questions" :key="question.id" class="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex justify-between"><h3 class="font-bold">{{ index+1 }}. {{ question.text }}</h3><button class="text-red-600" @click="removeQuestion(question)">Xóa</button></div><div class="mt-3 space-y-2"><div v-for="option in question.options" :key="option.id" class="flex justify-between rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><span><b :class="option.isCorrect?'text-emerald-600':''">{{ option.isCorrect?'✓':'○' }}</b> {{ option.text }}</span><button class="text-red-500" @click="removeOption(option.id)">Xóa</button></div><button class="text-sm font-semibold text-purple-600" @click="addOption(question)">+ Thêm đáp án</button></div></article></div>
</div></InstructorLayout></template>
